/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) tilt_qd_servo_thrust_dist_imp_mdl_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {27, 1, 1};
static const casadi_int casadi_s1[3] = {8, 1, 1};
static const casadi_int casadi_s2[3] = {47, 1, 1};

/* tilt_qd_servo_thrust_dist_imp_mdl_expl_ode_fun:(i0[27],i1[8],i2[47])->(o0[27]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  casadi_real a48, a49, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59;
  casadi_real a60, a61;
  a00=arg[0]? arg[0][3] : 0;
  if (res[0]!=0) res[0][0]=a00;
  a00=arg[0]? arg[0][4] : 0;
  if (res[0]!=0) res[0][1]=a00;
  a00=arg[0]? arg[0][5] : 0;
  if (res[0]!=0) res[0][2]=a00;
  a00=1.;
  a01=2.;
  a02=arg[0]? arg[0][8] : 0;
  a03=casadi_sq(a02);
  a03=(a01*a03);
  a04=(a00-a03);
  a05=arg[0]? arg[0][9] : 0;
  a06=casadi_sq(a05);
  a06=(a01*a06);
  a04=(a04-a06);
  a07=arg[2]? arg[2][12] : 0;
  a08=arg[2]? arg[2][11] : 0;
  a09=casadi_sq(a08);
  a10=casadi_sq(a07);
  a09=(a09+a10);
  a09=sqrt(a09);
  a10=(a07/a09);
  a11=arg[0]? arg[0][13] : 0;
  a12=sin(a11);
  a13=arg[0]? arg[0][17] : 0;
  a14=(a12*a13);
  a15=(a10*a14);
  a16=arg[2]? arg[2][16] : 0;
  a17=arg[2]? arg[2][15] : 0;
  a18=casadi_sq(a17);
  a19=casadi_sq(a16);
  a18=(a18+a19);
  a18=sqrt(a18);
  a19=(a16/a18);
  a20=arg[0]? arg[0][14] : 0;
  a21=sin(a20);
  a22=arg[0]? arg[0][18] : 0;
  a23=(a21*a22);
  a24=(a19*a23);
  a25=(a15+a24);
  a26=arg[2]? arg[2][20] : 0;
  a27=arg[2]? arg[2][19] : 0;
  a28=casadi_sq(a27);
  a29=casadi_sq(a26);
  a28=(a28+a29);
  a28=sqrt(a28);
  a29=(a26/a28);
  a30=arg[0]? arg[0][15] : 0;
  a31=sin(a30);
  a32=arg[0]? arg[0][19] : 0;
  a33=(a31*a32);
  a34=(a29*a33);
  a25=(a25+a34);
  a35=arg[2]? arg[2][24] : 0;
  a36=arg[2]? arg[2][23] : 0;
  a37=casadi_sq(a36);
  a38=casadi_sq(a35);
  a37=(a37+a38);
  a37=sqrt(a37);
  a38=(a35/a37);
  a39=arg[0]? arg[0][16] : 0;
  a40=sin(a39);
  a41=arg[0]? arg[0][20] : 0;
  a42=(a40*a41);
  a43=(a38*a42);
  a25=(a25+a43);
  a04=(a04*a25);
  a44=arg[0]? arg[0][7] : 0;
  a45=(a01*a44);
  a46=(a45*a02);
  a47=arg[0]? arg[0][6] : 0;
  a48=(a01*a47);
  a49=(a48*a05);
  a50=(a46-a49);
  a09=(a08/a09);
  a14=(a09*a14);
  a18=(a17/a18);
  a23=(a18*a23);
  a51=(a14+a23);
  a28=(a27/a28);
  a33=(a28*a33);
  a51=(a51+a33);
  a37=(a36/a37);
  a42=(a37*a42);
  a51=(a51+a42);
  a50=(a50*a51);
  a04=(a04-a50);
  a45=(a45*a05);
  a50=(a48*a02);
  a52=(a45+a50);
  a53=cos(a11);
  a54=(a53*a13);
  a55=cos(a20);
  a56=(a55*a22);
  a57=(a54+a56);
  a58=cos(a30);
  a59=(a58*a32);
  a57=(a57+a59);
  a60=cos(a39);
  a61=(a60*a41);
  a57=(a57+a61);
  a52=(a52*a57);
  a04=(a04+a52);
  a52=arg[0]? arg[0][21] : 0;
  a04=(a04+a52);
  a52=arg[2]? arg[2][35] : 0;
  a04=(a04+a52);
  a52=arg[2]? arg[2][4] : 0;
  a04=(a04/a52);
  if (res[0]!=0) res[0][3]=a04;
  a46=(a46+a49);
  a46=(a46*a25);
  a49=casadi_sq(a44);
  a49=(a01*a49);
  a00=(a00-a49);
  a06=(a00-a06);
  a06=(a06*a51);
  a46=(a46-a06);
  a06=(a01*a02);
  a06=(a06*a05);
  a48=(a48*a44);
  a49=(a06-a48);
  a49=(a49*a57);
  a46=(a46+a49);
  a49=arg[0]? arg[0][22] : 0;
  a46=(a46+a49);
  a49=arg[2]? arg[2][36] : 0;
  a46=(a46+a49);
  a46=(a46/a52);
  if (res[0]!=0) res[0][4]=a46;
  a45=(a45-a50);
  a45=(a45*a25);
  a06=(a06+a48);
  a06=(a06*a51);
  a45=(a45-a06);
  a00=(a00-a03);
  a00=(a00*a57);
  a45=(a45+a00);
  a00=arg[0]? arg[0][23] : 0;
  a45=(a45+a00);
  a00=arg[2]? arg[2][37] : 0;
  a45=(a45+a00);
  a45=(a45/a52);
  a52=arg[2]? arg[2][5] : 0;
  a45=(a45-a52);
  if (res[0]!=0) res[0][5]=a45;
  a45=arg[0]? arg[0][10] : 0;
  a52=(a45*a44);
  a00=arg[0]? arg[0][11] : 0;
  a57=(a00*a02);
  a52=(a52+a57);
  a57=arg[0]? arg[0][12] : 0;
  a03=(a57*a05);
  a52=(a52+a03);
  a52=(a52/a01);
  a52=(-a52);
  if (res[0]!=0) res[0][6]=a52;
  a52=(a45*a47);
  a03=(a57*a02);
  a52=(a52+a03);
  a03=(a00*a05);
  a52=(a52-a03);
  a52=(a52/a01);
  if (res[0]!=0) res[0][7]=a52;
  a52=(a00*a47);
  a03=(a57*a44);
  a52=(a52-a03);
  a05=(a45*a05);
  a52=(a52+a05);
  a52=(a52/a01);
  if (res[0]!=0) res[0][8]=a52;
  a47=(a57*a47);
  a44=(a00*a44);
  a47=(a47+a44);
  a02=(a45*a02);
  a47=(a47-a02);
  a47=(a47/a01);
  if (res[0]!=0) res[0][9]=a47;
  a47=(a07*a54);
  a01=arg[2]? arg[2][13] : 0;
  a02=(a01*a14);
  a47=(a47+a02);
  a02=arg[2]? arg[2][10] : 0;
  a02=(a02*a13);
  a44=arg[2]? arg[2][9] : 0;
  a02=(a02*a44);
  a12=(a12*a02);
  a10=(a10*a12);
  a52=arg[2]? arg[2][14] : 0;
  a52=(a52*a22);
  a52=(a52*a44);
  a21=(a21*a52);
  a19=(a19*a21);
  a10=(a10+a19);
  a19=arg[2]? arg[2][18] : 0;
  a19=(a19*a32);
  a19=(a19*a44);
  a31=(a31*a19);
  a29=(a29*a31);
  a10=(a10+a29);
  a29=arg[2]? arg[2][22] : 0;
  a29=(a29*a41);
  a29=(a29*a44);
  a40=(a40*a29);
  a38=(a38*a40);
  a10=(a10+a38);
  a47=(a47-a10);
  a10=(a16*a56);
  a38=arg[2]? arg[2][17] : 0;
  a44=(a38*a23);
  a10=(a10+a44);
  a47=(a47+a10);
  a10=(a26*a59);
  a44=arg[2]? arg[2][21] : 0;
  a05=(a44*a33);
  a10=(a10+a05);
  a47=(a47+a10);
  a10=(a35*a61);
  a05=arg[2]? arg[2][25] : 0;
  a03=(a05*a42);
  a10=(a10+a03);
  a47=(a47+a10);
  a10=arg[2]? arg[2][8] : 0;
  a03=(a10*a57);
  a06=(a00*a03);
  a51=arg[2]? arg[2][7] : 0;
  a48=(a51*a00);
  a25=(a57*a48);
  a06=(a06-a25);
  a47=(a47-a06);
  a06=arg[0]? arg[0][24] : 0;
  a47=(a47+a06);
  a06=arg[2]? arg[2][38] : 0;
  a47=(a47+a06);
  a06=arg[2]? arg[2][6] : 0;
  a47=(a47/a06);
  if (res[0]!=0) res[0][10]=a47;
  a09=(a09*a12);
  a18=(a18*a21);
  a09=(a09+a18);
  a28=(a28*a31);
  a09=(a09+a28);
  a37=(a37*a40);
  a09=(a09+a37);
  a01=(a01*a15);
  a54=(a08*a54);
  a01=(a01-a54);
  a09=(a09+a01);
  a38=(a38*a24);
  a56=(a17*a56);
  a38=(a38-a56);
  a09=(a09+a38);
  a44=(a44*a34);
  a59=(a27*a59);
  a44=(a44-a59);
  a09=(a09+a44);
  a05=(a05*a43);
  a61=(a36*a61);
  a05=(a05-a61);
  a09=(a09+a05);
  a06=(a06*a45);
  a57=(a57*a06);
  a03=(a45*a03);
  a57=(a57-a03);
  a09=(a09-a57);
  a57=arg[0]? arg[0][25] : 0;
  a09=(a09+a57);
  a57=arg[2]? arg[2][39] : 0;
  a09=(a09+a57);
  a09=(a09/a51);
  if (res[0]!=0) res[0][11]=a09;
  a09=arg[0]? arg[0][26] : 0;
  a45=(a45*a48);
  a00=(a00*a06);
  a45=(a45-a00);
  a53=(a53*a02);
  a55=(a55*a52);
  a53=(a53+a55);
  a58=(a58*a19);
  a53=(a53+a58);
  a60=(a60*a29);
  a53=(a53+a60);
  a08=(a08*a14);
  a07=(a07*a15);
  a08=(a08+a07);
  a53=(a53+a08);
  a17=(a17*a23);
  a16=(a16*a24);
  a17=(a17+a16);
  a53=(a53+a17);
  a27=(a27*a33);
  a26=(a26*a34);
  a27=(a27+a26);
  a53=(a53+a27);
  a36=(a36*a42);
  a35=(a35*a43);
  a36=(a36+a35);
  a53=(a53+a36);
  a45=(a45+a53);
  a09=(a09-a45);
  a45=arg[2]? arg[2][40] : 0;
  a09=(a09+a45);
  a09=(a09/a10);
  if (res[0]!=0) res[0][12]=a09;
  a09=arg[1]? arg[1][4] : 0;
  a09=(a09-a11);
  a11=arg[2]? arg[2][27] : 0;
  a09=(a09/a11);
  if (res[0]!=0) res[0][13]=a09;
  a09=arg[1]? arg[1][5] : 0;
  a09=(a09-a20);
  a09=(a09/a11);
  if (res[0]!=0) res[0][14]=a09;
  a09=arg[1]? arg[1][6] : 0;
  a09=(a09-a30);
  a09=(a09/a11);
  if (res[0]!=0) res[0][15]=a09;
  a09=arg[1]? arg[1][7] : 0;
  a09=(a09-a39);
  a09=(a09/a11);
  if (res[0]!=0) res[0][16]=a09;
  a09=arg[1]? arg[1][0] : 0;
  a09=(a09-a13);
  a13=arg[2]? arg[2][26] : 0;
  a09=(a09/a13);
  if (res[0]!=0) res[0][17]=a09;
  a09=arg[1]? arg[1][1] : 0;
  a09=(a09-a22);
  a09=(a09/a13);
  if (res[0]!=0) res[0][18]=a09;
  a09=arg[1]? arg[1][2] : 0;
  a09=(a09-a32);
  a09=(a09/a13);
  if (res[0]!=0) res[0][19]=a09;
  a09=arg[1]? arg[1][3] : 0;
  a09=(a09-a41);
  a09=(a09/a13);
  if (res[0]!=0) res[0][20]=a09;
  a09=0.;
  if (res[0]!=0) res[0][21]=a09;
  if (res[0]!=0) res[0][22]=a09;
  if (res[0]!=0) res[0][23]=a09;
  if (res[0]!=0) res[0][24]=a09;
  if (res[0]!=0) res[0][25]=a09;
  if (res[0]!=0) res[0][26]=a09;
  return 0;
}

CASADI_SYMBOL_EXPORT int tilt_qd_servo_thrust_dist_imp_mdl_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int tilt_qd_servo_thrust_dist_imp_mdl_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int tilt_qd_servo_thrust_dist_imp_mdl_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tilt_qd_servo_thrust_dist_imp_mdl_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int tilt_qd_servo_thrust_dist_imp_mdl_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tilt_qd_servo_thrust_dist_imp_mdl_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void tilt_qd_servo_thrust_dist_imp_mdl_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void tilt_qd_servo_thrust_dist_imp_mdl_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int tilt_qd_servo_thrust_dist_imp_mdl_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int tilt_qd_servo_thrust_dist_imp_mdl_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real tilt_qd_servo_thrust_dist_imp_mdl_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tilt_qd_servo_thrust_dist_imp_mdl_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tilt_qd_servo_thrust_dist_imp_mdl_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tilt_qd_servo_thrust_dist_imp_mdl_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tilt_qd_servo_thrust_dist_imp_mdl_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int tilt_qd_servo_thrust_dist_imp_mdl_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int tilt_qd_servo_thrust_dist_imp_mdl_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
