/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) tilt_bi_2_ord_servo_mdl_impl_dae_jac_x_xdot_u_z_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {17, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {0, 0, 1};
static const casadi_int casadi_s4[85] = 
  {17, 17, 0, 0, 0, 0, 1, 2,
  3, 9, 15, 21, 27, 33, 39, 45,
  52, 59, 62, 65, 0, 1, 2, 3,
  4, 5, 7, 8, 9, 3, 4, 5,
  6, 8, 9, 3, 4, 5, 6, 7,
  9, 3, 4, 5, 6, 7, 8, 6,
  7, 8, 9, 11, 12, 6, 7, 8,
  9, 10, 12, 6, 7, 8, 9, 10,
  11, 3, 4, 5, 10, 11, 12, 15,
  3, 4, 5, 10, 11, 12, 16, 11,
  13, 15, 11, 14, 16};
static const casadi_int casadi_s5[37] = 
  {17, 17, 0, 1, 2, 3, 4, 5,
  6, 7, 8, 9, 10, 11, 12, 13,
  14, 15, 16, 17, 0, 1, 2, 3,
  4, 5, 6, 7, 8, 9, 10, 11,
  12, 13, 14, 15, 16};
static const casadi_int casadi_s6[23] = 
  {17, 4, 0, 6, 12, 14, 16, 3,
  4, 5, 10, 11, 12, 3, 4, 5,
  10, 11, 12, 11, 15, 11, 16};
static const casadi_int casadi_s7[3] = {17, 0, 1};

/* tilt_bi_2_ord_servo_mdl_impl_dae_jac_x_xdot_u_z:(i0[17],i1[17],i2[4],i3[0],i4[],i5[4])->(o0[17x17,65nz],o1[17x17,17nz],o2[17x4,16nz],o3[17x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33;
  a00=-1.;
  if (res[0]!=0) res[0][0]=a00;
  if (res[0]!=0) res[0][1]=a00;
  if (res[0]!=0) res[0][2]=a00;
  a01=6.9232420157711450e-01;
  a02=arg[0]? arg[0][13] : 0;
  a03=cos(a02);
  a04=arg[2]? arg[2][0] : 0;
  a05=(a03*a04);
  a06=arg[0]? arg[0][14] : 0;
  a07=cos(a06);
  a08=arg[2]? arg[2][1] : 0;
  a09=(a07*a08);
  a05=(a05+a09);
  a09=2.;
  a10=arg[0]? arg[0][8] : 0;
  a11=(a09*a10);
  a12=(a05*a11);
  a13=(a01*a12);
  a13=(-a13);
  if (res[0]!=0) res[0][3]=a13;
  a02=sin(a02);
  a13=(a02*a04);
  a06=sin(a06);
  a14=(a06*a08);
  a13=(a13-a14);
  a14=arg[0]? arg[0][9] : 0;
  a15=(a09*a14);
  a16=(a13*a15);
  a17=arg[0]? arg[0][7] : 0;
  a18=(a09*a17);
  a19=(a05*a18);
  a20=(a16-a19);
  a20=(a01*a20);
  a20=(-a20);
  if (res[0]!=0) res[0][4]=a20;
  a20=(a13*a11);
  a21=(a01*a20);
  if (res[0]!=0) res[0][5]=a21;
  a21=5.0000000000000000e-01;
  a22=arg[0]? arg[0][10] : 0;
  a23=(a21*a22);
  a24=(-a23);
  if (res[0]!=0) res[0][6]=a24;
  a25=arg[0]? arg[0][11] : 0;
  a26=(a21*a25);
  a27=(-a26);
  if (res[0]!=0) res[0][7]=a27;
  a28=arg[0]? arg[0][12] : 0;
  a29=(a21*a28);
  a30=(-a29);
  if (res[0]!=0) res[0][8]=a30;
  a15=(a05*a15);
  a31=(a01*a15);
  a31=(-a31);
  if (res[0]!=0) res[0][9]=a31;
  a31=arg[0]? arg[0][6] : 0;
  a32=(a09*a31);
  a33=(a05*a32);
  a20=(a20-a33);
  a20=(a01*a20);
  a20=(-a20);
  if (res[0]!=0) res[0][10]=a20;
  a20=(a17+a17);
  a20=(a09*a20);
  a20=(a05*a20);
  a16=(a16-a20);
  a16=(a01*a16);
  a16=(-a16);
  if (res[0]!=0) res[0][11]=a16;
  if (res[0]!=0) res[0][12]=a23;
  if (res[0]!=0) res[0][13]=a29;
  if (res[0]!=0) res[0][14]=a27;
  a27=(a10+a10);
  a27=(a09*a27);
  a16=(a13*a27);
  a33=(a33-a16);
  a33=(a01*a33);
  a33=(-a33);
  if (res[0]!=0) res[0][15]=a33;
  a33=(a13*a18);
  a15=(a33+a15);
  a15=(a01*a15);
  a15=(-a15);
  if (res[0]!=0) res[0][16]=a15;
  a15=(a13*a32);
  a05=(a05*a27);
  a05=(a15+a05);
  a05=(a01*a05);
  if (res[0]!=0) res[0][17]=a05;
  if (res[0]!=0) res[0][18]=a26;
  if (res[0]!=0) res[0][19]=a30;
  if (res[0]!=0) res[0][20]=a23;
  a23=(a14+a14);
  a23=(a09*a23);
  a13=(a13*a23);
  a19=(a19-a13);
  a19=(a01*a19);
  a19=(-a19);
  if (res[0]!=0) res[0][21]=a19;
  a15=(a15+a12);
  a15=(a01*a15);
  a15=(-a15);
  if (res[0]!=0) res[0][22]=a15;
  a33=(a01*a33);
  a33=(-a33);
  if (res[0]!=0) res[0][23]=a33;
  if (res[0]!=0) res[0][24]=a29;
  if (res[0]!=0) res[0][25]=a26;
  if (res[0]!=0) res[0][26]=a24;
  a24=(a21*a17);
  if (res[0]!=0) res[0][27]=a24;
  a31=(a21*a31);
  a31=(-a31);
  if (res[0]!=0) res[0][28]=a31;
  a26=(a21*a14);
  a29=(-a26);
  if (res[0]!=0) res[0][29]=a29;
  a21=(a21*a10);
  if (res[0]!=0) res[0][30]=a21;
  a29=5.5950316119286072e+01;
  a33=5.5428999999999999e-02;
  a15=(a33*a28);
  a12=6.7850999999999995e-02;
  a19=(a12*a28);
  a15=(a15-a19);
  a15=(a29*a15);
  if (res[0]!=0) res[0][31]=a15;
  a15=1.4738176298064879e+01;
  a13=1.7873000000000000e-02;
  a23=(a13*a25);
  a30=(a33*a25);
  a30=(a23-a30);
  a30=(a15*a30);
  if (res[0]!=0) res[0][32]=a30;
  if (res[0]!=0) res[0][33]=a21;
  if (res[0]!=0) res[0][34]=a26;
  if (res[0]!=0) res[0][35]=a31;
  a30=(-a24);
  if (res[0]!=0) res[0][36]=a30;
  a30=1.8041097620379226e+01;
  a28=(a13*a28);
  a19=(a19-a28);
  a19=(a30*a19);
  if (res[0]!=0) res[0][37]=a19;
  a13=(a13*a22);
  a33=(a33*a22);
  a13=(a13-a33);
  a13=(a15*a13);
  if (res[0]!=0) res[0][38]=a13;
  if (res[0]!=0) res[0][39]=a26;
  a21=(-a21);
  if (res[0]!=0) res[0][40]=a21;
  if (res[0]!=0) res[0][41]=a24;
  if (res[0]!=0) res[0][42]=a31;
  a25=(a12*a25);
  a25=(a25-a23);
  a25=(a30*a25);
  if (res[0]!=0) res[0][43]=a25;
  a12=(a12*a22);
  a33=(a33-a12);
  a33=(a29*a33);
  if (res[0]!=0) res[0][44]=a33;
  a33=1.;
  a12=casadi_sq(a10);
  a12=(a09*a12);
  a22=(a33-a12);
  a25=casadi_sq(a14);
  a25=(a09*a25);
  a22=(a22-a25);
  a25=(a04*a03);
  a23=(a22*a25);
  a31=(a18*a14);
  a24=(a32*a10);
  a21=(a31+a24);
  a26=(a04*a02);
  a13=(a21*a26);
  a23=(a23-a13);
  a23=(a01*a23);
  a23=(-a23);
  if (res[0]!=0) res[0][45]=a23;
  a18=(a18*a10);
  a10=(a32*a14);
  a18=(a18+a10);
  a10=(a18*a25);
  a11=(a11*a14);
  a32=(a32*a17);
  a11=(a11-a32);
  a32=(a11*a26);
  a10=(a10-a32);
  a10=(a01*a10);
  a10=(-a10);
  if (res[0]!=0) res[0][46]=a10;
  a31=(a31-a24);
  a24=(a31*a25);
  a17=casadi_sq(a17);
  a09=(a09*a17);
  a09=(a33-a09);
  a09=(a09-a12);
  a12=(a09*a26);
  a24=(a24-a12);
  a24=(a01*a24);
  a24=(-a24);
  if (res[0]!=0) res[0][47]=a24;
  a24=2.3749999999999999e-01;
  a26=(a24*a26);
  a12=1.7200000000000000e-02;
  a04=(a12*a04);
  a17=(a04*a03);
  a26=(a26+a17);
  a26=(a30*a26);
  if (res[0]!=0) res[0][48]=a26;
  a26=1.2098000000000000e-01;
  a17=(a26*a25);
  a10=7.2757000000000005e+01;
  a17=(a17+a10);
  a17=(a29*a17);
  a17=(-a17);
  if (res[0]!=0) res[0][49]=a17;
  a04=(a04*a02);
  a25=(a24*a25);
  a04=(a04-a25);
  a04=(a15*a04);
  a04=(-a04);
  if (res[0]!=0) res[0][50]=a04;
  a04=1.9826416328310213e+04;
  if (res[0]!=0) res[0][51]=a04;
  a25=(a08*a07);
  a17=(a22*a25);
  a10=(a08*a06);
  a32=(a21*a10);
  a17=(a17+a32);
  a17=(a01*a17);
  if (res[0]!=0) res[0][52]=a17;
  a17=(a18*a25);
  a32=(a11*a10);
  a17=(a17+a32);
  a17=(a01*a17);
  if (res[0]!=0) res[0][53]=a17;
  a17=(a31*a25);
  a32=(a09*a10);
  a17=(a17+a32);
  a17=(a01*a17);
  if (res[0]!=0) res[0][54]=a17;
  a08=(a12*a08);
  a17=(a08*a07);
  a32=-2.3749999999999999e-01;
  a10=(a32*a10);
  a17=(a17+a10);
  a17=(a30*a17);
  if (res[0]!=0) res[0][55]=a17;
  a17=-7.2757000000000005e+01;
  a10=(a26*a25);
  a17=(a17-a10);
  a17=(a29*a17);
  a17=(-a17);
  if (res[0]!=0) res[0][56]=a17;
  a25=(a32*a25);
  a08=(a08*a06);
  a25=(a25-a08);
  a25=(a15*a25);
  a25=(-a25);
  if (res[0]!=0) res[0][57]=a25;
  if (res[0]!=0) res[0][58]=a04;
  a04=-6.4548760700497951e+02;
  if (res[0]!=0) res[0][59]=a04;
  if (res[0]!=0) res[0][60]=a00;
  a04=3.1437992206447389e+03;
  if (res[0]!=0) res[0][61]=a04;
  a25=6.4548760700497951e+02;
  if (res[0]!=0) res[0][62]=a25;
  if (res[0]!=0) res[0][63]=a00;
  if (res[0]!=0) res[0][64]=a04;
  if (res[1]!=0) res[1][0]=a33;
  if (res[1]!=0) res[1][1]=a33;
  if (res[1]!=0) res[1][2]=a33;
  if (res[1]!=0) res[1][3]=a33;
  if (res[1]!=0) res[1][4]=a33;
  if (res[1]!=0) res[1][5]=a33;
  if (res[1]!=0) res[1][6]=a33;
  if (res[1]!=0) res[1][7]=a33;
  if (res[1]!=0) res[1][8]=a33;
  if (res[1]!=0) res[1][9]=a33;
  if (res[1]!=0) res[1][10]=a33;
  if (res[1]!=0) res[1][11]=a33;
  if (res[1]!=0) res[1][12]=a33;
  if (res[1]!=0) res[1][13]=a33;
  if (res[1]!=0) res[1][14]=a33;
  if (res[1]!=0) res[1][15]=a33;
  if (res[1]!=0) res[1][16]=a33;
  a33=(a22*a02);
  a04=(a21*a03);
  a33=(a33+a04);
  a33=(a01*a33);
  a33=(-a33);
  if (res[2]!=0) res[2][0]=a33;
  a33=(a18*a02);
  a04=(a11*a03);
  a33=(a33+a04);
  a33=(a01*a33);
  a33=(-a33);
  if (res[2]!=0) res[2][1]=a33;
  a33=(a31*a02);
  a04=(a09*a03);
  a33=(a33+a04);
  a33=(a01*a33);
  a33=(-a33);
  if (res[2]!=0) res[2][2]=a33;
  a33=(a24*a03);
  a04=(a12*a02);
  a33=(a33-a04);
  a33=(a30*a33);
  a33=(-a33);
  if (res[2]!=0) res[2][3]=a33;
  a33=(a26*a02);
  a33=(a29*a33);
  a33=(-a33);
  if (res[2]!=0) res[2][4]=a33;
  a03=(a12*a03);
  a24=(a24*a02);
  a03=(a03+a24);
  a03=(a15*a03);
  if (res[2]!=0) res[2][5]=a03;
  a21=(a21*a07);
  a22=(a22*a06);
  a21=(a21-a22);
  a21=(a01*a21);
  a21=(-a21);
  if (res[2]!=0) res[2][6]=a21;
  a11=(a11*a07);
  a18=(a18*a06);
  a11=(a11-a18);
  a11=(a01*a11);
  a11=(-a11);
  if (res[2]!=0) res[2][7]=a11;
  a09=(a09*a07);
  a31=(a31*a06);
  a09=(a09-a31);
  a01=(a01*a09);
  a01=(-a01);
  if (res[2]!=0) res[2][8]=a01;
  a01=(a32*a07);
  a09=(a12*a06);
  a01=(a01-a09);
  a30=(a30*a01);
  a30=(-a30);
  if (res[2]!=0) res[2][9]=a30;
  a26=(a26*a06);
  a29=(a29*a26);
  if (res[2]!=0) res[2][10]=a29;
  a12=(a12*a07);
  a32=(a32*a06);
  a12=(a12+a32);
  a15=(a15*a12);
  a15=(-a15);
  if (res[2]!=0) res[2][11]=a15;
  a15=4.0707771498908969e+03;
  if (res[2]!=0) res[2][12]=a15;
  a15=-1.9826416328310213e+04;
  if (res[2]!=0) res[2][13]=a15;
  a12=-4.0707771498908969e+03;
  if (res[2]!=0) res[2][14]=a12;
  if (res[2]!=0) res[2][15]=a15;
  return 0;
}

CASADI_SYMBOL_EXPORT int tilt_bi_2_ord_servo_mdl_impl_dae_jac_x_xdot_u_z(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int tilt_bi_2_ord_servo_mdl_impl_dae_jac_x_xdot_u_z_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int tilt_bi_2_ord_servo_mdl_impl_dae_jac_x_xdot_u_z_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tilt_bi_2_ord_servo_mdl_impl_dae_jac_x_xdot_u_z_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int tilt_bi_2_ord_servo_mdl_impl_dae_jac_x_xdot_u_z_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tilt_bi_2_ord_servo_mdl_impl_dae_jac_x_xdot_u_z_release(int mem) {
}

CASADI_SYMBOL_EXPORT void tilt_bi_2_ord_servo_mdl_impl_dae_jac_x_xdot_u_z_incref(void) {
}

CASADI_SYMBOL_EXPORT void tilt_bi_2_ord_servo_mdl_impl_dae_jac_x_xdot_u_z_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int tilt_bi_2_ord_servo_mdl_impl_dae_jac_x_xdot_u_z_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int tilt_bi_2_ord_servo_mdl_impl_dae_jac_x_xdot_u_z_n_out(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_real tilt_bi_2_ord_servo_mdl_impl_dae_jac_x_xdot_u_z_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tilt_bi_2_ord_servo_mdl_impl_dae_jac_x_xdot_u_z_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tilt_bi_2_ord_servo_mdl_impl_dae_jac_x_xdot_u_z_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tilt_bi_2_ord_servo_mdl_impl_dae_jac_x_xdot_u_z_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    case 5: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tilt_bi_2_ord_servo_mdl_impl_dae_jac_x_xdot_u_z_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    case 3: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int tilt_bi_2_ord_servo_mdl_impl_dae_jac_x_xdot_u_z_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int tilt_bi_2_ord_servo_mdl_impl_dae_jac_x_xdot_u_z_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 4*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
