/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) tilt_bi_2_ord_servo_mdl_impl_dae_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {17, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {0, 0, 1};

/* tilt_bi_2_ord_servo_mdl_impl_dae_fun:(i0[17],i1[17],i2[4],i3[0],i4[],i5[4])->(o0[17]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27;
  a00=arg[1]? arg[1][0] : 0;
  a01=arg[0]? arg[0][3] : 0;
  a00=(a00-a01);
  if (res[0]!=0) res[0][0]=a00;
  a00=arg[1]? arg[1][1] : 0;
  a01=arg[0]? arg[0][4] : 0;
  a00=(a00-a01);
  if (res[0]!=0) res[0][1]=a00;
  a00=arg[1]? arg[1][2] : 0;
  a01=arg[0]? arg[0][5] : 0;
  a00=(a00-a01);
  if (res[0]!=0) res[0][2]=a00;
  a00=arg[1]? arg[1][3] : 0;
  a01=1.;
  a02=2.;
  a03=arg[0]? arg[0][8] : 0;
  a04=casadi_sq(a03);
  a04=(a02*a04);
  a05=(a01-a04);
  a06=arg[0]? arg[0][9] : 0;
  a07=casadi_sq(a06);
  a07=(a02*a07);
  a05=(a05-a07);
  a07=arg[0]? arg[0][13] : 0;
  a08=sin(a07);
  a09=arg[2]? arg[2][0] : 0;
  a10=(a08*a09);
  a11=arg[0]? arg[0][14] : 0;
  a12=sin(a11);
  a13=arg[2]? arg[2][1] : 0;
  a14=(a12*a13);
  a15=(a10-a14);
  a05=(a05*a15);
  a16=arg[0]? arg[0][7] : 0;
  a17=(a02*a16);
  a18=(a17*a06);
  a19=arg[0]? arg[0][6] : 0;
  a20=(a02*a19);
  a21=(a20*a03);
  a22=(a18+a21);
  a23=cos(a07);
  a24=(a23*a09);
  a25=cos(a11);
  a26=(a25*a13);
  a27=(a24+a26);
  a22=(a22*a27);
  a05=(a05+a22);
  a22=1.4444100000000000e+00;
  a05=(a05/a22);
  a00=(a00-a05);
  if (res[0]!=0) res[0][3]=a00;
  a00=arg[1]? arg[1][4] : 0;
  a17=(a17*a03);
  a05=(a20*a06);
  a17=(a17+a05);
  a17=(a17*a15);
  a05=(a02*a03);
  a05=(a05*a06);
  a20=(a20*a16);
  a05=(a05-a20);
  a05=(a05*a27);
  a17=(a17+a05);
  a17=(a17/a22);
  a00=(a00-a17);
  if (res[0]!=0) res[0][4]=a00;
  a00=arg[1]? arg[1][5] : 0;
  a18=(a18-a21);
  a18=(a18*a15);
  a15=casadi_sq(a16);
  a15=(a02*a15);
  a01=(a01-a15);
  a01=(a01-a04);
  a01=(a01*a27);
  a18=(a18+a01);
  a18=(a18/a22);
  a22=-9.7980000000000000e+00;
  a18=(a18+a22);
  a00=(a00-a18);
  if (res[0]!=0) res[0][5]=a00;
  a00=arg[1]? arg[1][6] : 0;
  a18=arg[0]? arg[0][10] : 0;
  a22=(a18*a16);
  a01=arg[0]? arg[0][11] : 0;
  a27=(a01*a03);
  a22=(a22+a27);
  a27=arg[0]? arg[0][12] : 0;
  a04=(a27*a06);
  a22=(a22+a04);
  a22=(a22/a02);
  a00=(a00+a22);
  if (res[0]!=0) res[0][6]=a00;
  a00=arg[1]? arg[1][7] : 0;
  a22=(a18*a19);
  a04=(a27*a03);
  a22=(a22+a04);
  a04=(a01*a06);
  a22=(a22-a04);
  a22=(a22/a02);
  a00=(a00-a22);
  if (res[0]!=0) res[0][7]=a00;
  a00=arg[1]? arg[1][8] : 0;
  a22=(a01*a19);
  a04=(a27*a16);
  a22=(a22-a04);
  a06=(a18*a06);
  a22=(a22+a06);
  a22=(a22/a02);
  a00=(a00-a22);
  if (res[0]!=0) res[0][8]=a00;
  a00=arg[1]? arg[1][9] : 0;
  a19=(a27*a19);
  a16=(a01*a16);
  a19=(a19+a16);
  a03=(a18*a03);
  a19=(a19-a03);
  a19=(a19/a02);
  a00=(a00-a19);
  if (res[0]!=0) res[0][9]=a00;
  a00=arg[1]? arg[1][10] : 0;
  a19=1.8041097620379226e+01;
  a02=2.3749999999999999e-01;
  a24=(a02*a24);
  a03=1.7200000000000000e-02;
  a09=(a03*a09);
  a08=(a08*a09);
  a03=(a03*a13);
  a12=(a12*a03);
  a08=(a08+a12);
  a24=(a24-a08);
  a08=-2.3749999999999999e-01;
  a26=(a08*a26);
  a24=(a24+a26);
  a26=6.7850999999999995e-02;
  a26=(a26*a27);
  a12=(a01*a26);
  a13=1.7873000000000000e-02;
  a13=(a13*a01);
  a16=(a27*a13);
  a12=(a12-a16);
  a24=(a24-a12);
  a19=(a19*a24);
  a00=(a00-a19);
  if (res[0]!=0) res[0][10]=a00;
  a00=arg[1]? arg[1][11] : 0;
  a19=5.5950316119286072e+01;
  a24=1.2098000000000000e-01;
  a12=(a24*a10);
  a24=(a24*a14);
  a12=(a12-a24);
  a24=5.5428999999999999e-02;
  a24=(a24*a18);
  a27=(a27*a24);
  a26=(a18*a26);
  a27=(a27-a26);
  a12=(a12-a27);
  a27=7.2757000000000005e+01;
  a26=arg[2]? arg[2][2] : 0;
  a26=(a26-a07);
  a26=(a27*a26);
  a07=1.1536799999999999e+01;
  a16=arg[0]? arg[0][15] : 0;
  a22=(a07*a16);
  a26=(a26-a22);
  a22=arg[2]? arg[2][3] : 0;
  a22=(a22-a11);
  a27=(a27*a22);
  a22=arg[0]? arg[0][16] : 0;
  a07=(a07*a22);
  a27=(a27-a07);
  a07=(a26-a27);
  a12=(a12-a07);
  a19=(a19*a12);
  a00=(a00-a19);
  if (res[0]!=0) res[0][11]=a00;
  a00=arg[1]? arg[1][12] : 0;
  a19=1.4738176298064879e+01;
  a25=(a25*a03);
  a23=(a23*a09);
  a25=(a25-a23);
  a02=(a02*a10);
  a25=(a25-a02);
  a08=(a08*a14);
  a25=(a25+a08);
  a18=(a18*a13);
  a01=(a01*a24);
  a18=(a18-a01);
  a25=(a25-a18);
  a19=(a19*a25);
  a00=(a00-a19);
  if (res[0]!=0) res[0][12]=a00;
  a00=arg[1]? arg[1][13] : 0;
  a00=(a00-a16);
  if (res[0]!=0) res[0][13]=a00;
  a00=arg[1]? arg[1][14] : 0;
  a00=(a00-a22);
  if (res[0]!=0) res[0][14]=a00;
  a00=arg[1]? arg[1][15] : 0;
  a22=3.6697000000000001e-03;
  a26=(a26/a22);
  a00=(a00-a26);
  if (res[0]!=0) res[0][15]=a00;
  a00=arg[1]? arg[1][16] : 0;
  a27=(a27/a22);
  a00=(a00-a27);
  if (res[0]!=0) res[0][16]=a00;
  return 0;
}

CASADI_SYMBOL_EXPORT int tilt_bi_2_ord_servo_mdl_impl_dae_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int tilt_bi_2_ord_servo_mdl_impl_dae_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int tilt_bi_2_ord_servo_mdl_impl_dae_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tilt_bi_2_ord_servo_mdl_impl_dae_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int tilt_bi_2_ord_servo_mdl_impl_dae_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tilt_bi_2_ord_servo_mdl_impl_dae_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void tilt_bi_2_ord_servo_mdl_impl_dae_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void tilt_bi_2_ord_servo_mdl_impl_dae_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int tilt_bi_2_ord_servo_mdl_impl_dae_fun_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int tilt_bi_2_ord_servo_mdl_impl_dae_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real tilt_bi_2_ord_servo_mdl_impl_dae_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tilt_bi_2_ord_servo_mdl_impl_dae_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tilt_bi_2_ord_servo_mdl_impl_dae_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tilt_bi_2_ord_servo_mdl_impl_dae_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    case 5: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tilt_bi_2_ord_servo_mdl_impl_dae_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int tilt_bi_2_ord_servo_mdl_impl_dae_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int tilt_bi_2_ord_servo_mdl_impl_dae_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
