/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) tilt_bi_2_ord_servo_mdl_impl_dae_fun_jac_x_xdot_u_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {17, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {0, 0, 1};
static const casadi_int casadi_s4[85] = 
  {17, 17, 0, 0, 0, 0, 1, 2,
  3, 9, 15, 21, 27, 33, 39, 45,
  52, 59, 62, 65, 0, 1, 2, 3,
  4, 5, 7, 8, 9, 3, 4, 5,
  6, 8, 9, 3, 4, 5, 6, 7,
  9, 3, 4, 5, 6, 7, 8, 6,
  7, 8, 9, 11, 12, 6, 7, 8,
  9, 10, 12, 6, 7, 8, 9, 10,
  11, 3, 4, 5, 10, 11, 12, 15,
  3, 4, 5, 10, 11, 12, 16, 11,
  13, 15, 11, 14, 16};
static const casadi_int casadi_s5[37] = 
  {17, 17, 0, 1, 2, 3, 4, 5,
  6, 7, 8, 9, 10, 11, 12, 13,
  14, 15, 16, 17, 0, 1, 2, 3,
  4, 5, 6, 7, 8, 9, 10, 11,
  12, 13, 14, 15, 16};
static const casadi_int casadi_s6[23] = 
  {17, 4, 0, 6, 12, 14, 16, 3,
  4, 5, 10, 11, 12, 3, 4, 5,
  10, 11, 12, 11, 15, 11, 16};

/* tilt_bi_2_ord_servo_mdl_impl_dae_fun_jac_x_xdot_u:(i0[17],i1[17],i2[4],i3[0],i4[],i5[4])->(o0[17],o1[17x17,65nz],o2[17x17,17nz],o3[17x4,16nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  casadi_real a48, a49, a50, a51, a52, a53, a54, a55;
  a00=arg[1]? arg[1][0] : 0;
  a01=arg[0]? arg[0][3] : 0;
  a00=(a00-a01);
  if (res[0]!=0) res[0][0]=a00;
  a00=arg[1]? arg[1][1] : 0;
  a01=arg[0]? arg[0][4] : 0;
  a00=(a00-a01);
  if (res[0]!=0) res[0][1]=a00;
  a00=arg[1]? arg[1][2] : 0;
  a01=arg[0]? arg[0][5] : 0;
  a00=(a00-a01);
  if (res[0]!=0) res[0][2]=a00;
  a00=arg[1]? arg[1][3] : 0;
  a01=1.;
  a02=2.;
  a03=arg[0]? arg[0][8] : 0;
  a04=casadi_sq(a03);
  a04=(a02*a04);
  a05=(a01-a04);
  a06=arg[0]? arg[0][9] : 0;
  a07=casadi_sq(a06);
  a07=(a02*a07);
  a05=(a05-a07);
  a07=arg[0]? arg[0][13] : 0;
  a08=sin(a07);
  a09=arg[2]? arg[2][0] : 0;
  a10=(a08*a09);
  a11=arg[0]? arg[0][14] : 0;
  a12=sin(a11);
  a13=arg[2]? arg[2][1] : 0;
  a14=(a12*a13);
  a15=(a10-a14);
  a16=(a05*a15);
  a17=arg[0]? arg[0][7] : 0;
  a18=(a02*a17);
  a19=(a18*a06);
  a20=arg[0]? arg[0][6] : 0;
  a21=(a02*a20);
  a22=(a21*a03);
  a23=(a19+a22);
  a24=cos(a07);
  a25=(a24*a09);
  a26=cos(a11);
  a27=(a26*a13);
  a28=(a25+a27);
  a29=(a23*a28);
  a16=(a16+a29);
  a29=1.4444100000000000e+00;
  a16=(a16/a29);
  a00=(a00-a16);
  if (res[0]!=0) res[0][3]=a00;
  a00=arg[1]? arg[1][4] : 0;
  a16=(a18*a03);
  a30=(a21*a06);
  a16=(a16+a30);
  a30=(a16*a15);
  a31=(a02*a03);
  a32=(a31*a06);
  a33=(a21*a17);
  a32=(a32-a33);
  a33=(a32*a28);
  a30=(a30+a33);
  a30=(a30/a29);
  a00=(a00-a30);
  if (res[0]!=0) res[0][4]=a00;
  a00=arg[1]? arg[1][5] : 0;
  a19=(a19-a22);
  a22=(a19*a15);
  a30=casadi_sq(a17);
  a30=(a02*a30);
  a30=(a01-a30);
  a30=(a30-a04);
  a04=(a30*a28);
  a22=(a22+a04);
  a22=(a22/a29);
  a29=-9.7980000000000000e+00;
  a22=(a22+a29);
  a00=(a00-a22);
  if (res[0]!=0) res[0][5]=a00;
  a00=arg[1]? arg[1][6] : 0;
  a22=arg[0]? arg[0][10] : 0;
  a29=(a22*a17);
  a04=arg[0]? arg[0][11] : 0;
  a33=(a04*a03);
  a29=(a29+a33);
  a33=arg[0]? arg[0][12] : 0;
  a34=(a33*a06);
  a29=(a29+a34);
  a29=(a29/a02);
  a00=(a00+a29);
  if (res[0]!=0) res[0][6]=a00;
  a00=arg[1]? arg[1][7] : 0;
  a29=(a22*a20);
  a34=(a33*a03);
  a29=(a29+a34);
  a34=(a04*a06);
  a29=(a29-a34);
  a29=(a29/a02);
  a00=(a00-a29);
  if (res[0]!=0) res[0][7]=a00;
  a00=arg[1]? arg[1][8] : 0;
  a29=(a04*a20);
  a34=(a33*a17);
  a29=(a29-a34);
  a34=(a22*a06);
  a29=(a29+a34);
  a29=(a29/a02);
  a00=(a00-a29);
  if (res[0]!=0) res[0][8]=a00;
  a00=arg[1]? arg[1][9] : 0;
  a29=(a33*a20);
  a34=(a04*a17);
  a29=(a29+a34);
  a34=(a22*a03);
  a29=(a29-a34);
  a29=(a29/a02);
  a00=(a00-a29);
  if (res[0]!=0) res[0][9]=a00;
  a00=arg[1]? arg[1][10] : 0;
  a29=1.8041097620379226e+01;
  a34=2.3749999999999999e-01;
  a25=(a34*a25);
  a35=1.7200000000000000e-02;
  a36=(a35*a09);
  a37=(a08*a36);
  a38=(a35*a13);
  a39=(a12*a38);
  a37=(a37+a39);
  a25=(a25-a37);
  a37=-2.3749999999999999e-01;
  a27=(a37*a27);
  a25=(a25+a27);
  a27=6.7850999999999995e-02;
  a39=(a27*a33);
  a40=(a04*a39);
  a41=1.7873000000000000e-02;
  a42=(a41*a04);
  a43=(a33*a42);
  a40=(a40-a43);
  a25=(a25-a40);
  a25=(a29*a25);
  a00=(a00-a25);
  if (res[0]!=0) res[0][10]=a00;
  a00=arg[1]? arg[1][11] : 0;
  a25=5.5950316119286072e+01;
  a40=1.2098000000000000e-01;
  a43=(a40*a10);
  a44=(a40*a14);
  a43=(a43-a44);
  a44=5.5428999999999999e-02;
  a45=(a44*a22);
  a46=(a33*a45);
  a47=(a22*a39);
  a46=(a46-a47);
  a43=(a43-a46);
  a46=7.2757000000000005e+01;
  a47=arg[2]? arg[2][2] : 0;
  a47=(a47-a07);
  a47=(a46*a47);
  a07=1.1536799999999999e+01;
  a48=arg[0]? arg[0][15] : 0;
  a49=(a07*a48);
  a47=(a47-a49);
  a49=arg[2]? arg[2][3] : 0;
  a49=(a49-a11);
  a49=(a46*a49);
  a11=arg[0]? arg[0][16] : 0;
  a07=(a07*a11);
  a49=(a49-a07);
  a07=(a47-a49);
  a43=(a43-a07);
  a43=(a25*a43);
  a00=(a00-a43);
  if (res[0]!=0) res[0][11]=a00;
  a00=arg[1]? arg[1][12] : 0;
  a43=1.4738176298064879e+01;
  a07=(a26*a38);
  a50=(a24*a36);
  a07=(a07-a50);
  a10=(a34*a10);
  a07=(a07-a10);
  a14=(a37*a14);
  a07=(a07+a14);
  a14=(a22*a42);
  a10=(a04*a45);
  a14=(a14-a10);
  a07=(a07-a14);
  a07=(a43*a07);
  a00=(a00-a07);
  if (res[0]!=0) res[0][12]=a00;
  a00=arg[1]? arg[1][13] : 0;
  a00=(a00-a48);
  if (res[0]!=0) res[0][13]=a00;
  a00=arg[1]? arg[1][14] : 0;
  a00=(a00-a11);
  if (res[0]!=0) res[0][14]=a00;
  a00=arg[1]? arg[1][15] : 0;
  a11=3.6697000000000001e-03;
  a47=(a47/a11);
  a00=(a00-a47);
  if (res[0]!=0) res[0][15]=a00;
  a00=arg[1]? arg[1][16] : 0;
  a49=(a49/a11);
  a00=(a00-a49);
  if (res[0]!=0) res[0][16]=a00;
  a00=-1.;
  if (res[1]!=0) res[1][0]=a00;
  if (res[1]!=0) res[1][1]=a00;
  if (res[1]!=0) res[1][2]=a00;
  a49=6.9232420157711450e-01;
  a11=(a28*a31);
  a47=(a49*a11);
  a47=(-a47);
  if (res[1]!=0) res[1][3]=a47;
  a47=(a02*a06);
  a48=(a15*a47);
  a07=(a28*a18);
  a14=(a48-a07);
  a14=(a49*a14);
  a14=(-a14);
  if (res[1]!=0) res[1][4]=a14;
  a31=(a15*a31);
  a14=(a49*a31);
  if (res[1]!=0) res[1][5]=a14;
  a14=5.0000000000000000e-01;
  a10=(a14*a22);
  a50=(-a10);
  if (res[1]!=0) res[1][6]=a50;
  a51=(a14*a04);
  a52=(-a51);
  if (res[1]!=0) res[1][7]=a52;
  a53=(a14*a33);
  a54=(-a53);
  if (res[1]!=0) res[1][8]=a54;
  a47=(a28*a47);
  a55=(a49*a47);
  a55=(-a55);
  if (res[1]!=0) res[1][9]=a55;
  a55=(a28*a21);
  a31=(a31-a55);
  a31=(a49*a31);
  a31=(-a31);
  if (res[1]!=0) res[1][10]=a31;
  a31=(a17+a17);
  a31=(a02*a31);
  a31=(a28*a31);
  a48=(a48-a31);
  a48=(a49*a48);
  a48=(-a48);
  if (res[1]!=0) res[1][11]=a48;
  if (res[1]!=0) res[1][12]=a10;
  if (res[1]!=0) res[1][13]=a53;
  if (res[1]!=0) res[1][14]=a52;
  a52=(a03+a03);
  a52=(a02*a52);
  a48=(a15*a52);
  a55=(a55-a48);
  a55=(a49*a55);
  a55=(-a55);
  if (res[1]!=0) res[1][15]=a55;
  a18=(a15*a18);
  a47=(a18+a47);
  a47=(a49*a47);
  a47=(-a47);
  if (res[1]!=0) res[1][16]=a47;
  a21=(a15*a21);
  a28=(a28*a52);
  a28=(a21+a28);
  a28=(a49*a28);
  if (res[1]!=0) res[1][17]=a28;
  if (res[1]!=0) res[1][18]=a51;
  if (res[1]!=0) res[1][19]=a54;
  if (res[1]!=0) res[1][20]=a10;
  a10=(a06+a06);
  a02=(a02*a10);
  a15=(a15*a02);
  a07=(a07-a15);
  a07=(a49*a07);
  a07=(-a07);
  if (res[1]!=0) res[1][21]=a07;
  a21=(a21+a11);
  a21=(a49*a21);
  a21=(-a21);
  if (res[1]!=0) res[1][22]=a21;
  a18=(a49*a18);
  a18=(-a18);
  if (res[1]!=0) res[1][23]=a18;
  if (res[1]!=0) res[1][24]=a53;
  if (res[1]!=0) res[1][25]=a51;
  if (res[1]!=0) res[1][26]=a50;
  a17=(a14*a17);
  if (res[1]!=0) res[1][27]=a17;
  a20=(a14*a20);
  a20=(-a20);
  if (res[1]!=0) res[1][28]=a20;
  a06=(a14*a06);
  a50=(-a06);
  if (res[1]!=0) res[1][29]=a50;
  a14=(a14*a03);
  if (res[1]!=0) res[1][30]=a14;
  a03=(a44*a33);
  a03=(a03-a39);
  a03=(a25*a03);
  if (res[1]!=0) res[1][31]=a03;
  a44=(a44*a04);
  a44=(a42-a44);
  a44=(a43*a44);
  if (res[1]!=0) res[1][32]=a44;
  if (res[1]!=0) res[1][33]=a14;
  if (res[1]!=0) res[1][34]=a06;
  if (res[1]!=0) res[1][35]=a20;
  a44=(-a17);
  if (res[1]!=0) res[1][36]=a44;
  a33=(a41*a33);
  a39=(a39-a33);
  a39=(a29*a39);
  if (res[1]!=0) res[1][37]=a39;
  a41=(a41*a22);
  a41=(a41-a45);
  a41=(a43*a41);
  if (res[1]!=0) res[1][38]=a41;
  if (res[1]!=0) res[1][39]=a06;
  a14=(-a14);
  if (res[1]!=0) res[1][40]=a14;
  if (res[1]!=0) res[1][41]=a17;
  if (res[1]!=0) res[1][42]=a20;
  a04=(a27*a04);
  a04=(a04-a42);
  a04=(a29*a04);
  if (res[1]!=0) res[1][43]=a04;
  a27=(a27*a22);
  a45=(a45-a27);
  a45=(a25*a45);
  if (res[1]!=0) res[1][44]=a45;
  a45=(a09*a24);
  a27=(a05*a45);
  a09=(a09*a08);
  a22=(a23*a09);
  a27=(a27-a22);
  a27=(a49*a27);
  a27=(-a27);
  if (res[1]!=0) res[1][45]=a27;
  a27=(a16*a45);
  a22=(a32*a09);
  a27=(a27-a22);
  a27=(a49*a27);
  a27=(-a27);
  if (res[1]!=0) res[1][46]=a27;
  a27=(a19*a45);
  a22=(a30*a09);
  a27=(a27-a22);
  a27=(a49*a27);
  a27=(-a27);
  if (res[1]!=0) res[1][47]=a27;
  a09=(a34*a09);
  a27=(a36*a24);
  a09=(a09+a27);
  a09=(a29*a09);
  if (res[1]!=0) res[1][48]=a09;
  a09=(a40*a45);
  a09=(a09+a46);
  a09=(a25*a09);
  a09=(-a09);
  if (res[1]!=0) res[1][49]=a09;
  a36=(a36*a08);
  a45=(a34*a45);
  a36=(a36-a45);
  a36=(a43*a36);
  a36=(-a36);
  if (res[1]!=0) res[1][50]=a36;
  a36=1.9826416328310213e+04;
  if (res[1]!=0) res[1][51]=a36;
  a45=(a13*a26);
  a09=(a05*a45);
  a13=(a13*a12);
  a46=(a23*a13);
  a09=(a09+a46);
  a09=(a49*a09);
  if (res[1]!=0) res[1][52]=a09;
  a09=(a16*a45);
  a46=(a32*a13);
  a09=(a09+a46);
  a09=(a49*a09);
  if (res[1]!=0) res[1][53]=a09;
  a09=(a19*a45);
  a46=(a30*a13);
  a09=(a09+a46);
  a09=(a49*a09);
  if (res[1]!=0) res[1][54]=a09;
  a09=(a38*a26);
  a13=(a37*a13);
  a09=(a09+a13);
  a09=(a29*a09);
  if (res[1]!=0) res[1][55]=a09;
  a09=-7.2757000000000005e+01;
  a13=(a40*a45);
  a09=(a09-a13);
  a09=(a25*a09);
  a09=(-a09);
  if (res[1]!=0) res[1][56]=a09;
  a45=(a37*a45);
  a38=(a38*a12);
  a45=(a45-a38);
  a45=(a43*a45);
  a45=(-a45);
  if (res[1]!=0) res[1][57]=a45;
  if (res[1]!=0) res[1][58]=a36;
  a36=-6.4548760700497951e+02;
  if (res[1]!=0) res[1][59]=a36;
  if (res[1]!=0) res[1][60]=a00;
  a36=3.1437992206447389e+03;
  if (res[1]!=0) res[1][61]=a36;
  a45=6.4548760700497951e+02;
  if (res[1]!=0) res[1][62]=a45;
  if (res[1]!=0) res[1][63]=a00;
  if (res[1]!=0) res[1][64]=a36;
  if (res[2]!=0) res[2][0]=a01;
  if (res[2]!=0) res[2][1]=a01;
  if (res[2]!=0) res[2][2]=a01;
  if (res[2]!=0) res[2][3]=a01;
  if (res[2]!=0) res[2][4]=a01;
  if (res[2]!=0) res[2][5]=a01;
  if (res[2]!=0) res[2][6]=a01;
  if (res[2]!=0) res[2][7]=a01;
  if (res[2]!=0) res[2][8]=a01;
  if (res[2]!=0) res[2][9]=a01;
  if (res[2]!=0) res[2][10]=a01;
  if (res[2]!=0) res[2][11]=a01;
  if (res[2]!=0) res[2][12]=a01;
  if (res[2]!=0) res[2][13]=a01;
  if (res[2]!=0) res[2][14]=a01;
  if (res[2]!=0) res[2][15]=a01;
  if (res[2]!=0) res[2][16]=a01;
  a01=(a05*a08);
  a36=(a23*a24);
  a01=(a01+a36);
  a01=(a49*a01);
  a01=(-a01);
  if (res[3]!=0) res[3][0]=a01;
  a01=(a16*a08);
  a36=(a32*a24);
  a01=(a01+a36);
  a01=(a49*a01);
  a01=(-a01);
  if (res[3]!=0) res[3][1]=a01;
  a01=(a19*a08);
  a36=(a30*a24);
  a01=(a01+a36);
  a01=(a49*a01);
  a01=(-a01);
  if (res[3]!=0) res[3][2]=a01;
  a01=(a34*a24);
  a36=(a35*a08);
  a01=(a01-a36);
  a01=(a29*a01);
  a01=(-a01);
  if (res[3]!=0) res[3][3]=a01;
  a01=(a40*a08);
  a01=(a25*a01);
  a01=(-a01);
  if (res[3]!=0) res[3][4]=a01;
  a24=(a35*a24);
  a34=(a34*a08);
  a24=(a24+a34);
  a24=(a43*a24);
  if (res[3]!=0) res[3][5]=a24;
  a23=(a23*a26);
  a05=(a05*a12);
  a23=(a23-a05);
  a23=(a49*a23);
  a23=(-a23);
  if (res[3]!=0) res[3][6]=a23;
  a32=(a32*a26);
  a16=(a16*a12);
  a32=(a32-a16);
  a32=(a49*a32);
  a32=(-a32);
  if (res[3]!=0) res[3][7]=a32;
  a30=(a30*a26);
  a19=(a19*a12);
  a30=(a30-a19);
  a49=(a49*a30);
  a49=(-a49);
  if (res[3]!=0) res[3][8]=a49;
  a49=(a37*a26);
  a30=(a35*a12);
  a49=(a49-a30);
  a29=(a29*a49);
  a29=(-a29);
  if (res[3]!=0) res[3][9]=a29;
  a40=(a40*a12);
  a25=(a25*a40);
  if (res[3]!=0) res[3][10]=a25;
  a35=(a35*a26);
  a37=(a37*a12);
  a35=(a35+a37);
  a43=(a43*a35);
  a43=(-a43);
  if (res[3]!=0) res[3][11]=a43;
  a43=4.0707771498908969e+03;
  if (res[3]!=0) res[3][12]=a43;
  a43=-1.9826416328310213e+04;
  if (res[3]!=0) res[3][13]=a43;
  a35=-4.0707771498908969e+03;
  if (res[3]!=0) res[3][14]=a35;
  if (res[3]!=0) res[3][15]=a43;
  return 0;
}

CASADI_SYMBOL_EXPORT int tilt_bi_2_ord_servo_mdl_impl_dae_fun_jac_x_xdot_u(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int tilt_bi_2_ord_servo_mdl_impl_dae_fun_jac_x_xdot_u_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int tilt_bi_2_ord_servo_mdl_impl_dae_fun_jac_x_xdot_u_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tilt_bi_2_ord_servo_mdl_impl_dae_fun_jac_x_xdot_u_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int tilt_bi_2_ord_servo_mdl_impl_dae_fun_jac_x_xdot_u_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tilt_bi_2_ord_servo_mdl_impl_dae_fun_jac_x_xdot_u_release(int mem) {
}

CASADI_SYMBOL_EXPORT void tilt_bi_2_ord_servo_mdl_impl_dae_fun_jac_x_xdot_u_incref(void) {
}

CASADI_SYMBOL_EXPORT void tilt_bi_2_ord_servo_mdl_impl_dae_fun_jac_x_xdot_u_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int tilt_bi_2_ord_servo_mdl_impl_dae_fun_jac_x_xdot_u_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int tilt_bi_2_ord_servo_mdl_impl_dae_fun_jac_x_xdot_u_n_out(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_real tilt_bi_2_ord_servo_mdl_impl_dae_fun_jac_x_xdot_u_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tilt_bi_2_ord_servo_mdl_impl_dae_fun_jac_x_xdot_u_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tilt_bi_2_ord_servo_mdl_impl_dae_fun_jac_x_xdot_u_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tilt_bi_2_ord_servo_mdl_impl_dae_fun_jac_x_xdot_u_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    case 5: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tilt_bi_2_ord_servo_mdl_impl_dae_fun_jac_x_xdot_u_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    case 3: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int tilt_bi_2_ord_servo_mdl_impl_dae_fun_jac_x_xdot_u_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int tilt_bi_2_ord_servo_mdl_impl_dae_fun_jac_x_xdot_u_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 4*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
