/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) tilt_qd_servo_dist_mdl_cost_y_0_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {23, 1, 1};
static const casadi_int casadi_s1[3] = {8, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {0, 0, 1};
static const casadi_int casadi_s4[3] = {41, 1, 1};
static const casadi_int casadi_s5[3] = {31, 1, 1};

/* tilt_qd_servo_dist_mdl_cost_y_0_fun:(i0[23],i1[8],i2[0],i3[],i4[41])->(o0[31]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  a00=arg[0]? arg[0][0] : 0;
  a01=1.;
  a02=2.;
  a03=arg[0]? arg[0][8] : 0;
  a04=casadi_sq(a03);
  a04=(a02*a04);
  a05=(a01-a04);
  a06=arg[0]? arg[0][9] : 0;
  a07=casadi_sq(a06);
  a07=(a02*a07);
  a05=(a05-a07);
  a08=arg[4]? arg[4][28] : 0;
  a09=(a05*a08);
  a10=arg[0]? arg[0][7] : 0;
  a11=(a02*a10);
  a12=(a11*a03);
  a13=arg[0]? arg[0][6] : 0;
  a14=(a02*a13);
  a15=(a14*a06);
  a16=(a12-a15);
  a17=arg[4]? arg[4][29] : 0;
  a18=(a16*a17);
  a09=(a09+a18);
  a11=(a11*a06);
  a18=(a14*a03);
  a19=(a11+a18);
  a20=arg[4]? arg[4][30] : 0;
  a21=(a19*a20);
  a09=(a09+a21);
  a00=(a00+a09);
  if (res[0]!=0) res[0][0]=a00;
  a00=arg[0]? arg[0][1] : 0;
  a12=(a12+a15);
  a15=(a12*a08);
  a09=casadi_sq(a10);
  a09=(a02*a09);
  a09=(a01-a09);
  a07=(a09-a07);
  a21=(a07*a17);
  a15=(a15+a21);
  a21=(a02*a03);
  a21=(a21*a06);
  a14=(a14*a10);
  a22=(a21-a14);
  a23=(a22*a20);
  a15=(a15+a23);
  a00=(a00+a15);
  if (res[0]!=0) res[0][1]=a00;
  a00=arg[0]? arg[0][2] : 0;
  a11=(a11-a18);
  a18=(a11*a08);
  a21=(a21+a14);
  a14=(a21*a17);
  a18=(a18+a14);
  a09=(a09-a04);
  a04=(a09*a20);
  a18=(a18+a04);
  a00=(a00+a18);
  if (res[0]!=0) res[0][2]=a00;
  a00=arg[0]? arg[0][3] : 0;
  a18=arg[0]? arg[0][12] : 0;
  a04=(a16*a18);
  a14=arg[0]? arg[0][11] : 0;
  a15=(a19*a14);
  a04=(a04-a15);
  a04=(a04*a08);
  a15=arg[0]? arg[0][10] : 0;
  a19=(a19*a15);
  a23=(a05*a18);
  a19=(a19-a23);
  a19=(a19*a17);
  a04=(a04+a19);
  a05=(a05*a14);
  a16=(a16*a15);
  a05=(a05-a16);
  a05=(a05*a20);
  a04=(a04+a05);
  a00=(a00+a04);
  if (res[0]!=0) res[0][3]=a00;
  a00=arg[0]? arg[0][4] : 0;
  a04=(a07*a18);
  a05=(a22*a14);
  a04=(a04-a05);
  a04=(a04*a08);
  a22=(a22*a15);
  a05=(a12*a18);
  a22=(a22-a05);
  a22=(a22*a17);
  a04=(a04+a22);
  a12=(a12*a14);
  a07=(a07*a15);
  a12=(a12-a07);
  a12=(a12*a20);
  a04=(a04+a12);
  a00=(a00+a04);
  if (res[0]!=0) res[0][4]=a00;
  a00=arg[0]? arg[0][5] : 0;
  a04=(a21*a18);
  a12=(a09*a14);
  a04=(a04-a12);
  a04=(a04*a08);
  a09=(a09*a15);
  a08=(a11*a18);
  a09=(a09-a08);
  a09=(a09*a17);
  a04=(a04+a09);
  a11=(a11*a14);
  a21=(a21*a15);
  a11=(a11-a21);
  a11=(a11*a20);
  a04=(a04+a11);
  a00=(a00+a04);
  if (res[0]!=0) res[0][5]=a00;
  a00=arg[4]? arg[4][0] : 0;
  if (res[0]!=0) res[0][6]=a00;
  a04=arg[4]? arg[4][32] : 0;
  a11=(a13*a04);
  a20=arg[4]? arg[4][31] : 0;
  a21=(a10*a20);
  a11=(a11+a21);
  a21=arg[4]? arg[4][34] : 0;
  a09=(a03*a21);
  a11=(a11+a09);
  a09=arg[4]? arg[4][33] : 0;
  a17=(a06*a09);
  a11=(a11-a17);
  a17=(a00*a11);
  a08=arg[4]? arg[4][1] : 0;
  a12=(a13*a20);
  a07=(a10*a04);
  a12=(a12-a07);
  a07=(a03*a09);
  a12=(a12-a07);
  a07=(a06*a21);
  a12=(a12-a07);
  a07=(a08*a12);
  a17=(a17-a07);
  a07=arg[4]? arg[4][2] : 0;
  a22=(a13*a21);
  a05=(a10*a09);
  a22=(a22+a05);
  a05=(a03*a04);
  a22=(a22-a05);
  a05=(a06*a20);
  a22=(a22+a05);
  a05=(a07*a22);
  a17=(a17-a05);
  a05=arg[4]? arg[4][3] : 0;
  a13=(a13*a09);
  a10=(a10*a21);
  a13=(a13-a10);
  a03=(a03*a20);
  a13=(a13+a03);
  a06=(a06*a04);
  a13=(a13+a06);
  a06=(a05*a13);
  a17=(a17+a06);
  a17=(a17+a08);
  if (res[0]!=0) res[0][7]=a17;
  a17=(a00*a13);
  a06=(a08*a22);
  a17=(a17+a06);
  a06=(a07*a12);
  a17=(a17-a06);
  a06=(a05*a11);
  a17=(a17-a06);
  a17=(a17+a07);
  if (res[0]!=0) res[0][8]=a17;
  a00=(a00*a22);
  a08=(a08*a13);
  a00=(a00-a08);
  a07=(a07*a11);
  a00=(a00+a07);
  a12=(a05*a12);
  a00=(a00-a12);
  a00=(a00+a05);
  if (res[0]!=0) res[0][9]=a00;
  a00=casadi_sq(a09);
  a00=(a02*a00);
  a05=(a01-a00);
  a12=casadi_sq(a21);
  a12=(a02*a12);
  a05=(a05-a12);
  a05=(a05*a15);
  a07=(a02*a04);
  a11=(a07*a09);
  a20=(a02*a20);
  a08=(a20*a21);
  a13=(a11+a08);
  a13=(a13*a14);
  a05=(a05+a13);
  a07=(a07*a21);
  a13=(a20*a09);
  a22=(a07-a13);
  a22=(a22*a18);
  a05=(a05+a22);
  if (res[0]!=0) res[0][10]=a05;
  a11=(a11-a08);
  a11=(a11*a15);
  a08=casadi_sq(a04);
  a08=(a02*a08);
  a01=(a01-a08);
  a12=(a01-a12);
  a12=(a12*a14);
  a11=(a11+a12);
  a02=(a02*a09);
  a02=(a02*a21);
  a20=(a20*a04);
  a04=(a02+a20);
  a04=(a04*a18);
  a11=(a11+a04);
  if (res[0]!=0) res[0][11]=a11;
  a07=(a07+a13);
  a07=(a07*a15);
  a02=(a02-a20);
  a02=(a02*a14);
  a07=(a07+a02);
  a01=(a01-a00);
  a01=(a01*a18);
  a07=(a07+a01);
  if (res[0]!=0) res[0][12]=a07;
  a07=arg[0]? arg[0][13] : 0;
  if (res[0]!=0) res[0][13]=a07;
  a01=arg[0]? arg[0][14] : 0;
  if (res[0]!=0) res[0][14]=a01;
  a18=arg[0]? arg[0][15] : 0;
  if (res[0]!=0) res[0][15]=a18;
  a00=arg[0]? arg[0][16] : 0;
  if (res[0]!=0) res[0][16]=a00;
  a02=arg[0]? arg[0][17] : 0;
  if (res[0]!=0) res[0][17]=a02;
  a02=arg[0]? arg[0][18] : 0;
  if (res[0]!=0) res[0][18]=a02;
  a02=arg[0]? arg[0][19] : 0;
  if (res[0]!=0) res[0][19]=a02;
  a02=arg[0]? arg[0][20] : 0;
  if (res[0]!=0) res[0][20]=a02;
  a02=arg[0]? arg[0][21] : 0;
  if (res[0]!=0) res[0][21]=a02;
  a02=arg[0]? arg[0][22] : 0;
  if (res[0]!=0) res[0][22]=a02;
  a02=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][23]=a02;
  a02=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][24]=a02;
  a02=arg[1]? arg[1][2] : 0;
  if (res[0]!=0) res[0][25]=a02;
  a02=arg[1]? arg[1][3] : 0;
  if (res[0]!=0) res[0][26]=a02;
  a02=arg[1]? arg[1][4] : 0;
  a02=(a02-a07);
  if (res[0]!=0) res[0][27]=a02;
  a02=arg[1]? arg[1][5] : 0;
  a02=(a02-a01);
  if (res[0]!=0) res[0][28]=a02;
  a02=arg[1]? arg[1][6] : 0;
  a02=(a02-a18);
  if (res[0]!=0) res[0][29]=a02;
  a02=arg[1]? arg[1][7] : 0;
  a02=(a02-a00);
  if (res[0]!=0) res[0][30]=a02;
  return 0;
}

CASADI_SYMBOL_EXPORT int tilt_qd_servo_dist_mdl_cost_y_0_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int tilt_qd_servo_dist_mdl_cost_y_0_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int tilt_qd_servo_dist_mdl_cost_y_0_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tilt_qd_servo_dist_mdl_cost_y_0_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int tilt_qd_servo_dist_mdl_cost_y_0_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tilt_qd_servo_dist_mdl_cost_y_0_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void tilt_qd_servo_dist_mdl_cost_y_0_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void tilt_qd_servo_dist_mdl_cost_y_0_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int tilt_qd_servo_dist_mdl_cost_y_0_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int tilt_qd_servo_dist_mdl_cost_y_0_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real tilt_qd_servo_dist_mdl_cost_y_0_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tilt_qd_servo_dist_mdl_cost_y_0_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tilt_qd_servo_dist_mdl_cost_y_0_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tilt_qd_servo_dist_mdl_cost_y_0_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tilt_qd_servo_dist_mdl_cost_y_0_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int tilt_qd_servo_dist_mdl_cost_y_0_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int tilt_qd_servo_dist_mdl_cost_y_0_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
