/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) tilt_qd_servo_dist_imp_mdl_cost_y_e_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {23, 1, 1};
static const casadi_int casadi_s1[3] = {0, 1, 1};
static const casadi_int casadi_s2[3] = {0, 0, 1};
static const casadi_int casadi_s3[3] = {47, 1, 1};
static const casadi_int casadi_s4[65] = 
  {23, 23, 0, 0, 0, 0, 0, 0,
  0, 6, 13, 20, 27, 31, 35, 39,
  39, 39, 39, 39, 39, 39, 39, 39,
  39, 39, 7, 8, 9, 10, 11, 12,
  6, 7, 8, 9, 10, 11, 12, 6,
  7, 8, 9, 10, 11, 12, 6, 7,
  8, 9, 10, 11, 12, 6, 7, 8,
  9, 6, 7, 8, 9, 6, 7, 8,
  9};

/* tilt_qd_servo_dist_imp_mdl_cost_y_e_hess:(i0[23],i1[0],i2[0],i3[23],i4[],i5[47])->(o0[23x23,39nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43;
  a00=2.;
  a01=arg[0]? arg[0][12] : 0;
  a02=arg[5]? arg[5][28] : 0;
  a03=arg[3]? arg[3][5] : 0;
  a04=(a02*a03);
  a05=(a01*a04);
  a06=arg[0]? arg[0][10] : 0;
  a07=arg[5]? arg[5][30] : 0;
  a08=(a07*a03);
  a09=(a06*a08);
  a05=(a05-a09);
  a09=arg[5]? arg[5][29] : 0;
  a10=arg[3]? arg[3][2] : 0;
  a11=(a09*a10);
  a05=(a05+a11);
  a05=(a00*a05);
  a11=arg[3]? arg[3][4] : 0;
  a12=(a09*a11);
  a13=(a06*a12);
  a14=arg[0]? arg[0][11] : 0;
  a15=(a02*a11);
  a16=(a14*a15);
  a13=(a13-a16);
  a16=arg[3]? arg[3][1] : 0;
  a17=(a07*a16);
  a13=(a13+a17);
  a13=(a00*a13);
  a17=(a05-a13);
  if (res[0]!=0) res[0][0]=a17;
  a18=arg[3]? arg[3][3] : 0;
  a19=(a09*a18);
  a20=(a06*a19);
  a21=(a02*a18);
  a22=(a14*a21);
  a20=(a20-a22);
  a22=arg[3]? arg[3][0] : 0;
  a23=(a07*a22);
  a20=(a20+a23);
  a20=(a00*a20);
  a23=(a14*a08);
  a03=(a09*a03);
  a24=(a01*a03);
  a23=(a23-a24);
  a24=(a02*a10);
  a23=(a23+a24);
  a23=(a00*a23);
  a24=(a20-a23);
  if (res[0]!=0) res[0][1]=a24;
  a11=(a07*a11);
  a25=(a14*a11);
  a26=(a01*a12);
  a25=(a25-a26);
  a26=(a02*a16);
  a25=(a25+a26);
  a25=(a00*a25);
  a26=(a01*a21);
  a18=(a07*a18);
  a27=(a06*a18);
  a26=(a26-a27);
  a27=(a09*a22);
  a26=(a26+a27);
  a26=(a00*a26);
  a27=(a25-a26);
  if (res[0]!=0) res[0][2]=a27;
  a28=arg[0]? arg[0][9] : 0;
  a29=(a00*a28);
  a30=(a18*a29);
  a31=arg[0]? arg[0][7] : 0;
  a32=(a00*a31);
  a33=(a08*a32);
  a34=(a12*a32);
  a35=(a33+a34);
  a30=(a30-a35);
  a35=arg[0]? arg[0][8] : 0;
  a36=(a00*a35);
  a37=(a19*a36);
  a30=(a30+a37);
  if (res[0]!=0) res[0][3]=a30;
  a37=(a11*a29);
  a38=(a08*a36);
  a37=(a37-a38);
  a39=(a15*a32);
  a37=(a37+a39);
  a39=(a21*a36);
  a37=(a37-a39);
  if (res[0]!=0) res[0][4]=a37;
  a40=(a03*a36);
  a41=(a04*a32);
  a40=(a40+a41);
  a41=(a12*a29);
  a40=(a40-a41);
  a42=(a21*a29);
  a40=(a40-a42);
  if (res[0]!=0) res[0][5]=a40;
  if (res[0]!=0) res[0][6]=a17;
  a17=(a06*a03);
  a43=(a14*a04);
  a17=(a17-a43);
  a07=(a07*a10);
  a17=(a17+a07);
  a17=(a00*a17);
  a17=(a00*a17);
  a07=(a01*a15);
  a06=(a06*a11);
  a07=(a07-a06);
  a09=(a09*a16);
  a07=(a07+a09);
  a07=(a00*a07);
  a07=(a00*a07);
  a09=(a17+a07);
  a09=(-a09);
  if (res[0]!=0) res[0][7]=a09;
  a25=(a25+a26);
  if (res[0]!=0) res[0][8]=a25;
  a23=(a23+a20);
  if (res[0]!=0) res[0][9]=a23;
  a31=(a31+a31);
  a31=(a00*a31);
  a20=(a11*a31);
  a26=arg[0]? arg[0][6] : 0;
  a26=(a00*a26);
  a09=(a08*a26);
  a16=(a03*a31);
  a16=(a09+a16);
  a20=(a20-a16);
  a16=(a12*a26);
  a20=(a20-a16);
  a06=(a18*a36);
  a20=(a20-a06);
  a06=(a19*a29);
  a20=(a20+a06);
  if (res[0]!=0) res[0][10]=a20;
  a08=(a08*a29);
  a06=(a04*a31);
  a06=(a08+a06);
  a10=(a11*a36);
  a06=(a06+a10);
  a10=(a15*a26);
  a06=(a06+a10);
  a06=(a06-a42);
  if (res[0]!=0) res[0][11]=a06;
  a42=(a04*a26);
  a10=(a03*a29);
  a42=(a42-a10);
  a12=(a12*a36);
  a42=(a42-a12);
  a31=(a15*a31);
  a42=(a42-a31);
  a42=(a42+a39);
  if (res[0]!=0) res[0][12]=a42;
  if (res[0]!=0) res[0][13]=a24;
  if (res[0]!=0) res[0][14]=a25;
  a14=(a14*a18);
  a01=(a01*a19);
  a14=(a14-a01);
  a02=(a02*a22);
  a14=(a14+a02);
  a14=(a00*a14);
  a14=(a00*a14);
  a17=(a17+a14);
  a17=(-a17);
  if (res[0]!=0) res[0][15]=a17;
  a05=(a05+a13);
  if (res[0]!=0) res[0][16]=a05;
  a35=(a35+a35);
  a35=(a00*a35);
  a13=(a03*a35);
  a08=(a08+a13);
  a41=(a41-a08);
  a08=(a18*a32);
  a41=(a41-a08);
  a08=(a19*a26);
  a41=(a41+a08);
  if (res[0]!=0) res[0][17]=a41;
  a08=(a04*a35);
  a08=(a08-a09);
  a09=(a11*a32);
  a08=(a08+a09);
  a09=(a15*a29);
  a08=(a08-a09);
  a09=(a18*a35);
  a08=(a08-a09);
  a09=(a21*a26);
  a08=(a08-a09);
  if (res[0]!=0) res[0][18]=a08;
  a13=(a03*a26);
  a29=(a04*a29);
  a13=(a13+a29);
  a13=(a13-a34);
  a35=(a19*a35);
  a13=(a13+a35);
  a21=(a21*a32);
  a13=(a13+a21);
  if (res[0]!=0) res[0][19]=a13;
  if (res[0]!=0) res[0][20]=a27;
  if (res[0]!=0) res[0][21]=a23;
  if (res[0]!=0) res[0][22]=a05;
  a07=(a07+a14);
  a07=(-a07);
  if (res[0]!=0) res[0][23]=a07;
  a28=(a28+a28);
  a00=(a00*a28);
  a28=(a11*a00);
  a28=(a28-a38);
  a28=(a28+a12);
  a12=(a18*a26);
  a28=(a28+a12);
  a12=(a19*a32);
  a28=(a28+a12);
  if (res[0]!=0) res[0][24]=a28;
  a11=(a11*a26);
  a33=(a33+a11);
  a11=(a15*a36);
  a33=(a33-a11);
  a18=(a18*a00);
  a33=(a33-a18);
  a33=(a33-a21);
  if (res[0]!=0) res[0][25]=a33;
  a04=(a04*a36);
  a03=(a03*a32);
  a04=(a04-a03);
  a04=(a04-a16);
  a15=(a15*a00);
  a04=(a04-a15);
  a19=(a19*a00);
  a04=(a04+a19);
  a04=(a04-a09);
  if (res[0]!=0) res[0][26]=a04;
  if (res[0]!=0) res[0][27]=a30;
  if (res[0]!=0) res[0][28]=a20;
  if (res[0]!=0) res[0][29]=a41;
  if (res[0]!=0) res[0][30]=a28;
  if (res[0]!=0) res[0][31]=a37;
  if (res[0]!=0) res[0][32]=a06;
  if (res[0]!=0) res[0][33]=a08;
  if (res[0]!=0) res[0][34]=a33;
  if (res[0]!=0) res[0][35]=a40;
  if (res[0]!=0) res[0][36]=a42;
  if (res[0]!=0) res[0][37]=a13;
  if (res[0]!=0) res[0][38]=a04;
  return 0;
}

CASADI_SYMBOL_EXPORT int tilt_qd_servo_dist_imp_mdl_cost_y_e_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int tilt_qd_servo_dist_imp_mdl_cost_y_e_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int tilt_qd_servo_dist_imp_mdl_cost_y_e_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tilt_qd_servo_dist_imp_mdl_cost_y_e_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int tilt_qd_servo_dist_imp_mdl_cost_y_e_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tilt_qd_servo_dist_imp_mdl_cost_y_e_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void tilt_qd_servo_dist_imp_mdl_cost_y_e_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void tilt_qd_servo_dist_imp_mdl_cost_y_e_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int tilt_qd_servo_dist_imp_mdl_cost_y_e_hess_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int tilt_qd_servo_dist_imp_mdl_cost_y_e_hess_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real tilt_qd_servo_dist_imp_mdl_cost_y_e_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tilt_qd_servo_dist_imp_mdl_cost_y_e_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tilt_qd_servo_dist_imp_mdl_cost_y_e_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tilt_qd_servo_dist_imp_mdl_cost_y_e_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s0;
    case 4: return casadi_s2;
    case 5: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tilt_qd_servo_dist_imp_mdl_cost_y_e_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int tilt_qd_servo_dist_imp_mdl_cost_y_e_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int tilt_qd_servo_dist_imp_mdl_cost_y_e_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
