/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) tilt_qd_servo_dist_imp_mdl_cost_y_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {23, 1, 1};
static const casadi_int casadi_s1[3] = {8, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {31, 1, 1};
static const casadi_int casadi_s4[3] = {0, 0, 1};
static const casadi_int casadi_s5[3] = {47, 1, 1};
static const casadi_int casadi_s6[155] = 
  {31, 31, 0, 5, 10, 15, 20, 20,
  20, 20, 20, 20, 20, 20, 20, 20,
  20, 34, 49, 64, 79, 85, 91, 97,
  103, 109, 115, 121, 121, 121, 121, 121,
  121, 121, 14, 15, 16, 17, 21, 14,
  15, 16, 17, 22, 14, 15, 16, 17,
  23, 14, 15, 16, 17, 24, 0, 1,
  2, 3, 15, 16, 17, 18, 19, 20,
  21, 22, 23, 24, 0, 1, 2, 3,
  14, 15, 16, 17, 18, 19, 20, 21,
  22, 23, 24, 0, 1, 2, 3, 14,
  15, 16, 17, 18, 19, 20, 21, 22,
  23, 24, 0, 1, 2, 3, 14, 15,
  16, 17, 18, 19, 20, 21, 22, 23,
  24, 14, 15, 16, 17, 19, 20, 14,
  15, 16, 17, 18, 20, 14, 15, 16,
  17, 18, 19, 0, 14, 15, 16, 17,
  21, 1, 14, 15, 16, 17, 22, 2,
  14, 15, 16, 17, 23, 3, 14, 15,
  16, 17, 24};

/* tilt_qd_servo_dist_imp_mdl_cost_y_hess:(i0[23],i1[8],i2[0],i3[31],i4[],i5[47])->(o0[31x31,121nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a000, a001, a002, a003, a004, a005, a006, a007, a008, a009, a010, a011;
  casadi_real a012, a013, a014, a015, a016, a017, a018, a019, a020, a021, a022, a023;
  casadi_real a024, a025, a026, a027, a028, a029, a030, a031, a032, a033, a034, a035;
  casadi_real a036, a037, a038, a039, a040, a041, a042, a043, a044, a045, a046, a047;
  casadi_real a048, a049, a050, a051, a052, a053, a054, a055, a056, a057, a058, a059;
  casadi_real a060, a061, a062, a063, a064, a065, a066, a067, a068, a069, a070, a071;
  casadi_real a072, a073, a074, a075, a076, a077, a078, a079, a080, a081, a082, a083;
  casadi_real a084, a085, a086, a087, a088, a089, a090, a091, a092, a093, a094, a095;
  casadi_real a096, a097, a098, a099, a100, a101, a102, a103, a104, a105, a106, a107;
  casadi_real a108, a109, a110, a111, a112, a113, a114, a115, a116, a117, a118, a119;
  casadi_real a120, a121, a122, a123, a124, a125, a126, a127, a128, a129, a130, a131;
  casadi_real a132, a133;
  a000=arg[0]? arg[0][13] : 0;
  a001=cos(a000);
  a002=arg[5]? arg[5][41] : 0;
  a003=arg[3]? arg[3][17] : 0;
  a002=(a002*a003);
  a003=arg[5]? arg[5][4] : 0;
  a002=(a002/a003);
  a004=2.;
  a005=arg[0]? arg[0][8] : 0;
  a006=(a004*a005);
  a007=(a002*a006);
  a008=arg[5]? arg[5][42] : 0;
  a009=arg[3]? arg[3][18] : 0;
  a008=(a008*a009);
  a008=(a008/a003);
  a009=arg[0]? arg[0][7] : 0;
  a010=(a004*a009);
  a011=(a008*a010);
  a012=(a007-a011);
  a013=(a001*a012);
  a000=sin(a000);
  a014=arg[5]? arg[5][12] : 0;
  a015=arg[5]? arg[5][11] : 0;
  a016=casadi_sq(a015);
  a017=casadi_sq(a014);
  a016=(a016+a017);
  a016=sqrt(a016);
  a017=(a014/a016);
  a018=arg[0]? arg[0][9] : 0;
  a019=(a004*a018);
  a020=(a008*a019);
  a021=arg[5]? arg[5][43] : 0;
  a022=arg[3]? arg[3][19] : 0;
  a021=(a021*a022);
  a021=(a021/a003);
  a003=(a021*a006);
  a022=(a020-a003);
  a023=(a017*a022);
  a016=(a015/a016);
  a024=(a021*a010);
  a025=(a002*a019);
  a026=(a024-a025);
  a027=(a016*a026);
  a023=(a023-a027);
  a027=(a000*a023);
  a013=(a013+a027);
  if (res[0]!=0) res[0][0]=a013;
  a027=(a009+a009);
  a028=(a004*a027);
  a029=(a021*a028);
  a030=arg[0]? arg[0][6] : 0;
  a030=(a004*a030);
  a031=(a008*a030);
  a029=(a029+a031);
  a025=(a025-a029);
  a029=(a001*a025);
  a032=(a021*a019);
  a033=(a008*a006);
  a034=(a032+a033);
  a035=(a017*a034);
  a036=(a021*a030);
  a037=(a008*a028);
  a037=(a036-a037);
  a037=(a037+a007);
  a007=(a016*a037);
  a035=(a035-a007);
  a007=(a000*a035);
  a029=(a029+a007);
  if (res[0]!=0) res[0][1]=a029;
  a007=(a005+a005);
  a038=(a004*a007);
  a039=(a021*a038);
  a020=(a020-a039);
  a039=(a002*a030);
  a020=(a020+a039);
  a040=(a001*a020);
  a011=(a011-a036);
  a036=(a002*a038);
  a011=(a011-a036);
  a036=(a017*a011);
  a041=(a002*a010);
  a032=(a032+a041);
  a042=(a016*a032);
  a036=(a036-a042);
  a042=(a000*a036);
  a040=(a040+a042);
  if (res[0]!=0) res[0][2]=a040;
  a033=(a033+a041);
  a041=(a001*a033);
  a024=(a024+a031);
  a031=(a018+a018);
  a042=(a004*a031);
  a043=(a002*a042);
  a024=(a024-a043);
  a043=(a017*a024);
  a044=(a008*a042);
  a003=(a003-a044);
  a003=(a003-a039);
  a039=(a016*a003);
  a043=(a043-a039);
  a039=(a000*a043);
  a041=(a041+a039);
  if (res[0]!=0) res[0][3]=a041;
  a039=arg[5]? arg[5][45] : 0;
  a044=arg[3]? arg[3][21] : 0;
  a039=(a039*a044);
  a044=arg[5]? arg[5][7] : 0;
  a039=(a039/a044);
  a045=(a016*a039);
  a046=arg[5]? arg[5][44] : 0;
  a047=arg[3]? arg[3][20] : 0;
  a046=(a046*a047);
  a047=arg[5]? arg[5][6] : 0;
  a046=(a046/a047);
  a048=(a017*a046);
  a045=(a045-a048);
  a048=arg[5]? arg[5][9] : 0;
  a049=arg[5]? arg[5][10] : 0;
  a050=(a048*a049);
  a051=(a045*a050);
  a052=arg[5]? arg[5][13] : 0;
  a053=(a052*a039);
  a054=arg[5]? arg[5][46] : 0;
  a055=arg[3]? arg[3][22] : 0;
  a054=(a054*a055);
  a055=arg[5]? arg[5][8] : 0;
  a054=(a054/a055);
  a056=(a014*a054);
  a053=(a053-a056);
  a053=(a017*a053);
  a052=(a052*a046);
  a056=(a015*a054);
  a052=(a052-a056);
  a052=(a016*a052);
  a053=(a053+a052);
  a051=(a051+a053);
  a052=(a010*a018);
  a056=(a030*a005);
  a057=(a052-a056);
  a057=(a057*a021);
  a058=(a010*a005);
  a059=(a030*a018);
  a060=(a058+a059);
  a060=(a060*a008);
  a057=(a057+a060);
  a060=1.;
  a061=casadi_sq(a005);
  a061=(a004*a061);
  a062=(a060-a061);
  a063=casadi_sq(a018);
  a063=(a004*a063);
  a062=(a062-a063);
  a062=(a062*a002);
  a057=(a057+a062);
  a062=(a017*a057);
  a064=(a006*a018);
  a065=(a030*a009);
  a066=(a064+a065);
  a066=(a066*a021);
  a067=casadi_sq(a009);
  a067=(a004*a067);
  a060=(a060-a067);
  a063=(a060-a063);
  a063=(a063*a008);
  a066=(a066+a063);
  a058=(a058-a059);
  a058=(a058*a002);
  a066=(a066+a058);
  a058=(a016*a066);
  a062=(a062-a058);
  a051=(a051+a062);
  a051=(a001*a051);
  a014=(a014*a046);
  a015=(a015*a039);
  a014=(a014-a015);
  a050=(a054*a050);
  a050=(a014-a050);
  a060=(a060-a061);
  a060=(a060*a021);
  a064=(a064-a065);
  a064=(a064*a008);
  a060=(a060+a064);
  a052=(a052+a056);
  a052=(a052*a002);
  a060=(a060+a052);
  a050=(a050+a060);
  a050=(a000*a050);
  a051=(a051-a050);
  if (res[0]!=0) res[0][4]=a051;
  a050=arg[0]? arg[0][14] : 0;
  a052=cos(a050);
  a056=(a052*a012);
  a050=sin(a050);
  a064=arg[5]? arg[5][16] : 0;
  a065=arg[5]? arg[5][15] : 0;
  a061=casadi_sq(a065);
  a015=casadi_sq(a064);
  a061=(a061+a015);
  a061=sqrt(a061);
  a015=(a064/a061);
  a058=(a015*a022);
  a061=(a065/a061);
  a059=(a061*a026);
  a058=(a058-a059);
  a059=(a050*a058);
  a056=(a056+a059);
  if (res[0]!=0) res[0][5]=a056;
  a059=(a052*a025);
  a063=(a015*a034);
  a067=(a061*a037);
  a063=(a063-a067);
  a067=(a050*a063);
  a059=(a059+a067);
  if (res[0]!=0) res[0][6]=a059;
  a067=(a052*a020);
  a068=(a015*a011);
  a069=(a061*a032);
  a068=(a068-a069);
  a069=(a050*a068);
  a067=(a067+a069);
  if (res[0]!=0) res[0][7]=a067;
  a069=(a052*a033);
  a070=(a015*a024);
  a071=(a061*a003);
  a070=(a070-a071);
  a071=(a050*a070);
  a069=(a069+a071);
  if (res[0]!=0) res[0][8]=a069;
  a071=arg[5]? arg[5][17] : 0;
  a072=(a071*a039);
  a073=(a064*a054);
  a072=(a072-a073);
  a072=(a015*a072);
  a071=(a071*a046);
  a073=(a065*a054);
  a071=(a071-a073);
  a071=(a061*a071);
  a072=(a072+a071);
  a071=(a061*a039);
  a073=(a015*a046);
  a071=(a071-a073);
  a073=arg[5]? arg[5][14] : 0;
  a074=(a048*a073);
  a075=(a071*a074);
  a075=(a072+a075);
  a076=(a015*a057);
  a077=(a061*a066);
  a076=(a076-a077);
  a075=(a075+a076);
  a075=(a052*a075);
  a064=(a064*a046);
  a065=(a065*a039);
  a064=(a064-a065);
  a074=(a054*a074);
  a074=(a064-a074);
  a074=(a074+a060);
  a074=(a050*a074);
  a075=(a075-a074);
  if (res[0]!=0) res[0][9]=a075;
  a074=arg[0]? arg[0][15] : 0;
  a065=cos(a074);
  a077=(a065*a012);
  a074=sin(a074);
  a078=arg[5]? arg[5][20] : 0;
  a079=arg[5]? arg[5][19] : 0;
  a080=casadi_sq(a079);
  a081=casadi_sq(a078);
  a080=(a080+a081);
  a080=sqrt(a080);
  a081=(a078/a080);
  a082=(a081*a022);
  a080=(a079/a080);
  a083=(a080*a026);
  a082=(a082-a083);
  a083=(a074*a082);
  a077=(a077+a083);
  if (res[0]!=0) res[0][10]=a077;
  a083=(a065*a025);
  a084=(a081*a034);
  a085=(a080*a037);
  a084=(a084-a085);
  a085=(a074*a084);
  a083=(a083+a085);
  if (res[0]!=0) res[0][11]=a083;
  a085=(a065*a020);
  a086=(a081*a011);
  a087=(a080*a032);
  a086=(a086-a087);
  a087=(a074*a086);
  a085=(a085+a087);
  if (res[0]!=0) res[0][12]=a085;
  a087=(a065*a033);
  a088=(a081*a024);
  a089=(a080*a003);
  a088=(a088-a089);
  a089=(a074*a088);
  a087=(a087+a089);
  if (res[0]!=0) res[0][13]=a087;
  a089=arg[5]? arg[5][21] : 0;
  a090=(a089*a039);
  a091=(a078*a054);
  a090=(a090-a091);
  a090=(a081*a090);
  a089=(a089*a046);
  a091=(a079*a054);
  a089=(a089-a091);
  a089=(a080*a089);
  a090=(a090+a089);
  a089=(a080*a039);
  a091=(a081*a046);
  a089=(a089-a091);
  a091=arg[5]? arg[5][18] : 0;
  a092=(a048*a091);
  a093=(a089*a092);
  a093=(a090+a093);
  a094=(a081*a057);
  a095=(a080*a066);
  a094=(a094-a095);
  a093=(a093+a094);
  a093=(a065*a093);
  a078=(a078*a046);
  a079=(a079*a039);
  a078=(a078-a079);
  a092=(a054*a092);
  a092=(a078-a092);
  a092=(a092+a060);
  a092=(a074*a092);
  a093=(a093-a092);
  if (res[0]!=0) res[0][14]=a093;
  a092=arg[0]? arg[0][16] : 0;
  a079=cos(a092);
  a095=(a079*a012);
  a092=sin(a092);
  a096=arg[5]? arg[5][24] : 0;
  a097=arg[5]? arg[5][23] : 0;
  a098=casadi_sq(a097);
  a099=casadi_sq(a096);
  a098=(a098+a099);
  a098=sqrt(a098);
  a099=(a096/a098);
  a022=(a099*a022);
  a098=(a097/a098);
  a026=(a098*a026);
  a022=(a022-a026);
  a026=(a092*a022);
  a095=(a095+a026);
  if (res[0]!=0) res[0][15]=a095;
  a026=(a079*a025);
  a034=(a099*a034);
  a037=(a098*a037);
  a034=(a034-a037);
  a037=(a092*a034);
  a026=(a026+a037);
  if (res[0]!=0) res[0][16]=a026;
  a037=(a079*a020);
  a011=(a099*a011);
  a032=(a098*a032);
  a011=(a011-a032);
  a032=(a092*a011);
  a037=(a037+a032);
  if (res[0]!=0) res[0][17]=a037;
  a032=(a079*a033);
  a024=(a099*a024);
  a003=(a098*a003);
  a024=(a024-a003);
  a003=(a092*a024);
  a032=(a032+a003);
  if (res[0]!=0) res[0][18]=a032;
  a003=arg[5]? arg[5][25] : 0;
  a100=(a003*a039);
  a101=(a096*a054);
  a100=(a100-a101);
  a100=(a099*a100);
  a003=(a003*a046);
  a101=(a097*a054);
  a003=(a003-a101);
  a003=(a098*a003);
  a100=(a100+a003);
  a003=(a098*a039);
  a101=(a099*a046);
  a003=(a003-a101);
  a101=arg[5]? arg[5][22] : 0;
  a102=(a048*a101);
  a103=(a003*a102);
  a103=(a100+a103);
  a057=(a099*a057);
  a066=(a098*a066);
  a057=(a057-a066);
  a103=(a103+a057);
  a103=(a079*a103);
  a096=(a096*a046);
  a097=(a097*a039);
  a096=(a096-a097);
  a102=(a054*a102);
  a102=(a096-a102);
  a102=(a102+a060);
  a102=(a092*a102);
  a103=(a103-a102);
  if (res[0]!=0) res[0][19]=a103;
  if (res[0]!=0) res[0][20]=a013;
  if (res[0]!=0) res[0][21]=a056;
  if (res[0]!=0) res[0][22]=a077;
  if (res[0]!=0) res[0][23]=a095;
  a095=arg[0]? arg[0][12] : 0;
  a077=arg[5]? arg[5][28] : 0;
  a056=arg[3]? arg[3][5] : 0;
  a013=(a077*a056);
  a102=(a095*a013);
  a097=arg[0]? arg[0][10] : 0;
  a066=arg[5]? arg[5][30] : 0;
  a104=(a066*a056);
  a105=(a097*a104);
  a102=(a102-a105);
  a105=arg[5]? arg[5][29] : 0;
  a106=arg[3]? arg[3][2] : 0;
  a107=(a105*a106);
  a102=(a102+a107);
  a102=(a004*a102);
  a107=arg[1]? arg[1][0] : 0;
  a108=(a000*a107);
  a016=(a016*a108);
  a109=arg[1]? arg[1][1] : 0;
  a110=(a050*a109);
  a061=(a061*a110);
  a016=(a016+a061);
  a061=arg[1]? arg[1][2] : 0;
  a111=(a074*a061);
  a080=(a080*a111);
  a016=(a016+a080);
  a080=arg[1]? arg[1][3] : 0;
  a112=(a092*a080);
  a098=(a098*a112);
  a016=(a016+a098);
  a098=(a016*a021);
  a098=(a004*a098);
  a113=(a001*a107);
  a114=(a052*a109);
  a113=(a113+a114);
  a114=(a065*a061);
  a113=(a113+a114);
  a114=(a079*a080);
  a113=(a113+a114);
  a114=(a113*a008);
  a114=(a004*a114);
  a115=(a098+a114);
  a115=(a102-a115);
  a116=arg[3]? arg[3][4] : 0;
  a117=(a105*a116);
  a118=(a097*a117);
  a119=arg[0]? arg[0][11] : 0;
  a120=(a077*a116);
  a121=(a119*a120);
  a118=(a118-a121);
  a121=arg[3]? arg[3][1] : 0;
  a122=(a066*a121);
  a118=(a118+a122);
  a118=(a004*a118);
  a115=(a115-a118);
  if (res[0]!=0) res[0][24]=a115;
  a122=(a113*a002);
  a122=(a004*a122);
  a017=(a017*a108);
  a015=(a015*a110);
  a017=(a017+a015);
  a081=(a081*a111);
  a017=(a017+a081);
  a099=(a099*a112);
  a017=(a017+a099);
  a099=(a017*a021);
  a099=(a004*a099);
  a112=(a122-a099);
  a081=(a119*a104);
  a056=(a105*a056);
  a111=(a095*a056);
  a081=(a081-a111);
  a111=(a077*a106);
  a081=(a081+a111);
  a081=(a004*a081);
  a112=(a112-a081);
  a111=arg[3]? arg[3][3] : 0;
  a015=(a105*a111);
  a110=(a097*a015);
  a108=(a077*a111);
  a123=(a119*a108);
  a110=(a110-a123);
  a123=arg[3]? arg[3][0] : 0;
  a124=(a066*a123);
  a110=(a110+a124);
  a110=(a004*a110);
  a112=(a112+a110);
  if (res[0]!=0) res[0][25]=a112;
  a124=(a017*a008);
  a124=(a004*a124);
  a125=(a016*a002);
  a125=(a004*a125);
  a126=(a124+a125);
  a116=(a066*a116);
  a127=(a119*a116);
  a128=(a095*a117);
  a127=(a127-a128);
  a128=(a077*a121);
  a127=(a127+a128);
  a127=(a004*a127);
  a126=(a126+a127);
  a128=(a095*a108);
  a111=(a066*a111);
  a129=(a097*a111);
  a128=(a128-a129);
  a129=(a105*a123);
  a128=(a128+a129);
  a128=(a004*a128);
  a126=(a126-a128);
  if (res[0]!=0) res[0][26]=a126;
  a129=(a111*a019);
  a130=(a104*a010);
  a131=(a117*a010);
  a131=(a130+a131);
  a129=(a129-a131);
  a131=(a015*a006);
  a129=(a129+a131);
  if (res[0]!=0) res[0][27]=a129;
  a131=(a116*a019);
  a132=(a104*a006);
  a131=(a131-a132);
  a133=(a120*a010);
  a131=(a131+a133);
  a133=(a108*a006);
  a131=(a131-a133);
  if (res[0]!=0) res[0][28]=a131;
  a009=(a009*a013);
  a009=(a004*a009);
  a133=(a005*a056);
  a133=(a004*a133);
  a009=(a009+a133);
  a133=(a018*a117);
  a133=(a004*a133);
  a009=(a009-a133);
  a133=(a018*a108);
  a133=(a004*a133);
  a009=(a009-a133);
  if (res[0]!=0) res[0][29]=a009;
  a023=(a107*a023);
  a023=(a001*a023);
  a133=(a107*a012);
  a133=(a000*a133);
  a023=(a023-a133);
  if (res[0]!=0) res[0][30]=a023;
  a058=(a109*a058);
  a058=(a052*a058);
  a133=(a109*a012);
  a133=(a050*a133);
  a058=(a058-a133);
  if (res[0]!=0) res[0][31]=a058;
  a082=(a061*a082);
  a082=(a065*a082);
  a133=(a061*a012);
  a133=(a074*a133);
  a082=(a082-a133);
  if (res[0]!=0) res[0][32]=a082;
  a022=(a080*a022);
  a022=(a079*a022);
  a012=(a080*a012);
  a012=(a092*a012);
  a022=(a022-a012);
  if (res[0]!=0) res[0][33]=a022;
  if (res[0]!=0) res[0][34]=a029;
  if (res[0]!=0) res[0][35]=a059;
  if (res[0]!=0) res[0][36]=a083;
  if (res[0]!=0) res[0][37]=a026;
  if (res[0]!=0) res[0][38]=a115;
  a016=(a016*a008);
  a016=(a004*a016);
  a016=(a004*a016);
  a113=(a113*a021);
  a113=(a004*a113);
  a113=(a004*a113);
  a021=(a016-a113);
  a008=(a097*a056);
  a115=(a119*a013);
  a008=(a008-a115);
  a066=(a066*a106);
  a008=(a008+a066);
  a008=(a004*a008);
  a008=(a004*a008);
  a021=(a021-a008);
  a066=(a095*a120);
  a097=(a097*a116);
  a066=(a066-a097);
  a105=(a105*a121);
  a066=(a066+a105);
  a066=(a004*a066);
  a066=(a004*a066);
  a021=(a021-a066);
  if (res[0]!=0) res[0][39]=a021;
  a124=(a124-a125);
  a124=(a124+a127);
  a124=(a124+a128);
  if (res[0]!=0) res[0][40]=a124;
  a099=(a099+a122);
  a099=(a099+a081);
  a099=(a099+a110);
  if (res[0]!=0) res[0][41]=a099;
  a110=(a116*a028);
  a081=(a104*a030);
  a122=(a056*a028);
  a122=(a081+a122);
  a110=(a110-a122);
  a122=(a117*a030);
  a110=(a110-a122);
  a122=(a111*a006);
  a110=(a110-a122);
  a122=(a015*a019);
  a110=(a110+a122);
  if (res[0]!=0) res[0][42]=a110;
  a104=(a104*a019);
  a028=(a013*a028);
  a028=(a104+a028);
  a122=(a116*a006);
  a028=(a028+a122);
  a122=(a120*a030);
  a028=(a028+a122);
  a122=(a108*a019);
  a028=(a028-a122);
  if (res[0]!=0) res[0][43]=a028;
  a122=(a030*a013);
  a128=(a018*a056);
  a128=(a004*a128);
  a122=(a122-a128);
  a128=(a004*a120);
  a027=(a027*a128);
  a122=(a122-a027);
  a027=(a005*a117);
  a027=(a004*a027);
  a122=(a122-a027);
  a005=(a005*a108);
  a005=(a004*a005);
  a122=(a122+a005);
  if (res[0]!=0) res[0][44]=a122;
  a035=(a107*a035);
  a035=(a001*a035);
  a005=(a107*a025);
  a005=(a000*a005);
  a035=(a035-a005);
  if (res[0]!=0) res[0][45]=a035;
  a063=(a109*a063);
  a063=(a052*a063);
  a005=(a109*a025);
  a005=(a050*a005);
  a063=(a063-a005);
  if (res[0]!=0) res[0][46]=a063;
  a084=(a061*a084);
  a084=(a065*a084);
  a005=(a061*a025);
  a005=(a074*a005);
  a084=(a084-a005);
  if (res[0]!=0) res[0][47]=a084;
  a034=(a080*a034);
  a034=(a079*a034);
  a025=(a080*a025);
  a025=(a092*a025);
  a034=(a034-a025);
  if (res[0]!=0) res[0][48]=a034;
  if (res[0]!=0) res[0][49]=a040;
  if (res[0]!=0) res[0][50]=a067;
  if (res[0]!=0) res[0][51]=a085;
  if (res[0]!=0) res[0][52]=a037;
  if (res[0]!=0) res[0][53]=a112;
  if (res[0]!=0) res[0][54]=a124;
  a017=(a017*a002);
  a017=(a004*a017);
  a017=(a004*a017);
  a113=(a113+a017);
  a113=(a113+a008);
  a119=(a119*a111);
  a095=(a095*a015);
  a119=(a119-a095);
  a077=(a077*a123);
  a119=(a119+a077);
  a119=(a004*a119);
  a119=(a004*a119);
  a113=(a113+a119);
  a113=(-a113);
  if (res[0]!=0) res[0][55]=a113;
  a114=(a114-a098);
  a114=(a114+a102);
  a114=(a114+a118);
  if (res[0]!=0) res[0][56]=a114;
  a118=(a117*a019);
  a102=(a056*a038);
  a104=(a104+a102);
  a118=(a118-a104);
  a104=(a111*a010);
  a118=(a118-a104);
  a104=(a015*a030);
  a118=(a118+a104);
  if (res[0]!=0) res[0][57]=a118;
  a104=(a013*a038);
  a104=(a104-a081);
  a081=(a116*a010);
  a104=(a104+a081);
  a019=(a120*a019);
  a104=(a104-a019);
  a038=(a111*a038);
  a104=(a104-a038);
  a038=(a108*a030);
  a104=(a104-a038);
  if (res[0]!=0) res[0][58]=a104;
  a018=(a018*a013);
  a018=(a004*a018);
  a038=(a030*a056);
  a018=(a018+a038);
  a038=(a010*a117);
  a018=(a018-a038);
  a038=(a010*a108);
  a018=(a018+a038);
  a004=(a004*a015);
  a007=(a007*a004);
  a018=(a018+a007);
  if (res[0]!=0) res[0][59]=a018;
  a036=(a107*a036);
  a036=(a001*a036);
  a007=(a107*a020);
  a007=(a000*a007);
  a036=(a036-a007);
  if (res[0]!=0) res[0][60]=a036;
  a068=(a109*a068);
  a068=(a052*a068);
  a007=(a109*a020);
  a007=(a050*a007);
  a068=(a068-a007);
  if (res[0]!=0) res[0][61]=a068;
  a086=(a061*a086);
  a086=(a065*a086);
  a007=(a061*a020);
  a007=(a074*a007);
  a086=(a086-a007);
  if (res[0]!=0) res[0][62]=a086;
  a011=(a080*a011);
  a011=(a079*a011);
  a020=(a080*a020);
  a020=(a092*a020);
  a011=(a011-a020);
  if (res[0]!=0) res[0][63]=a011;
  if (res[0]!=0) res[0][64]=a041;
  if (res[0]!=0) res[0][65]=a069;
  if (res[0]!=0) res[0][66]=a087;
  if (res[0]!=0) res[0][67]=a032;
  if (res[0]!=0) res[0][68]=a126;
  if (res[0]!=0) res[0][69]=a099;
  if (res[0]!=0) res[0][70]=a114;
  a016=(a016-a017);
  a016=(a016-a066);
  a016=(a016-a119);
  if (res[0]!=0) res[0][71]=a016;
  a016=(a116*a042);
  a016=(a016-a132);
  a132=(a117*a006);
  a016=(a016+a132);
  a132=(a111*a030);
  a016=(a016+a132);
  a015=(a015*a010);
  a016=(a016+a015);
  if (res[0]!=0) res[0][72]=a016;
  a116=(a116*a030);
  a130=(a130+a116);
  a120=(a120*a006);
  a130=(a130-a120);
  a111=(a111*a042);
  a130=(a130-a111);
  a111=(a108*a010);
  a130=(a130-a111);
  if (res[0]!=0) res[0][73]=a130;
  a006=(a006*a013);
  a010=(a010*a056);
  a006=(a006-a010);
  a128=(a031*a128);
  a006=(a006-a128);
  a117=(a030*a117);
  a006=(a006-a117);
  a030=(a030*a108);
  a006=(a006-a030);
  a031=(a031*a004);
  a006=(a006+a031);
  if (res[0]!=0) res[0][74]=a006;
  a043=(a107*a043);
  a043=(a001*a043);
  a031=(a107*a033);
  a031=(a000*a031);
  a043=(a043-a031);
  if (res[0]!=0) res[0][75]=a043;
  a070=(a109*a070);
  a070=(a052*a070);
  a031=(a109*a033);
  a031=(a050*a031);
  a070=(a070-a031);
  if (res[0]!=0) res[0][76]=a070;
  a088=(a061*a088);
  a088=(a065*a088);
  a031=(a061*a033);
  a031=(a074*a031);
  a088=(a088-a031);
  if (res[0]!=0) res[0][77]=a088;
  a024=(a080*a024);
  a024=(a079*a024);
  a033=(a080*a033);
  a033=(a092*a033);
  a024=(a024-a033);
  if (res[0]!=0) res[0][78]=a024;
  if (res[0]!=0) res[0][79]=a129;
  if (res[0]!=0) res[0][80]=a110;
  if (res[0]!=0) res[0][81]=a118;
  if (res[0]!=0) res[0][82]=a016;
  a016=(a047*a054);
  a118=(a054*a044);
  a016=(a016-a118);
  if (res[0]!=0) res[0][83]=a016;
  a118=(a039*a055);
  a047=(a047*a039);
  a118=(a118-a047);
  if (res[0]!=0) res[0][84]=a118;
  if (res[0]!=0) res[0][85]=a131;
  if (res[0]!=0) res[0][86]=a028;
  if (res[0]!=0) res[0][87]=a104;
  if (res[0]!=0) res[0][88]=a130;
  if (res[0]!=0) res[0][89]=a016;
  a044=(a044*a046);
  a046=(a046*a055);
  a044=(a044-a046);
  if (res[0]!=0) res[0][90]=a044;
  if (res[0]!=0) res[0][91]=a009;
  if (res[0]!=0) res[0][92]=a122;
  if (res[0]!=0) res[0][93]=a018;
  if (res[0]!=0) res[0][94]=a006;
  if (res[0]!=0) res[0][95]=a118;
  if (res[0]!=0) res[0][96]=a044;
  if (res[0]!=0) res[0][97]=a051;
  if (res[0]!=0) res[0][98]=a023;
  if (res[0]!=0) res[0][99]=a035;
  if (res[0]!=0) res[0][100]=a036;
  if (res[0]!=0) res[0][101]=a043;
  a049=(a049*a107);
  a049=(a049*a048);
  a045=(a049*a045);
  a053=(a107*a053);
  a045=(a045+a053);
  a062=(a107*a062);
  a045=(a045+a062);
  a045=(a045*a000);
  a014=(a107*a014);
  a049=(a049*a054);
  a014=(a014-a049);
  a107=(a107*a060);
  a014=(a014+a107);
  a014=(a014*a001);
  a045=(a045+a014);
  a045=(-a045);
  if (res[0]!=0) res[0][102]=a045;
  if (res[0]!=0) res[0][103]=a075;
  if (res[0]!=0) res[0][104]=a058;
  if (res[0]!=0) res[0][105]=a063;
  if (res[0]!=0) res[0][106]=a068;
  if (res[0]!=0) res[0][107]=a070;
  a072=(a109*a072);
  a073=(a073*a109);
  a073=(a073*a048);
  a071=(a073*a071);
  a072=(a072+a071);
  a076=(a109*a076);
  a072=(a072+a076);
  a072=(a072*a050);
  a064=(a109*a064);
  a073=(a073*a054);
  a064=(a064-a073);
  a109=(a109*a060);
  a064=(a064+a109);
  a064=(a064*a052);
  a072=(a072+a064);
  a072=(-a072);
  if (res[0]!=0) res[0][108]=a072;
  if (res[0]!=0) res[0][109]=a093;
  if (res[0]!=0) res[0][110]=a082;
  if (res[0]!=0) res[0][111]=a084;
  if (res[0]!=0) res[0][112]=a086;
  if (res[0]!=0) res[0][113]=a088;
  a090=(a061*a090);
  a091=(a091*a061);
  a091=(a091*a048);
  a089=(a091*a089);
  a090=(a090+a089);
  a094=(a061*a094);
  a090=(a090+a094);
  a090=(a090*a074);
  a078=(a061*a078);
  a091=(a091*a054);
  a078=(a078-a091);
  a061=(a061*a060);
  a078=(a078+a061);
  a078=(a078*a065);
  a090=(a090+a078);
  a090=(-a090);
  if (res[0]!=0) res[0][114]=a090;
  if (res[0]!=0) res[0][115]=a103;
  if (res[0]!=0) res[0][116]=a022;
  if (res[0]!=0) res[0][117]=a034;
  if (res[0]!=0) res[0][118]=a011;
  if (res[0]!=0) res[0][119]=a024;
  a100=(a080*a100);
  a101=(a101*a080);
  a101=(a101*a048);
  a003=(a101*a003);
  a100=(a100+a003);
  a057=(a080*a057);
  a100=(a100+a057);
  a100=(a100*a092);
  a096=(a080*a096);
  a101=(a101*a054);
  a096=(a096-a101);
  a080=(a080*a060);
  a096=(a096+a080);
  a096=(a096*a079);
  a100=(a100+a096);
  a100=(-a100);
  if (res[0]!=0) res[0][120]=a100;
  return 0;
}

CASADI_SYMBOL_EXPORT int tilt_qd_servo_dist_imp_mdl_cost_y_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int tilt_qd_servo_dist_imp_mdl_cost_y_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int tilt_qd_servo_dist_imp_mdl_cost_y_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tilt_qd_servo_dist_imp_mdl_cost_y_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int tilt_qd_servo_dist_imp_mdl_cost_y_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tilt_qd_servo_dist_imp_mdl_cost_y_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void tilt_qd_servo_dist_imp_mdl_cost_y_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void tilt_qd_servo_dist_imp_mdl_cost_y_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int tilt_qd_servo_dist_imp_mdl_cost_y_hess_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int tilt_qd_servo_dist_imp_mdl_cost_y_hess_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real tilt_qd_servo_dist_imp_mdl_cost_y_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tilt_qd_servo_dist_imp_mdl_cost_y_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tilt_qd_servo_dist_imp_mdl_cost_y_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tilt_qd_servo_dist_imp_mdl_cost_y_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    case 5: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tilt_qd_servo_dist_imp_mdl_cost_y_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int tilt_qd_servo_dist_imp_mdl_cost_y_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int tilt_qd_servo_dist_imp_mdl_cost_y_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
