/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) tilt_qd_servo_dist_imp_mdl_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {23, 1, 1};
static const casadi_int casadi_s1[3] = {8, 1, 1};
static const casadi_int casadi_s2[3] = {47, 1, 1};
static const casadi_int casadi_s3[3] = {31, 1, 1};

/* tilt_qd_servo_dist_imp_mdl_expl_vde_adj:(i0[23],i1[23],i2[8],i3[47])->(o0[31]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  casadi_real a48, a49, a50, a51, a52, a53, a54, a55;
  a00=0.;
  if (res[0]!=0) res[0][0]=a00;
  if (res[0]!=0) res[0][1]=a00;
  if (res[0]!=0) res[0][2]=a00;
  a00=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][3]=a00;
  a00=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][4]=a00;
  a00=arg[1]? arg[1][2] : 0;
  if (res[0]!=0) res[0][5]=a00;
  a00=arg[0]? arg[0][12] : 0;
  a01=5.0000000000000000e-01;
  a02=arg[1]? arg[1][9] : 0;
  a02=(a01*a02);
  a03=(a00*a02);
  a04=arg[0]? arg[0][11] : 0;
  a05=arg[1]? arg[1][8] : 0;
  a05=(a01*a05);
  a06=(a04*a05);
  a03=(a03+a06);
  a06=arg[0]? arg[0][10] : 0;
  a07=arg[1]? arg[1][7] : 0;
  a07=(a01*a07);
  a08=(a06*a07);
  a03=(a03+a08);
  a08=2.;
  a09=arg[0]? arg[0][7] : 0;
  a10=arg[3]? arg[3][11] : 0;
  a11=casadi_sq(a10);
  a12=arg[3]? arg[3][12] : 0;
  a13=casadi_sq(a12);
  a11=(a11+a13);
  a11=sqrt(a11);
  a13=(a10/a11);
  a14=arg[0]? arg[0][13] : 0;
  a15=sin(a14);
  a16=arg[2]? arg[2][0] : 0;
  a17=(a15*a16);
  a18=(a13*a17);
  a19=arg[3]? arg[3][15] : 0;
  a20=casadi_sq(a19);
  a21=arg[3]? arg[3][16] : 0;
  a22=casadi_sq(a21);
  a20=(a20+a22);
  a20=sqrt(a20);
  a22=(a19/a20);
  a23=arg[0]? arg[0][14] : 0;
  a24=sin(a23);
  a25=arg[2]? arg[2][1] : 0;
  a26=(a24*a25);
  a27=(a22*a26);
  a18=(a18+a27);
  a27=arg[3]? arg[3][19] : 0;
  a28=casadi_sq(a27);
  a29=arg[3]? arg[3][20] : 0;
  a30=casadi_sq(a29);
  a28=(a28+a30);
  a28=sqrt(a28);
  a30=(a27/a28);
  a31=arg[0]? arg[0][15] : 0;
  a32=sin(a31);
  a33=arg[2]? arg[2][2] : 0;
  a34=(a32*a33);
  a35=(a30*a34);
  a18=(a18+a35);
  a35=arg[3]? arg[3][23] : 0;
  a36=casadi_sq(a35);
  a37=arg[3]? arg[3][24] : 0;
  a38=casadi_sq(a37);
  a36=(a36+a38);
  a36=sqrt(a36);
  a38=(a35/a36);
  a39=arg[0]? arg[0][16] : 0;
  a40=sin(a39);
  a41=arg[2]? arg[2][3] : 0;
  a42=(a40*a41);
  a43=(a38*a42);
  a18=(a18+a43);
  a43=arg[1]? arg[1][5] : 0;
  a44=arg[3]? arg[3][4] : 0;
  a43=(a43/a44);
  a45=(a18*a43);
  a46=(a09*a45);
  a46=(a08*a46);
  a03=(a03-a46);
  a46=arg[0]? arg[0][8] : 0;
  a11=(a12/a11);
  a17=(a11*a17);
  a20=(a21/a20);
  a26=(a20*a26);
  a17=(a17+a26);
  a28=(a29/a28);
  a34=(a28*a34);
  a17=(a17+a34);
  a36=(a37/a36);
  a42=(a36*a42);
  a17=(a17+a42);
  a42=(a17*a43);
  a34=(a46*a42);
  a34=(a08*a34);
  a03=(a03-a34);
  a14=cos(a14);
  a34=(a14*a16);
  a23=cos(a23);
  a26=(a23*a25);
  a34=(a34+a26);
  a31=cos(a31);
  a26=(a31*a33);
  a34=(a34+a26);
  a39=cos(a39);
  a26=(a39*a41);
  a34=(a34+a26);
  a26=arg[1]? arg[1][4] : 0;
  a26=(a26/a44);
  a47=(a34*a26);
  a48=(a09*a47);
  a48=(a08*a48);
  a03=(a03-a48);
  a48=arg[0]? arg[0][9] : 0;
  a49=(a17*a26);
  a50=(a48*a49);
  a50=(a08*a50);
  a03=(a03+a50);
  a50=arg[1]? arg[1][3] : 0;
  a50=(a50/a44);
  a44=(a34*a50);
  a51=(a46*a44);
  a51=(a08*a51);
  a03=(a03+a51);
  a51=(a18*a50);
  a52=(a48*a51);
  a52=(a08*a52);
  a03=(a03+a52);
  if (res[0]!=0) res[0][6]=a03;
  a03=(a04*a02);
  a52=(a00*a05);
  a03=(a03-a52);
  a52=arg[1]? arg[1][6] : 0;
  a01=(a01*a52);
  a52=(a06*a01);
  a03=(a03-a52);
  a52=(a09+a09);
  a34=(a34*a43);
  a34=(a08*a34);
  a53=(a52*a34);
  a03=(a03-a53);
  a53=arg[0]? arg[0][6] : 0;
  a54=(a08*a53);
  a55=(a54*a45);
  a03=(a03-a55);
  a55=(a48*a42);
  a55=(a08*a55);
  a03=(a03+a55);
  a55=(a54*a47);
  a03=(a03-a55);
  a18=(a18*a26);
  a18=(a08*a18);
  a52=(a52*a18);
  a03=(a03+a52);
  a52=(a46*a49);
  a52=(a08*a52);
  a03=(a03+a52);
  a52=(a48*a44);
  a52=(a08*a52);
  a03=(a03+a52);
  a52=(a46*a51);
  a52=(a08*a52);
  a03=(a03-a52);
  if (res[0]!=0) res[0][7]=a03;
  a03=(a00*a07);
  a52=(a06*a02);
  a03=(a03-a52);
  a52=(a04*a01);
  a03=(a03-a52);
  a52=(a46+a46);
  a34=(a52*a34);
  a03=(a03-a34);
  a34=(a48*a45);
  a34=(a08*a34);
  a03=(a03-a34);
  a34=(a54*a42);
  a03=(a03-a34);
  a34=(a48*a47);
  a34=(a08*a34);
  a03=(a03+a34);
  a34=(a08*a09);
  a55=(a34*a49);
  a03=(a03+a55);
  a55=(a54*a44);
  a03=(a03+a55);
  a55=(a34*a51);
  a03=(a03-a55);
  a17=(a17*a50);
  a17=(a08*a17);
  a52=(a52*a17);
  a03=(a03-a52);
  if (res[0]!=0) res[0][8]=a03;
  a03=(a06*a05);
  a52=(a04*a07);
  a03=(a03-a52);
  a52=(a00*a01);
  a03=(a03-a52);
  a52=(a08*a46);
  a45=(a52*a45);
  a03=(a03-a45);
  a42=(a34*a42);
  a03=(a03+a42);
  a47=(a52*a47);
  a03=(a03+a47);
  a47=(a48+a48);
  a18=(a47*a18);
  a03=(a03+a18);
  a49=(a54*a49);
  a03=(a03+a49);
  a44=(a34*a44);
  a03=(a03+a44);
  a51=(a54*a51);
  a03=(a03+a51);
  a47=(a47*a17);
  a03=(a03-a47);
  if (res[0]!=0) res[0][9]=a03;
  a03=arg[3]? arg[3][8] : 0;
  a47=(a03*a00);
  a17=arg[1]? arg[1][11] : 0;
  a51=arg[3]? arg[3][7] : 0;
  a17=(a17/a51);
  a44=(a47*a17);
  a49=(a51*a04);
  a18=arg[1]? arg[1][12] : 0;
  a18=(a18/a03);
  a42=(a49*a18);
  a44=(a44-a42);
  a42=arg[3]? arg[3][6] : 0;
  a45=(a04*a18);
  a55=(a00*a17);
  a45=(a45-a55);
  a45=(a42*a45);
  a44=(a44+a45);
  a45=(a46*a02);
  a44=(a44-a45);
  a45=(a48*a05);
  a44=(a44+a45);
  a45=(a53*a07);
  a44=(a44+a45);
  a45=(a09*a01);
  a44=(a44-a45);
  if (res[0]!=0) res[0][10]=a44;
  a44=(a42*a06);
  a45=(a44*a18);
  a55=arg[1]? arg[1][10] : 0;
  a55=(a55/a42);
  a00=(a00*a55);
  a42=(a06*a18);
  a00=(a00-a42);
  a51=(a51*a00);
  a45=(a45+a51);
  a47=(a47*a55);
  a45=(a45-a47);
  a47=(a09*a02);
  a45=(a45+a47);
  a47=(a53*a05);
  a45=(a45+a47);
  a47=(a48*a07);
  a45=(a45-a47);
  a47=(a46*a01);
  a45=(a45-a47);
  if (res[0]!=0) res[0][11]=a45;
  a49=(a49*a55);
  a44=(a44*a17);
  a49=(a49-a44);
  a06=(a06*a17);
  a04=(a04*a55);
  a06=(a06-a04);
  a03=(a03*a06);
  a49=(a49+a03);
  a53=(a53*a02);
  a49=(a49+a53);
  a05=(a09*a05);
  a49=(a49-a05);
  a07=(a46*a07);
  a49=(a49+a07);
  a01=(a48*a01);
  a49=(a49-a01);
  if (res[0]!=0) res[0][12]=a49;
  a49=arg[3]? arg[3][10] : 0;
  a01=(a49*a16);
  a07=arg[3]? arg[3][9] : 0;
  a01=(a01*a07);
  a05=(a13*a17);
  a53=(a11*a55);
  a05=(a05-a53);
  a53=(a01*a05);
  a02=arg[3]? arg[3][13] : 0;
  a03=(a02*a17);
  a06=(a12*a18);
  a03=(a03-a06);
  a03=(a11*a03);
  a02=(a02*a55);
  a06=(a10*a18);
  a02=(a02-a06);
  a02=(a13*a02);
  a03=(a03+a02);
  a02=(a16*a03);
  a53=(a53+a02);
  a02=(a34*a48);
  a06=(a54*a46);
  a04=(a02-a06);
  a04=(a04*a43);
  a34=(a34*a46);
  a44=(a54*a48);
  a45=(a34+a44);
  a45=(a45*a26);
  a04=(a04+a45);
  a45=1.;
  a46=casadi_sq(a46);
  a46=(a08*a46);
  a47=(a45-a46);
  a51=casadi_sq(a48);
  a51=(a08*a51);
  a47=(a47-a51);
  a47=(a47*a50);
  a04=(a04+a47);
  a11=(a11*a04);
  a52=(a52*a48);
  a54=(a54*a09);
  a48=(a52+a54);
  a48=(a48*a43);
  a09=casadi_sq(a09);
  a08=(a08*a09);
  a45=(a45-a08);
  a51=(a45-a51);
  a51=(a51*a26);
  a48=(a48+a51);
  a34=(a34-a44);
  a34=(a34*a50);
  a48=(a48+a34);
  a13=(a13*a48);
  a11=(a11-a13);
  a13=(a16*a11);
  a53=(a53+a13);
  a53=(a14*a53);
  a13=arg[1]? arg[1][13] : 0;
  a34=arg[3]? arg[3][27] : 0;
  a13=(a13/a34);
  a12=(a12*a55);
  a10=(a10*a17);
  a12=(a12-a10);
  a10=(a16*a12);
  a01=(a01*a18);
  a10=(a10-a01);
  a45=(a45-a46);
  a45=(a45*a43);
  a52=(a52-a54);
  a52=(a52*a26);
  a45=(a45+a52);
  a02=(a02+a06);
  a02=(a02*a50);
  a45=(a45+a02);
  a16=(a16*a45);
  a10=(a10+a16);
  a10=(a15*a10);
  a10=(a13+a10);
  a53=(a53-a10);
  if (res[0]!=0) res[0][13]=a53;
  a53=arg[3]? arg[3][17] : 0;
  a10=(a53*a17);
  a16=(a21*a18);
  a10=(a10-a16);
  a10=(a20*a10);
  a53=(a53*a55);
  a16=(a19*a18);
  a53=(a53-a16);
  a53=(a22*a53);
  a10=(a10+a53);
  a53=(a25*a10);
  a16=arg[3]? arg[3][14] : 0;
  a02=(a16*a25);
  a02=(a02*a07);
  a06=(a22*a17);
  a52=(a20*a55);
  a06=(a06-a52);
  a52=(a02*a06);
  a53=(a53+a52);
  a20=(a20*a04);
  a22=(a22*a48);
  a20=(a20-a22);
  a22=(a25*a20);
  a53=(a53+a22);
  a53=(a23*a53);
  a22=arg[1]? arg[1][14] : 0;
  a22=(a22/a34);
  a21=(a21*a55);
  a19=(a19*a17);
  a21=(a21-a19);
  a19=(a25*a21);
  a02=(a02*a18);
  a19=(a19-a02);
  a25=(a25*a45);
  a19=(a19+a25);
  a19=(a24*a19);
  a19=(a22+a19);
  a53=(a53-a19);
  if (res[0]!=0) res[0][14]=a53;
  a53=arg[3]? arg[3][21] : 0;
  a19=(a53*a17);
  a25=(a29*a18);
  a19=(a19-a25);
  a19=(a28*a19);
  a53=(a53*a55);
  a25=(a27*a18);
  a53=(a53-a25);
  a53=(a30*a53);
  a19=(a19+a53);
  a53=(a33*a19);
  a25=arg[3]? arg[3][18] : 0;
  a02=(a25*a33);
  a02=(a02*a07);
  a52=(a30*a17);
  a54=(a28*a55);
  a52=(a52-a54);
  a54=(a02*a52);
  a53=(a53+a54);
  a28=(a28*a04);
  a30=(a30*a48);
  a28=(a28-a30);
  a30=(a33*a28);
  a53=(a53+a30);
  a53=(a31*a53);
  a30=arg[1]? arg[1][15] : 0;
  a30=(a30/a34);
  a29=(a29*a55);
  a27=(a27*a17);
  a29=(a29-a27);
  a27=(a33*a29);
  a02=(a02*a18);
  a27=(a27-a02);
  a33=(a33*a45);
  a27=(a27+a33);
  a27=(a32*a27);
  a27=(a30+a27);
  a53=(a53-a27);
  if (res[0]!=0) res[0][15]=a53;
  a53=arg[3]? arg[3][25] : 0;
  a27=(a53*a17);
  a33=(a37*a18);
  a27=(a27-a33);
  a27=(a36*a27);
  a53=(a53*a55);
  a33=(a35*a18);
  a53=(a53-a33);
  a53=(a38*a53);
  a27=(a27+a53);
  a53=(a41*a27);
  a33=arg[3]? arg[3][22] : 0;
  a02=(a33*a41);
  a02=(a02*a07);
  a54=(a38*a17);
  a46=(a36*a55);
  a54=(a54-a46);
  a46=(a02*a54);
  a53=(a53+a46);
  a36=(a36*a04);
  a38=(a38*a48);
  a36=(a36-a38);
  a38=(a41*a36);
  a53=(a53+a38);
  a53=(a39*a53);
  a38=arg[1]? arg[1][16] : 0;
  a38=(a38/a34);
  a37=(a37*a55);
  a35=(a35*a17);
  a37=(a37-a35);
  a35=(a41*a37);
  a02=(a02*a18);
  a35=(a35-a02);
  a41=(a41*a45);
  a35=(a35+a41);
  a35=(a40*a35);
  a35=(a38+a35);
  a53=(a53-a35);
  if (res[0]!=0) res[0][16]=a53;
  if (res[0]!=0) res[0][17]=a50;
  if (res[0]!=0) res[0][18]=a26;
  if (res[0]!=0) res[0][19]=a43;
  if (res[0]!=0) res[0][20]=a55;
  if (res[0]!=0) res[0][21]=a17;
  if (res[0]!=0) res[0][22]=a18;
  a05=(a15*a05);
  a17=(a14*a18);
  a05=(a05-a17);
  a05=(a07*a05);
  a49=(a49*a05);
  a03=(a15*a03);
  a49=(a49+a03);
  a12=(a14*a12);
  a49=(a49+a12);
  a14=(a14*a45);
  a49=(a49+a14);
  a15=(a15*a11);
  a49=(a49+a15);
  if (res[0]!=0) res[0][23]=a49;
  a10=(a24*a10);
  a21=(a23*a21);
  a10=(a10+a21);
  a06=(a24*a06);
  a21=(a23*a18);
  a06=(a06-a21);
  a06=(a07*a06);
  a16=(a16*a06);
  a10=(a10+a16);
  a23=(a23*a45);
  a10=(a10+a23);
  a24=(a24*a20);
  a10=(a10+a24);
  if (res[0]!=0) res[0][24]=a10;
  a19=(a32*a19);
  a29=(a31*a29);
  a19=(a19+a29);
  a52=(a32*a52);
  a29=(a31*a18);
  a52=(a52-a29);
  a52=(a07*a52);
  a25=(a25*a52);
  a19=(a19+a25);
  a31=(a31*a45);
  a19=(a19+a31);
  a32=(a32*a28);
  a19=(a19+a32);
  if (res[0]!=0) res[0][25]=a19;
  a27=(a40*a27);
  a37=(a39*a37);
  a27=(a27+a37);
  a54=(a40*a54);
  a18=(a39*a18);
  a54=(a54-a18);
  a07=(a07*a54);
  a33=(a33*a07);
  a27=(a27+a33);
  a39=(a39*a45);
  a27=(a27+a39);
  a40=(a40*a36);
  a27=(a27+a40);
  if (res[0]!=0) res[0][26]=a27;
  if (res[0]!=0) res[0][27]=a13;
  if (res[0]!=0) res[0][28]=a22;
  if (res[0]!=0) res[0][29]=a30;
  if (res[0]!=0) res[0][30]=a38;
  return 0;
}

CASADI_SYMBOL_EXPORT int tilt_qd_servo_dist_imp_mdl_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int tilt_qd_servo_dist_imp_mdl_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int tilt_qd_servo_dist_imp_mdl_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tilt_qd_servo_dist_imp_mdl_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int tilt_qd_servo_dist_imp_mdl_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tilt_qd_servo_dist_imp_mdl_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void tilt_qd_servo_dist_imp_mdl_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void tilt_qd_servo_dist_imp_mdl_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int tilt_qd_servo_dist_imp_mdl_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int tilt_qd_servo_dist_imp_mdl_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real tilt_qd_servo_dist_imp_mdl_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tilt_qd_servo_dist_imp_mdl_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tilt_qd_servo_dist_imp_mdl_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tilt_qd_servo_dist_imp_mdl_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tilt_qd_servo_dist_imp_mdl_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int tilt_qd_servo_dist_imp_mdl_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int tilt_qd_servo_dist_imp_mdl_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
