/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) mhe_wrench_est_acc_mom_mdl_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {9, 1, 1};
static const casadi_int casadi_s1[3] = {9, 9, 1};
static const casadi_int casadi_s2[3] = {9, 6, 1};
static const casadi_int casadi_s3[3] = {6, 1, 1};
static const casadi_int casadi_s4[3] = {3, 1, 1};

/* mhe_wrench_est_acc_mom_mdl_expl_vde_forw:(i0[9],i1[9x9],i2[9x6],i3[6],i4[3])->(o0[9],o1[9x9],o2[9x6]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21;
  a00=1.5924631902133582e+01;
  a01=arg[4]? arg[4][0] : 0;
  a02=arg[0]? arg[0][1] : 0;
  a03=9.4879500000000005e-02;
  a04=arg[0]? arg[0][2] : 0;
  a05=(a03*a04);
  a06=(a02*a05);
  a07=6.2079599999999999e-02;
  a08=(a07*a02);
  a09=(a04*a08);
  a06=(a06-a09);
  a01=(a01-a06);
  a06=arg[0]? arg[0][6] : 0;
  a01=(a01+a06);
  a01=(a00*a01);
  if (res[0]!=0) res[0][0]=a01;
  a01=1.6108351213603182e+01;
  a06=arg[4]? arg[4][1] : 0;
  a09=6.2795799999999999e-02;
  a10=arg[0]? arg[0][0] : 0;
  a11=(a09*a10);
  a12=(a04*a11);
  a13=(a10*a05);
  a12=(a12-a13);
  a06=(a06-a12);
  a12=arg[0]? arg[0][7] : 0;
  a06=(a06+a12);
  a06=(a01*a06);
  if (res[0]!=0) res[0][1]=a06;
  a06=1.0539684547241501e+01;
  a12=arg[4]? arg[4][2] : 0;
  a13=(a10*a08);
  a14=(a02*a11);
  a13=(a13-a14);
  a12=(a12-a13);
  a13=arg[0]? arg[0][8] : 0;
  a12=(a12+a13);
  a12=(a06*a12);
  if (res[0]!=0) res[0][2]=a12;
  a12=arg[3]? arg[3][0] : 0;
  if (res[0]!=0) res[0][3]=a12;
  a12=arg[3]? arg[3][1] : 0;
  if (res[0]!=0) res[0][4]=a12;
  a12=arg[3]? arg[3][2] : 0;
  if (res[0]!=0) res[0][5]=a12;
  a12=arg[3]? arg[3][3] : 0;
  if (res[0]!=0) res[0][6]=a12;
  a12=arg[3]? arg[3][4] : 0;
  if (res[0]!=0) res[0][7]=a12;
  a12=arg[3]? arg[3][5] : 0;
  if (res[0]!=0) res[0][8]=a12;
  a12=arg[1]? arg[1][6] : 0;
  a13=arg[1]? arg[1][1] : 0;
  a14=(a05*a13);
  a15=arg[1]? arg[1][2] : 0;
  a16=(a03*a15);
  a17=(a02*a16);
  a14=(a14+a17);
  a17=(a08*a15);
  a18=(a07*a13);
  a19=(a04*a18);
  a17=(a17+a19);
  a14=(a14-a17);
  a12=(a12-a14);
  a12=(a00*a12);
  if (res[1]!=0) res[1][0]=a12;
  a12=arg[1]? arg[1][7] : 0;
  a15=(a11*a15);
  a14=arg[1]? arg[1][0] : 0;
  a17=(a09*a14);
  a19=(a04*a17);
  a15=(a15+a19);
  a19=(a05*a14);
  a16=(a10*a16);
  a19=(a19+a16);
  a15=(a15-a19);
  a12=(a12-a15);
  a12=(a01*a12);
  if (res[1]!=0) res[1][1]=a12;
  a12=arg[1]? arg[1][8] : 0;
  a14=(a08*a14);
  a18=(a10*a18);
  a14=(a14+a18);
  a13=(a11*a13);
  a17=(a02*a17);
  a13=(a13+a17);
  a14=(a14-a13);
  a12=(a12-a14);
  a12=(a06*a12);
  if (res[1]!=0) res[1][2]=a12;
  a12=0.;
  if (res[1]!=0) res[1][3]=a12;
  if (res[1]!=0) res[1][4]=a12;
  if (res[1]!=0) res[1][5]=a12;
  if (res[1]!=0) res[1][6]=a12;
  if (res[1]!=0) res[1][7]=a12;
  if (res[1]!=0) res[1][8]=a12;
  a14=arg[1]? arg[1][15] : 0;
  a13=arg[1]? arg[1][10] : 0;
  a17=(a05*a13);
  a18=arg[1]? arg[1][11] : 0;
  a15=(a03*a18);
  a19=(a02*a15);
  a17=(a17+a19);
  a19=(a08*a18);
  a16=(a07*a13);
  a20=(a04*a16);
  a19=(a19+a20);
  a17=(a17-a19);
  a14=(a14-a17);
  a14=(a00*a14);
  if (res[1]!=0) res[1][9]=a14;
  a14=arg[1]? arg[1][16] : 0;
  a18=(a11*a18);
  a17=arg[1]? arg[1][9] : 0;
  a19=(a09*a17);
  a20=(a04*a19);
  a18=(a18+a20);
  a20=(a05*a17);
  a15=(a10*a15);
  a20=(a20+a15);
  a18=(a18-a20);
  a14=(a14-a18);
  a14=(a01*a14);
  if (res[1]!=0) res[1][10]=a14;
  a14=arg[1]? arg[1][17] : 0;
  a17=(a08*a17);
  a16=(a10*a16);
  a17=(a17+a16);
  a13=(a11*a13);
  a19=(a02*a19);
  a13=(a13+a19);
  a17=(a17-a13);
  a14=(a14-a17);
  a14=(a06*a14);
  if (res[1]!=0) res[1][11]=a14;
  if (res[1]!=0) res[1][12]=a12;
  if (res[1]!=0) res[1][13]=a12;
  if (res[1]!=0) res[1][14]=a12;
  if (res[1]!=0) res[1][15]=a12;
  if (res[1]!=0) res[1][16]=a12;
  if (res[1]!=0) res[1][17]=a12;
  a14=arg[1]? arg[1][24] : 0;
  a17=arg[1]? arg[1][19] : 0;
  a13=(a05*a17);
  a19=arg[1]? arg[1][20] : 0;
  a16=(a03*a19);
  a18=(a02*a16);
  a13=(a13+a18);
  a18=(a08*a19);
  a20=(a07*a17);
  a15=(a04*a20);
  a18=(a18+a15);
  a13=(a13-a18);
  a14=(a14-a13);
  a14=(a00*a14);
  if (res[1]!=0) res[1][18]=a14;
  a14=arg[1]? arg[1][25] : 0;
  a19=(a11*a19);
  a13=arg[1]? arg[1][18] : 0;
  a18=(a09*a13);
  a15=(a04*a18);
  a19=(a19+a15);
  a15=(a05*a13);
  a16=(a10*a16);
  a15=(a15+a16);
  a19=(a19-a15);
  a14=(a14-a19);
  a14=(a01*a14);
  if (res[1]!=0) res[1][19]=a14;
  a14=arg[1]? arg[1][26] : 0;
  a13=(a08*a13);
  a20=(a10*a20);
  a13=(a13+a20);
  a17=(a11*a17);
  a18=(a02*a18);
  a17=(a17+a18);
  a13=(a13-a17);
  a14=(a14-a13);
  a14=(a06*a14);
  if (res[1]!=0) res[1][20]=a14;
  if (res[1]!=0) res[1][21]=a12;
  if (res[1]!=0) res[1][22]=a12;
  if (res[1]!=0) res[1][23]=a12;
  if (res[1]!=0) res[1][24]=a12;
  if (res[1]!=0) res[1][25]=a12;
  if (res[1]!=0) res[1][26]=a12;
  a14=arg[1]? arg[1][33] : 0;
  a13=arg[1]? arg[1][28] : 0;
  a17=(a05*a13);
  a18=arg[1]? arg[1][29] : 0;
  a20=(a03*a18);
  a19=(a02*a20);
  a17=(a17+a19);
  a19=(a08*a18);
  a15=(a07*a13);
  a16=(a04*a15);
  a19=(a19+a16);
  a17=(a17-a19);
  a14=(a14-a17);
  a14=(a00*a14);
  if (res[1]!=0) res[1][27]=a14;
  a14=arg[1]? arg[1][34] : 0;
  a18=(a11*a18);
  a17=arg[1]? arg[1][27] : 0;
  a19=(a09*a17);
  a16=(a04*a19);
  a18=(a18+a16);
  a16=(a05*a17);
  a20=(a10*a20);
  a16=(a16+a20);
  a18=(a18-a16);
  a14=(a14-a18);
  a14=(a01*a14);
  if (res[1]!=0) res[1][28]=a14;
  a14=arg[1]? arg[1][35] : 0;
  a17=(a08*a17);
  a15=(a10*a15);
  a17=(a17+a15);
  a13=(a11*a13);
  a19=(a02*a19);
  a13=(a13+a19);
  a17=(a17-a13);
  a14=(a14-a17);
  a14=(a06*a14);
  if (res[1]!=0) res[1][29]=a14;
  if (res[1]!=0) res[1][30]=a12;
  if (res[1]!=0) res[1][31]=a12;
  if (res[1]!=0) res[1][32]=a12;
  if (res[1]!=0) res[1][33]=a12;
  if (res[1]!=0) res[1][34]=a12;
  if (res[1]!=0) res[1][35]=a12;
  a14=arg[1]? arg[1][42] : 0;
  a17=arg[1]? arg[1][37] : 0;
  a13=(a05*a17);
  a19=arg[1]? arg[1][38] : 0;
  a15=(a03*a19);
  a18=(a02*a15);
  a13=(a13+a18);
  a18=(a08*a19);
  a16=(a07*a17);
  a20=(a04*a16);
  a18=(a18+a20);
  a13=(a13-a18);
  a14=(a14-a13);
  a14=(a00*a14);
  if (res[1]!=0) res[1][36]=a14;
  a14=arg[1]? arg[1][43] : 0;
  a19=(a11*a19);
  a13=arg[1]? arg[1][36] : 0;
  a18=(a09*a13);
  a20=(a04*a18);
  a19=(a19+a20);
  a20=(a05*a13);
  a15=(a10*a15);
  a20=(a20+a15);
  a19=(a19-a20);
  a14=(a14-a19);
  a14=(a01*a14);
  if (res[1]!=0) res[1][37]=a14;
  a14=arg[1]? arg[1][44] : 0;
  a13=(a08*a13);
  a16=(a10*a16);
  a13=(a13+a16);
  a17=(a11*a17);
  a18=(a02*a18);
  a17=(a17+a18);
  a13=(a13-a17);
  a14=(a14-a13);
  a14=(a06*a14);
  if (res[1]!=0) res[1][38]=a14;
  if (res[1]!=0) res[1][39]=a12;
  if (res[1]!=0) res[1][40]=a12;
  if (res[1]!=0) res[1][41]=a12;
  if (res[1]!=0) res[1][42]=a12;
  if (res[1]!=0) res[1][43]=a12;
  if (res[1]!=0) res[1][44]=a12;
  a14=arg[1]? arg[1][51] : 0;
  a13=arg[1]? arg[1][46] : 0;
  a17=(a05*a13);
  a18=arg[1]? arg[1][47] : 0;
  a16=(a03*a18);
  a19=(a02*a16);
  a17=(a17+a19);
  a19=(a08*a18);
  a20=(a07*a13);
  a15=(a04*a20);
  a19=(a19+a15);
  a17=(a17-a19);
  a14=(a14-a17);
  a14=(a00*a14);
  if (res[1]!=0) res[1][45]=a14;
  a14=arg[1]? arg[1][52] : 0;
  a18=(a11*a18);
  a17=arg[1]? arg[1][45] : 0;
  a19=(a09*a17);
  a15=(a04*a19);
  a18=(a18+a15);
  a15=(a05*a17);
  a16=(a10*a16);
  a15=(a15+a16);
  a18=(a18-a15);
  a14=(a14-a18);
  a14=(a01*a14);
  if (res[1]!=0) res[1][46]=a14;
  a14=arg[1]? arg[1][53] : 0;
  a17=(a08*a17);
  a20=(a10*a20);
  a17=(a17+a20);
  a13=(a11*a13);
  a19=(a02*a19);
  a13=(a13+a19);
  a17=(a17-a13);
  a14=(a14-a17);
  a14=(a06*a14);
  if (res[1]!=0) res[1][47]=a14;
  if (res[1]!=0) res[1][48]=a12;
  if (res[1]!=0) res[1][49]=a12;
  if (res[1]!=0) res[1][50]=a12;
  if (res[1]!=0) res[1][51]=a12;
  if (res[1]!=0) res[1][52]=a12;
  if (res[1]!=0) res[1][53]=a12;
  a14=arg[1]? arg[1][60] : 0;
  a17=arg[1]? arg[1][55] : 0;
  a13=(a05*a17);
  a19=arg[1]? arg[1][56] : 0;
  a20=(a03*a19);
  a18=(a02*a20);
  a13=(a13+a18);
  a18=(a08*a19);
  a15=(a07*a17);
  a16=(a04*a15);
  a18=(a18+a16);
  a13=(a13-a18);
  a14=(a14-a13);
  a14=(a00*a14);
  if (res[1]!=0) res[1][54]=a14;
  a14=arg[1]? arg[1][61] : 0;
  a19=(a11*a19);
  a13=arg[1]? arg[1][54] : 0;
  a18=(a09*a13);
  a16=(a04*a18);
  a19=(a19+a16);
  a16=(a05*a13);
  a20=(a10*a20);
  a16=(a16+a20);
  a19=(a19-a16);
  a14=(a14-a19);
  a14=(a01*a14);
  if (res[1]!=0) res[1][55]=a14;
  a14=arg[1]? arg[1][62] : 0;
  a13=(a08*a13);
  a15=(a10*a15);
  a13=(a13+a15);
  a17=(a11*a17);
  a18=(a02*a18);
  a17=(a17+a18);
  a13=(a13-a17);
  a14=(a14-a13);
  a14=(a06*a14);
  if (res[1]!=0) res[1][56]=a14;
  if (res[1]!=0) res[1][57]=a12;
  if (res[1]!=0) res[1][58]=a12;
  if (res[1]!=0) res[1][59]=a12;
  if (res[1]!=0) res[1][60]=a12;
  if (res[1]!=0) res[1][61]=a12;
  if (res[1]!=0) res[1][62]=a12;
  a14=arg[1]? arg[1][69] : 0;
  a13=arg[1]? arg[1][64] : 0;
  a17=(a05*a13);
  a18=arg[1]? arg[1][65] : 0;
  a15=(a03*a18);
  a19=(a02*a15);
  a17=(a17+a19);
  a19=(a08*a18);
  a16=(a07*a13);
  a20=(a04*a16);
  a19=(a19+a20);
  a17=(a17-a19);
  a14=(a14-a17);
  a14=(a00*a14);
  if (res[1]!=0) res[1][63]=a14;
  a14=arg[1]? arg[1][70] : 0;
  a18=(a11*a18);
  a17=arg[1]? arg[1][63] : 0;
  a19=(a09*a17);
  a20=(a04*a19);
  a18=(a18+a20);
  a20=(a05*a17);
  a15=(a10*a15);
  a20=(a20+a15);
  a18=(a18-a20);
  a14=(a14-a18);
  a14=(a01*a14);
  if (res[1]!=0) res[1][64]=a14;
  a14=arg[1]? arg[1][71] : 0;
  a17=(a08*a17);
  a16=(a10*a16);
  a17=(a17+a16);
  a13=(a11*a13);
  a19=(a02*a19);
  a13=(a13+a19);
  a17=(a17-a13);
  a14=(a14-a17);
  a14=(a06*a14);
  if (res[1]!=0) res[1][65]=a14;
  if (res[1]!=0) res[1][66]=a12;
  if (res[1]!=0) res[1][67]=a12;
  if (res[1]!=0) res[1][68]=a12;
  if (res[1]!=0) res[1][69]=a12;
  if (res[1]!=0) res[1][70]=a12;
  if (res[1]!=0) res[1][71]=a12;
  a14=arg[1]? arg[1][78] : 0;
  a17=arg[1]? arg[1][73] : 0;
  a13=(a05*a17);
  a19=arg[1]? arg[1][74] : 0;
  a16=(a03*a19);
  a18=(a02*a16);
  a13=(a13+a18);
  a18=(a08*a19);
  a20=(a07*a17);
  a15=(a04*a20);
  a18=(a18+a15);
  a13=(a13-a18);
  a14=(a14-a13);
  a14=(a00*a14);
  if (res[1]!=0) res[1][72]=a14;
  a14=arg[1]? arg[1][79] : 0;
  a19=(a11*a19);
  a13=arg[1]? arg[1][72] : 0;
  a18=(a09*a13);
  a15=(a04*a18);
  a19=(a19+a15);
  a15=(a05*a13);
  a16=(a10*a16);
  a15=(a15+a16);
  a19=(a19-a15);
  a14=(a14-a19);
  a14=(a01*a14);
  if (res[1]!=0) res[1][73]=a14;
  a14=arg[1]? arg[1][80] : 0;
  a13=(a08*a13);
  a20=(a10*a20);
  a13=(a13+a20);
  a17=(a11*a17);
  a18=(a02*a18);
  a17=(a17+a18);
  a13=(a13-a17);
  a14=(a14-a13);
  a14=(a06*a14);
  if (res[1]!=0) res[1][74]=a14;
  if (res[1]!=0) res[1][75]=a12;
  if (res[1]!=0) res[1][76]=a12;
  if (res[1]!=0) res[1][77]=a12;
  if (res[1]!=0) res[1][78]=a12;
  if (res[1]!=0) res[1][79]=a12;
  if (res[1]!=0) res[1][80]=a12;
  a14=arg[2]? arg[2][6] : 0;
  a13=arg[2]? arg[2][1] : 0;
  a17=(a05*a13);
  a18=arg[2]? arg[2][2] : 0;
  a20=(a03*a18);
  a19=(a02*a20);
  a17=(a17+a19);
  a19=(a08*a18);
  a15=(a07*a13);
  a16=(a04*a15);
  a19=(a19+a16);
  a17=(a17-a19);
  a14=(a14-a17);
  a14=(a00*a14);
  if (res[2]!=0) res[2][0]=a14;
  a14=arg[2]? arg[2][7] : 0;
  a18=(a11*a18);
  a17=arg[2]? arg[2][0] : 0;
  a19=(a09*a17);
  a16=(a04*a19);
  a18=(a18+a16);
  a16=(a05*a17);
  a20=(a10*a20);
  a16=(a16+a20);
  a18=(a18-a16);
  a14=(a14-a18);
  a14=(a01*a14);
  if (res[2]!=0) res[2][1]=a14;
  a14=arg[2]? arg[2][8] : 0;
  a17=(a08*a17);
  a15=(a10*a15);
  a17=(a17+a15);
  a13=(a11*a13);
  a19=(a02*a19);
  a13=(a13+a19);
  a17=(a17-a13);
  a14=(a14-a17);
  a14=(a06*a14);
  if (res[2]!=0) res[2][2]=a14;
  a14=1.;
  if (res[2]!=0) res[2][3]=a14;
  if (res[2]!=0) res[2][4]=a12;
  if (res[2]!=0) res[2][5]=a12;
  if (res[2]!=0) res[2][6]=a12;
  if (res[2]!=0) res[2][7]=a12;
  if (res[2]!=0) res[2][8]=a12;
  a17=arg[2]? arg[2][15] : 0;
  a13=arg[2]? arg[2][10] : 0;
  a19=(a05*a13);
  a15=arg[2]? arg[2][11] : 0;
  a18=(a03*a15);
  a16=(a02*a18);
  a19=(a19+a16);
  a16=(a08*a15);
  a20=(a07*a13);
  a21=(a04*a20);
  a16=(a16+a21);
  a19=(a19-a16);
  a17=(a17-a19);
  a17=(a00*a17);
  if (res[2]!=0) res[2][9]=a17;
  a17=arg[2]? arg[2][16] : 0;
  a15=(a11*a15);
  a19=arg[2]? arg[2][9] : 0;
  a16=(a09*a19);
  a21=(a04*a16);
  a15=(a15+a21);
  a21=(a05*a19);
  a18=(a10*a18);
  a21=(a21+a18);
  a15=(a15-a21);
  a17=(a17-a15);
  a17=(a01*a17);
  if (res[2]!=0) res[2][10]=a17;
  a17=arg[2]? arg[2][17] : 0;
  a19=(a08*a19);
  a20=(a10*a20);
  a19=(a19+a20);
  a13=(a11*a13);
  a16=(a02*a16);
  a13=(a13+a16);
  a19=(a19-a13);
  a17=(a17-a19);
  a17=(a06*a17);
  if (res[2]!=0) res[2][11]=a17;
  if (res[2]!=0) res[2][12]=a12;
  if (res[2]!=0) res[2][13]=a14;
  if (res[2]!=0) res[2][14]=a12;
  if (res[2]!=0) res[2][15]=a12;
  if (res[2]!=0) res[2][16]=a12;
  if (res[2]!=0) res[2][17]=a12;
  a17=arg[2]? arg[2][24] : 0;
  a19=arg[2]? arg[2][19] : 0;
  a13=(a05*a19);
  a16=arg[2]? arg[2][20] : 0;
  a20=(a03*a16);
  a15=(a02*a20);
  a13=(a13+a15);
  a15=(a08*a16);
  a21=(a07*a19);
  a18=(a04*a21);
  a15=(a15+a18);
  a13=(a13-a15);
  a17=(a17-a13);
  a17=(a00*a17);
  if (res[2]!=0) res[2][18]=a17;
  a17=arg[2]? arg[2][25] : 0;
  a16=(a11*a16);
  a13=arg[2]? arg[2][18] : 0;
  a15=(a09*a13);
  a18=(a04*a15);
  a16=(a16+a18);
  a18=(a05*a13);
  a20=(a10*a20);
  a18=(a18+a20);
  a16=(a16-a18);
  a17=(a17-a16);
  a17=(a01*a17);
  if (res[2]!=0) res[2][19]=a17;
  a17=arg[2]? arg[2][26] : 0;
  a13=(a08*a13);
  a21=(a10*a21);
  a13=(a13+a21);
  a19=(a11*a19);
  a15=(a02*a15);
  a19=(a19+a15);
  a13=(a13-a19);
  a17=(a17-a13);
  a17=(a06*a17);
  if (res[2]!=0) res[2][20]=a17;
  if (res[2]!=0) res[2][21]=a12;
  if (res[2]!=0) res[2][22]=a12;
  if (res[2]!=0) res[2][23]=a14;
  if (res[2]!=0) res[2][24]=a12;
  if (res[2]!=0) res[2][25]=a12;
  if (res[2]!=0) res[2][26]=a12;
  a17=arg[2]? arg[2][33] : 0;
  a13=arg[2]? arg[2][28] : 0;
  a19=(a05*a13);
  a15=arg[2]? arg[2][29] : 0;
  a21=(a03*a15);
  a16=(a02*a21);
  a19=(a19+a16);
  a16=(a08*a15);
  a18=(a07*a13);
  a20=(a04*a18);
  a16=(a16+a20);
  a19=(a19-a16);
  a17=(a17-a19);
  a17=(a00*a17);
  if (res[2]!=0) res[2][27]=a17;
  a17=arg[2]? arg[2][34] : 0;
  a15=(a11*a15);
  a19=arg[2]? arg[2][27] : 0;
  a16=(a09*a19);
  a20=(a04*a16);
  a15=(a15+a20);
  a20=(a05*a19);
  a21=(a10*a21);
  a20=(a20+a21);
  a15=(a15-a20);
  a17=(a17-a15);
  a17=(a01*a17);
  if (res[2]!=0) res[2][28]=a17;
  a17=arg[2]? arg[2][35] : 0;
  a19=(a08*a19);
  a18=(a10*a18);
  a19=(a19+a18);
  a13=(a11*a13);
  a16=(a02*a16);
  a13=(a13+a16);
  a19=(a19-a13);
  a17=(a17-a19);
  a17=(a06*a17);
  if (res[2]!=0) res[2][29]=a17;
  if (res[2]!=0) res[2][30]=a12;
  if (res[2]!=0) res[2][31]=a12;
  if (res[2]!=0) res[2][32]=a12;
  if (res[2]!=0) res[2][33]=a14;
  if (res[2]!=0) res[2][34]=a12;
  if (res[2]!=0) res[2][35]=a12;
  a17=arg[2]? arg[2][42] : 0;
  a19=arg[2]? arg[2][37] : 0;
  a13=(a05*a19);
  a16=arg[2]? arg[2][38] : 0;
  a18=(a03*a16);
  a15=(a02*a18);
  a13=(a13+a15);
  a15=(a08*a16);
  a20=(a07*a19);
  a21=(a04*a20);
  a15=(a15+a21);
  a13=(a13-a15);
  a17=(a17-a13);
  a17=(a00*a17);
  if (res[2]!=0) res[2][36]=a17;
  a17=arg[2]? arg[2][43] : 0;
  a16=(a11*a16);
  a13=arg[2]? arg[2][36] : 0;
  a15=(a09*a13);
  a21=(a04*a15);
  a16=(a16+a21);
  a21=(a05*a13);
  a18=(a10*a18);
  a21=(a21+a18);
  a16=(a16-a21);
  a17=(a17-a16);
  a17=(a01*a17);
  if (res[2]!=0) res[2][37]=a17;
  a17=arg[2]? arg[2][44] : 0;
  a13=(a08*a13);
  a20=(a10*a20);
  a13=(a13+a20);
  a19=(a11*a19);
  a15=(a02*a15);
  a19=(a19+a15);
  a13=(a13-a19);
  a17=(a17-a13);
  a17=(a06*a17);
  if (res[2]!=0) res[2][38]=a17;
  if (res[2]!=0) res[2][39]=a12;
  if (res[2]!=0) res[2][40]=a12;
  if (res[2]!=0) res[2][41]=a12;
  if (res[2]!=0) res[2][42]=a12;
  if (res[2]!=0) res[2][43]=a14;
  if (res[2]!=0) res[2][44]=a12;
  a17=arg[2]? arg[2][51] : 0;
  a13=arg[2]? arg[2][46] : 0;
  a19=(a05*a13);
  a15=arg[2]? arg[2][47] : 0;
  a03=(a03*a15);
  a20=(a02*a03);
  a19=(a19+a20);
  a20=(a08*a15);
  a07=(a07*a13);
  a16=(a04*a07);
  a20=(a20+a16);
  a19=(a19-a20);
  a17=(a17-a19);
  a00=(a00*a17);
  if (res[2]!=0) res[2][45]=a00;
  a00=arg[2]? arg[2][52] : 0;
  a15=(a11*a15);
  a17=arg[2]? arg[2][45] : 0;
  a09=(a09*a17);
  a04=(a04*a09);
  a15=(a15+a04);
  a05=(a05*a17);
  a03=(a10*a03);
  a05=(a05+a03);
  a15=(a15-a05);
  a00=(a00-a15);
  a01=(a01*a00);
  if (res[2]!=0) res[2][46]=a01;
  a01=arg[2]? arg[2][53] : 0;
  a08=(a08*a17);
  a10=(a10*a07);
  a08=(a08+a10);
  a11=(a11*a13);
  a02=(a02*a09);
  a11=(a11+a02);
  a08=(a08-a11);
  a01=(a01-a08);
  a06=(a06*a01);
  if (res[2]!=0) res[2][47]=a06;
  if (res[2]!=0) res[2][48]=a12;
  if (res[2]!=0) res[2][49]=a12;
  if (res[2]!=0) res[2][50]=a12;
  if (res[2]!=0) res[2][51]=a12;
  if (res[2]!=0) res[2][52]=a12;
  if (res[2]!=0) res[2][53]=a14;
  return 0;
}

CASADI_SYMBOL_EXPORT int mhe_wrench_est_acc_mom_mdl_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int mhe_wrench_est_acc_mom_mdl_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int mhe_wrench_est_acc_mom_mdl_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mhe_wrench_est_acc_mom_mdl_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int mhe_wrench_est_acc_mom_mdl_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mhe_wrench_est_acc_mom_mdl_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void mhe_wrench_est_acc_mom_mdl_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void mhe_wrench_est_acc_mom_mdl_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int mhe_wrench_est_acc_mom_mdl_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int mhe_wrench_est_acc_mom_mdl_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real mhe_wrench_est_acc_mom_mdl_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mhe_wrench_est_acc_mom_mdl_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mhe_wrench_est_acc_mom_mdl_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mhe_wrench_est_acc_mom_mdl_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mhe_wrench_est_acc_mom_mdl_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int mhe_wrench_est_acc_mom_mdl_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int mhe_wrench_est_acc_mom_mdl_expl_vde_forw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
