/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) tilt_qd_servo_thrust_dist_mdl_cost_y_fun_jac_ut_xt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {27, 1, 1};
static const casadi_int casadi_s1[3] = {8, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {0, 0, 1};
static const casadi_int casadi_s4[3] = {41, 1, 1};
static const casadi_int casadi_s5[3] = {35, 1, 1};
static const casadi_int casadi_s6[128] = 
  {35, 35, 0, 5, 10, 15, 23, 31,
  39, 39, 43, 47, 51, 54, 57, 60,
  61, 62, 63, 64, 65, 66, 67, 68,
  69, 70, 71, 72, 73, 74, 76, 78,
  80, 82, 84, 86, 88, 90, 8, 14,
  15, 16, 17, 9, 14, 15, 16, 17,
  10, 14, 15, 16, 17, 11, 14, 15,
  16, 17, 18, 19, 20, 12, 14, 15,
  16, 17, 18, 19, 20, 13, 14, 15,
  16, 17, 18, 19, 20, 14, 15, 16,
  17, 14, 15, 16, 17, 14, 15, 16,
  17, 18, 19, 20, 18, 19, 20, 18,
  19, 20, 21, 22, 23, 24, 25, 26,
  27, 28, 29, 30, 31, 32, 33, 34,
  0, 25, 1, 26, 2, 27, 3, 28,
  4, 21, 5, 22, 6, 23, 7, 24};
static const casadi_int casadi_s7[3] = {35, 0, 1};

/* tilt_qd_servo_thrust_dist_mdl_cost_y_fun_jac_ut_xt:(i0[27],i1[8],i2[0],i3[],i4[41])->(o0[35],o1[35x35,90nz],o2[35x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  casadi_real a48, a49, a50, a51;
  a00=arg[0]? arg[0][0] : 0;
  a01=1.;
  a02=2.;
  a03=arg[0]? arg[0][8] : 0;
  a04=casadi_sq(a03);
  a04=(a02*a04);
  a05=(a01-a04);
  a06=arg[0]? arg[0][9] : 0;
  a07=casadi_sq(a06);
  a07=(a02*a07);
  a05=(a05-a07);
  a08=arg[4]? arg[4][28] : 0;
  a09=(a05*a08);
  a10=arg[0]? arg[0][7] : 0;
  a11=(a02*a10);
  a12=(a11*a03);
  a13=arg[0]? arg[0][6] : 0;
  a14=(a02*a13);
  a15=(a14*a06);
  a16=(a12-a15);
  a17=arg[4]? arg[4][29] : 0;
  a18=(a16*a17);
  a09=(a09+a18);
  a18=(a11*a06);
  a19=(a14*a03);
  a20=(a18+a19);
  a21=arg[4]? arg[4][30] : 0;
  a22=(a20*a21);
  a09=(a09+a22);
  a00=(a00+a09);
  if (res[0]!=0) res[0][0]=a00;
  a00=arg[0]? arg[0][1] : 0;
  a12=(a12+a15);
  a15=(a12*a08);
  a09=casadi_sq(a10);
  a09=(a02*a09);
  a09=(a01-a09);
  a07=(a09-a07);
  a22=(a07*a17);
  a15=(a15+a22);
  a22=(a02*a03);
  a23=(a22*a06);
  a24=(a14*a10);
  a25=(a23-a24);
  a26=(a25*a21);
  a15=(a15+a26);
  a00=(a00+a15);
  if (res[0]!=0) res[0][1]=a00;
  a00=arg[0]? arg[0][2] : 0;
  a18=(a18-a19);
  a19=(a18*a08);
  a23=(a23+a24);
  a24=(a23*a17);
  a19=(a19+a24);
  a09=(a09-a04);
  a04=(a09*a21);
  a19=(a19+a04);
  a00=(a00+a19);
  if (res[0]!=0) res[0][2]=a00;
  a00=arg[0]? arg[0][3] : 0;
  a19=arg[0]? arg[0][12] : 0;
  a04=(a16*a19);
  a24=arg[0]? arg[0][11] : 0;
  a15=(a20*a24);
  a04=(a04-a15);
  a04=(a04*a08);
  a15=arg[0]? arg[0][10] : 0;
  a26=(a20*a15);
  a27=(a05*a19);
  a26=(a26-a27);
  a26=(a26*a17);
  a04=(a04+a26);
  a26=(a05*a24);
  a27=(a16*a15);
  a26=(a26-a27);
  a26=(a26*a21);
  a04=(a04+a26);
  a00=(a00+a04);
  if (res[0]!=0) res[0][3]=a00;
  a00=arg[0]? arg[0][4] : 0;
  a04=(a07*a19);
  a26=(a25*a24);
  a04=(a04-a26);
  a04=(a04*a08);
  a26=(a25*a15);
  a27=(a12*a19);
  a26=(a26-a27);
  a26=(a26*a17);
  a04=(a04+a26);
  a26=(a12*a24);
  a27=(a07*a15);
  a26=(a26-a27);
  a26=(a26*a21);
  a04=(a04+a26);
  a00=(a00+a04);
  if (res[0]!=0) res[0][4]=a00;
  a00=arg[0]? arg[0][5] : 0;
  a04=(a23*a19);
  a26=(a09*a24);
  a04=(a04-a26);
  a04=(a04*a08);
  a26=(a09*a15);
  a27=(a18*a19);
  a26=(a26-a27);
  a26=(a26*a17);
  a04=(a04+a26);
  a26=(a18*a24);
  a27=(a23*a15);
  a26=(a26-a27);
  a26=(a26*a21);
  a04=(a04+a26);
  a00=(a00+a04);
  if (res[0]!=0) res[0][5]=a00;
  a00=arg[4]? arg[4][0] : 0;
  if (res[0]!=0) res[0][6]=a00;
  a04=arg[4]? arg[4][32] : 0;
  a26=(a13*a04);
  a27=arg[4]? arg[4][31] : 0;
  a28=(a10*a27);
  a26=(a26+a28);
  a28=arg[4]? arg[4][34] : 0;
  a29=(a03*a28);
  a26=(a26+a29);
  a29=arg[4]? arg[4][33] : 0;
  a30=(a06*a29);
  a26=(a26-a30);
  a30=(a00*a26);
  a31=arg[4]? arg[4][1] : 0;
  a32=(a13*a27);
  a33=(a10*a04);
  a32=(a32-a33);
  a33=(a03*a29);
  a32=(a32-a33);
  a33=(a06*a28);
  a32=(a32-a33);
  a33=(a31*a32);
  a30=(a30-a33);
  a33=arg[4]? arg[4][2] : 0;
  a34=(a13*a28);
  a35=(a10*a29);
  a34=(a34+a35);
  a35=(a03*a04);
  a34=(a34-a35);
  a35=(a06*a27);
  a34=(a34+a35);
  a35=(a33*a34);
  a30=(a30-a35);
  a35=arg[4]? arg[4][3] : 0;
  a13=(a13*a29);
  a36=(a10*a28);
  a13=(a13-a36);
  a36=(a03*a27);
  a13=(a13+a36);
  a36=(a06*a04);
  a13=(a13+a36);
  a36=(a35*a13);
  a30=(a30+a36);
  a30=(a30+a31);
  if (res[0]!=0) res[0][7]=a30;
  a30=(a00*a13);
  a36=(a31*a34);
  a30=(a30+a36);
  a36=(a33*a32);
  a30=(a30-a36);
  a36=(a35*a26);
  a30=(a30-a36);
  a30=(a30+a33);
  if (res[0]!=0) res[0][8]=a30;
  a34=(a00*a34);
  a13=(a31*a13);
  a34=(a34-a13);
  a26=(a33*a26);
  a34=(a34+a26);
  a32=(a35*a32);
  a34=(a34-a32);
  a34=(a34+a35);
  if (res[0]!=0) res[0][9]=a34;
  a34=casadi_sq(a29);
  a34=(a02*a34);
  a32=(a01-a34);
  a26=casadi_sq(a28);
  a26=(a02*a26);
  a32=(a32-a26);
  a13=(a32*a15);
  a30=(a02*a04);
  a36=(a30*a29);
  a37=(a02*a27);
  a38=(a37*a28);
  a39=(a36+a38);
  a40=(a39*a24);
  a13=(a13+a40);
  a30=(a30*a28);
  a40=(a37*a29);
  a41=(a30-a40);
  a42=(a41*a19);
  a13=(a13+a42);
  if (res[0]!=0) res[0][10]=a13;
  a36=(a36-a38);
  a38=(a36*a15);
  a13=casadi_sq(a04);
  a13=(a02*a13);
  a13=(a01-a13);
  a26=(a13-a26);
  a42=(a26*a24);
  a38=(a38+a42);
  a42=(a02*a29);
  a42=(a42*a28);
  a37=(a37*a04);
  a43=(a42+a37);
  a44=(a43*a19);
  a38=(a38+a44);
  if (res[0]!=0) res[0][11]=a38;
  a30=(a30+a40);
  a40=(a30*a15);
  a42=(a42-a37);
  a37=(a42*a24);
  a40=(a40+a37);
  a13=(a13-a34);
  a34=(a13*a19);
  a40=(a40+a34);
  if (res[0]!=0) res[0][12]=a40;
  a40=arg[0]? arg[0][13] : 0;
  if (res[0]!=0) res[0][13]=a40;
  a34=arg[0]? arg[0][14] : 0;
  if (res[0]!=0) res[0][14]=a34;
  a37=arg[0]? arg[0][15] : 0;
  if (res[0]!=0) res[0][15]=a37;
  a38=arg[0]? arg[0][16] : 0;
  if (res[0]!=0) res[0][16]=a38;
  a44=arg[0]? arg[0][17] : 0;
  if (res[0]!=0) res[0][17]=a44;
  a45=arg[0]? arg[0][18] : 0;
  if (res[0]!=0) res[0][18]=a45;
  a46=arg[0]? arg[0][19] : 0;
  if (res[0]!=0) res[0][19]=a46;
  a47=arg[0]? arg[0][20] : 0;
  if (res[0]!=0) res[0][20]=a47;
  a48=arg[0]? arg[0][21] : 0;
  if (res[0]!=0) res[0][21]=a48;
  a48=arg[0]? arg[0][22] : 0;
  if (res[0]!=0) res[0][22]=a48;
  a48=arg[0]? arg[0][23] : 0;
  if (res[0]!=0) res[0][23]=a48;
  a48=arg[0]? arg[0][24] : 0;
  if (res[0]!=0) res[0][24]=a48;
  a48=arg[0]? arg[0][25] : 0;
  if (res[0]!=0) res[0][25]=a48;
  a48=arg[0]? arg[0][26] : 0;
  if (res[0]!=0) res[0][26]=a48;
  a48=arg[1]? arg[1][0] : 0;
  a48=(a48-a44);
  if (res[0]!=0) res[0][27]=a48;
  a48=arg[1]? arg[1][1] : 0;
  a48=(a48-a45);
  if (res[0]!=0) res[0][28]=a48;
  a48=arg[1]? arg[1][2] : 0;
  a48=(a48-a46);
  if (res[0]!=0) res[0][29]=a48;
  a48=arg[1]? arg[1][3] : 0;
  a48=(a48-a47);
  if (res[0]!=0) res[0][30]=a48;
  a48=arg[1]? arg[1][4] : 0;
  a48=(a48-a40);
  if (res[0]!=0) res[0][31]=a48;
  a48=arg[1]? arg[1][5] : 0;
  a48=(a48-a34);
  if (res[0]!=0) res[0][32]=a48;
  a48=arg[1]? arg[1][6] : 0;
  a48=(a48-a37);
  if (res[0]!=0) res[0][33]=a48;
  a48=arg[1]? arg[1][7] : 0;
  a48=(a48-a38);
  if (res[0]!=0) res[0][34]=a48;
  if (res[1]!=0) res[1][0]=a01;
  a48=(a21*a22);
  a38=(a02*a06);
  a37=(a17*a38);
  a34=(a48-a37);
  if (res[1]!=0) res[1][1]=a34;
  a34=(a17*a22);
  a40=(a21*a38);
  a47=(a34+a40);
  if (res[1]!=0) res[1][2]=a47;
  a47=(a17*a11);
  a03=(a03+a03);
  a03=(a02*a03);
  a46=(a08*a03);
  a46=(a47-a46);
  a45=(a21*a14);
  a46=(a46+a45);
  if (res[1]!=0) res[1][3]=a46;
  a46=(a21*a11);
  a06=(a06+a06);
  a06=(a02*a06);
  a44=(a08*a06);
  a49=(a17*a14);
  a44=(a44+a49);
  a44=(a46-a44);
  if (res[1]!=0) res[1][4]=a44;
  if (res[1]!=0) res[1][5]=a01;
  a44=(a08*a38);
  a46=(a44-a46);
  if (res[1]!=0) res[1][6]=a46;
  a46=(a08*a22);
  a10=(a10+a10);
  a02=(a02*a10);
  a10=(a17*a02);
  a10=(a46-a10);
  a10=(a10-a45);
  if (res[1]!=0) res[1][7]=a10;
  a10=(a08*a11);
  a40=(a10+a40);
  if (res[1]!=0) res[1][8]=a40;
  a40=(a08*a14);
  a45=(a17*a06);
  a45=(a40-a45);
  a45=(a45+a48);
  if (res[1]!=0) res[1][9]=a45;
  if (res[1]!=0) res[1][10]=a01;
  a47=(a47-a46);
  if (res[1]!=0) res[1][11]=a47;
  a44=(a44+a49);
  a49=(a21*a02);
  a44=(a44-a49);
  if (res[1]!=0) res[1][12]=a44;
  a37=(a37-a40);
  a40=(a21*a03);
  a37=(a37-a40);
  if (res[1]!=0) res[1][13]=a37;
  a10=(a10+a34);
  if (res[1]!=0) res[1][14]=a10;
  if (res[1]!=0) res[1][15]=a01;
  a10=(a15*a22);
  a34=(a17*a10);
  a37=(a19*a38);
  a40=(a24*a22);
  a44=(a37+a40);
  a44=(a08*a44);
  a34=(a34-a44);
  a44=(a15*a38);
  a49=(a21*a44);
  a34=(a34+a49);
  if (res[1]!=0) res[1][16]=a34;
  a22=(a19*a22);
  a38=(a24*a38);
  a34=(a22-a38);
  a34=(a08*a34);
  a49=(a17*a44);
  a34=(a34+a49);
  a49=(a21*a10);
  a34=(a34-a49);
  if (res[1]!=0) res[1][17]=a34;
  a34=(a19*a11);
  a49=(a24*a14);
  a47=(a34-a49);
  a47=(a08*a47);
  a46=(a15*a14);
  a45=(a19*a03);
  a45=(a46+a45);
  a45=(a17*a45);
  a47=(a47+a45);
  a45=(a24*a03);
  a48=(a15*a11);
  a50=(a45+a48);
  a50=(a21*a50);
  a47=(a47-a50);
  if (res[1]!=0) res[1][18]=a47;
  a47=(a19*a06);
  a50=(a48+a47);
  a50=(a17*a50);
  a14=(a19*a14);
  a11=(a24*a11);
  a51=(a14+a11);
  a51=(a08*a51);
  a50=(a50-a51);
  a51=(a24*a06);
  a51=(a46-a51);
  a51=(a21*a51);
  a50=(a50+a51);
  if (res[1]!=0) res[1][19]=a50;
  a50=(a17*a20);
  a51=(a21*a16);
  a50=(a50-a51);
  if (res[1]!=0) res[1][20]=a50;
  a50=(a21*a05);
  a20=(a08*a20);
  a50=(a50-a20);
  if (res[1]!=0) res[1][21]=a50;
  a16=(a08*a16);
  a05=(a17*a05);
  a16=(a16-a05);
  if (res[1]!=0) res[1][22]=a16;
  if (res[1]!=0) res[1][23]=a01;
  a16=(a08*a11);
  a05=(a48+a37);
  a05=(a17*a05);
  a16=(a16-a05);
  a05=(a21*a38);
  a16=(a16+a05);
  if (res[1]!=0) res[1][24]=a16;
  a19=(a19*a02);
  a19=(a49-a19);
  a19=(a08*a19);
  a16=(a46+a22);
  a16=(a17*a16);
  a19=(a19-a16);
  a16=(a15*a02);
  a05=(a40+a16);
  a05=(a21*a05);
  a19=(a19+a05);
  if (res[1]!=0) res[1][25]=a19;
  a19=(a44-a34);
  a19=(a17*a19);
  a05=(a08*a38);
  a19=(a19-a05);
  a05=(a21*a11);
  a19=(a19+a05);
  if (res[1]!=0) res[1][26]=a19;
  a19=(a10-a14);
  a19=(a17*a19);
  a47=(a47+a40);
  a47=(a08*a47);
  a19=(a19-a47);
  a06=(a15*a06);
  a06=(a49+a06);
  a06=(a21*a06);
  a19=(a19+a06);
  if (res[1]!=0) res[1][27]=a19;
  a19=(a17*a25);
  a06=(a21*a07);
  a19=(a19-a06);
  if (res[1]!=0) res[1][28]=a19;
  a19=(a21*a12);
  a25=(a08*a25);
  a19=(a19-a25);
  if (res[1]!=0) res[1][29]=a19;
  a07=(a08*a07);
  a12=(a17*a12);
  a07=(a07-a12);
  if (res[1]!=0) res[1][30]=a07;
  if (res[1]!=0) res[1][31]=a01;
  a07=(a08*a34);
  a12=(a17*a22);
  a07=(a07+a12);
  a40=(a40+a48);
  a40=(a21*a40);
  a07=(a07-a40);
  if (res[1]!=0) res[1][32]=a07;
  a24=(a24*a02);
  a24=(a14+a24);
  a24=(a08*a24);
  a16=(a16+a37);
  a16=(a17*a16);
  a24=(a24-a16);
  a38=(a38-a46);
  a38=(a21*a38);
  a24=(a24+a38);
  if (res[1]!=0) res[1][33]=a24;
  a37=(a37+a45);
  a37=(a08*a37);
  a15=(a15*a03);
  a14=(a14-a15);
  a14=(a17*a14);
  a37=(a37+a14);
  a49=(a49+a44);
  a49=(a21*a49);
  a37=(a37-a49);
  if (res[1]!=0) res[1][34]=a37;
  a22=(a08*a22);
  a34=(a17*a34);
  a22=(a22-a34);
  a11=(a11-a10);
  a11=(a21*a11);
  a22=(a22+a11);
  if (res[1]!=0) res[1][35]=a22;
  a22=(a17*a09);
  a11=(a21*a23);
  a22=(a22-a11);
  if (res[1]!=0) res[1][36]=a22;
  a21=(a21*a18);
  a09=(a08*a09);
  a21=(a21-a09);
  if (res[1]!=0) res[1][37]=a21;
  a08=(a08*a23);
  a17=(a17*a18);
  a08=(a08-a17);
  if (res[1]!=0) res[1][38]=a08;
  a08=(a00*a04);
  a17=(a31*a27);
  a18=(a08-a17);
  a23=(a33*a28);
  a18=(a18-a23);
  a21=(a35*a29);
  a18=(a18+a21);
  if (res[1]!=0) res[1][39]=a18;
  a18=(a00*a27);
  a09=(a31*a04);
  a22=(a18+a09);
  a11=(a33*a29);
  a22=(a22-a11);
  a10=(a35*a28);
  a22=(a22-a10);
  if (res[1]!=0) res[1][40]=a22;
  a22=(a00*a28);
  a34=(a31*a29);
  a37=(a22+a34);
  a49=(a33*a04);
  a37=(a37+a49);
  a44=(a35*a27);
  a37=(a37+a44);
  if (res[1]!=0) res[1][41]=a37;
  a31=(a31*a28);
  a00=(a00*a29);
  a29=(a31-a00);
  a33=(a33*a27);
  a29=(a29-a33);
  a35=(a35*a04);
  a29=(a29+a35);
  if (res[1]!=0) res[1][42]=a29;
  a00=(a00+a31);
  a31=(a00-a33);
  a31=(a31-a35);
  if (res[1]!=0) res[1][43]=a31;
  a31=(a34-a22);
  a31=(a31+a49);
  a31=(a31-a44);
  if (res[1]!=0) res[1][44]=a31;
  a18=(a18-a09);
  a09=(a18+a11);
  a09=(a09-a10);
  if (res[1]!=0) res[1][45]=a09;
  a08=(a08+a17);
  a17=(a08+a23);
  a17=(a17+a21);
  if (res[1]!=0) res[1][46]=a17;
  a22=(a22-a34);
  a22=(a22+a49);
  a22=(a22-a44);
  if (res[1]!=0) res[1][47]=a22;
  a00=(a00+a33);
  a00=(a00+a35);
  if (res[1]!=0) res[1][48]=a00;
  a23=(a23-a08);
  a23=(a23+a21);
  if (res[1]!=0) res[1][49]=a23;
  a18=(a18-a11);
  a18=(a18+a10);
  if (res[1]!=0) res[1][50]=a18;
  if (res[1]!=0) res[1][51]=a32;
  if (res[1]!=0) res[1][52]=a39;
  if (res[1]!=0) res[1][53]=a41;
  if (res[1]!=0) res[1][54]=a36;
  if (res[1]!=0) res[1][55]=a26;
  if (res[1]!=0) res[1][56]=a43;
  if (res[1]!=0) res[1][57]=a30;
  if (res[1]!=0) res[1][58]=a42;
  if (res[1]!=0) res[1][59]=a13;
  if (res[1]!=0) res[1][60]=a01;
  if (res[1]!=0) res[1][61]=a01;
  if (res[1]!=0) res[1][62]=a01;
  if (res[1]!=0) res[1][63]=a01;
  if (res[1]!=0) res[1][64]=a01;
  if (res[1]!=0) res[1][65]=a01;
  if (res[1]!=0) res[1][66]=a01;
  if (res[1]!=0) res[1][67]=a01;
  if (res[1]!=0) res[1][68]=a01;
  if (res[1]!=0) res[1][69]=a01;
  if (res[1]!=0) res[1][70]=a01;
  if (res[1]!=0) res[1][71]=a01;
  if (res[1]!=0) res[1][72]=a01;
  if (res[1]!=0) res[1][73]=a01;
  if (res[1]!=0) res[1][74]=a01;
  a13=-1.;
  if (res[1]!=0) res[1][75]=a13;
  if (res[1]!=0) res[1][76]=a01;
  if (res[1]!=0) res[1][77]=a13;
  if (res[1]!=0) res[1][78]=a01;
  if (res[1]!=0) res[1][79]=a13;
  if (res[1]!=0) res[1][80]=a01;
  if (res[1]!=0) res[1][81]=a13;
  if (res[1]!=0) res[1][82]=a01;
  if (res[1]!=0) res[1][83]=a13;
  if (res[1]!=0) res[1][84]=a01;
  if (res[1]!=0) res[1][85]=a13;
  if (res[1]!=0) res[1][86]=a01;
  if (res[1]!=0) res[1][87]=a13;
  if (res[1]!=0) res[1][88]=a01;
  if (res[1]!=0) res[1][89]=a13;
  return 0;
}

CASADI_SYMBOL_EXPORT int tilt_qd_servo_thrust_dist_mdl_cost_y_fun_jac_ut_xt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int tilt_qd_servo_thrust_dist_mdl_cost_y_fun_jac_ut_xt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int tilt_qd_servo_thrust_dist_mdl_cost_y_fun_jac_ut_xt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tilt_qd_servo_thrust_dist_mdl_cost_y_fun_jac_ut_xt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int tilt_qd_servo_thrust_dist_mdl_cost_y_fun_jac_ut_xt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tilt_qd_servo_thrust_dist_mdl_cost_y_fun_jac_ut_xt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void tilt_qd_servo_thrust_dist_mdl_cost_y_fun_jac_ut_xt_incref(void) {
}

CASADI_SYMBOL_EXPORT void tilt_qd_servo_thrust_dist_mdl_cost_y_fun_jac_ut_xt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int tilt_qd_servo_thrust_dist_mdl_cost_y_fun_jac_ut_xt_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int tilt_qd_servo_thrust_dist_mdl_cost_y_fun_jac_ut_xt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real tilt_qd_servo_thrust_dist_mdl_cost_y_fun_jac_ut_xt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tilt_qd_servo_thrust_dist_mdl_cost_y_fun_jac_ut_xt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tilt_qd_servo_thrust_dist_mdl_cost_y_fun_jac_ut_xt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tilt_qd_servo_thrust_dist_mdl_cost_y_fun_jac_ut_xt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tilt_qd_servo_thrust_dist_mdl_cost_y_fun_jac_ut_xt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s6;
    case 2: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int tilt_qd_servo_thrust_dist_mdl_cost_y_fun_jac_ut_xt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int tilt_qd_servo_thrust_dist_mdl_cost_y_fun_jac_ut_xt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
