/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) tilt_qd_servo_thrust_dist_imp_mdl_cost_y_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {27, 1, 1};
static const casadi_int casadi_s1[3] = {8, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {35, 1, 1};
static const casadi_int casadi_s4[3] = {0, 0, 1};
static const casadi_int casadi_s5[3] = {47, 1, 1};
static const casadi_int casadi_s6[159] = 
  {35, 35, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0,
  0, 14, 29, 44, 59, 65, 71, 77,
  83, 89, 95, 101, 106, 111, 116, 121,
  121, 121, 121, 121, 121, 121, 15, 16,
  17, 18, 19, 20, 21, 22, 23, 24,
  25, 26, 27, 28, 14, 15, 16, 17,
  18, 19, 20, 21, 22, 23, 24, 25,
  26, 27, 28, 14, 15, 16, 17, 18,
  19, 20, 21, 22, 23, 24, 25, 26,
  27, 28, 14, 15, 16, 17, 18, 19,
  20, 21, 22, 23, 24, 25, 26, 27,
  28, 14, 15, 16, 17, 19, 20, 14,
  15, 16, 17, 18, 20, 14, 15, 16,
  17, 18, 19, 14, 15, 16, 17, 21,
  25, 14, 15, 16, 17, 22, 26, 14,
  15, 16, 17, 23, 27, 14, 15, 16,
  17, 24, 28, 14, 15, 16, 17, 21,
  14, 15, 16, 17, 22, 14, 15, 16,
  17, 23, 14, 15, 16, 17, 24};

/* tilt_qd_servo_thrust_dist_imp_mdl_cost_y_hess:(i0[27],i1[8],i2[0],i3[35],i4[],i5[47])->(o0[35x35,121nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a000, a001, a002, a003, a004, a005, a006, a007, a008, a009, a010, a011;
  casadi_real a012, a013, a014, a015, a016, a017, a018, a019, a020, a021, a022, a023;
  casadi_real a024, a025, a026, a027, a028, a029, a030, a031, a032, a033, a034, a035;
  casadi_real a036, a037, a038, a039, a040, a041, a042, a043, a044, a045, a046, a047;
  casadi_real a048, a049, a050, a051, a052, a053, a054, a055, a056, a057, a058, a059;
  casadi_real a060, a061, a062, a063, a064, a065, a066, a067, a068, a069, a070, a071;
  casadi_real a072, a073, a074, a075, a076, a077, a078, a079, a080, a081, a082, a083;
  casadi_real a084, a085, a086, a087, a088, a089, a090, a091, a092, a093, a094, a095;
  casadi_real a096, a097, a098, a099, a100;
  a000=2.;
  a001=arg[0]? arg[0][12] : 0;
  a002=arg[5]? arg[5][28] : 0;
  a003=arg[3]? arg[3][5] : 0;
  a004=(a002*a003);
  a005=(a001*a004);
  a006=arg[0]? arg[0][10] : 0;
  a007=arg[5]? arg[5][30] : 0;
  a008=(a007*a003);
  a009=(a006*a008);
  a005=(a005-a009);
  a009=arg[5]? arg[5][29] : 0;
  a010=arg[3]? arg[3][2] : 0;
  a011=(a009*a010);
  a005=(a005+a011);
  a005=(a000*a005);
  a011=arg[5]? arg[5][11] : 0;
  a012=casadi_sq(a011);
  a013=arg[5]? arg[5][12] : 0;
  a014=casadi_sq(a013);
  a012=(a012+a014);
  a012=sqrt(a012);
  a014=(a011/a012);
  a015=arg[0]? arg[0][13] : 0;
  a016=sin(a015);
  a017=arg[0]? arg[0][17] : 0;
  a018=(a016*a017);
  a019=(a014*a018);
  a020=arg[5]? arg[5][15] : 0;
  a021=casadi_sq(a020);
  a022=arg[5]? arg[5][16] : 0;
  a023=casadi_sq(a022);
  a021=(a021+a023);
  a021=sqrt(a021);
  a023=(a020/a021);
  a024=arg[0]? arg[0][14] : 0;
  a025=sin(a024);
  a026=arg[0]? arg[0][18] : 0;
  a027=(a025*a026);
  a028=(a023*a027);
  a019=(a019+a028);
  a028=arg[5]? arg[5][19] : 0;
  a029=casadi_sq(a028);
  a030=arg[5]? arg[5][20] : 0;
  a031=casadi_sq(a030);
  a029=(a029+a031);
  a029=sqrt(a029);
  a031=(a028/a029);
  a032=arg[0]? arg[0][15] : 0;
  a033=sin(a032);
  a034=arg[0]? arg[0][19] : 0;
  a035=(a033*a034);
  a036=(a031*a035);
  a019=(a019+a036);
  a036=arg[5]? arg[5][23] : 0;
  a037=casadi_sq(a036);
  a038=arg[5]? arg[5][24] : 0;
  a039=casadi_sq(a038);
  a037=(a037+a039);
  a037=sqrt(a037);
  a039=(a036/a037);
  a040=arg[0]? arg[0][16] : 0;
  a041=sin(a040);
  a042=arg[0]? arg[0][20] : 0;
  a043=(a041*a042);
  a044=(a039*a043);
  a019=(a019+a044);
  a044=arg[5]? arg[5][43] : 0;
  a045=arg[3]? arg[3][23] : 0;
  a044=(a044*a045);
  a045=arg[5]? arg[5][4] : 0;
  a044=(a044/a045);
  a046=(a019*a044);
  a046=(a000*a046);
  a015=cos(a015);
  a047=(a015*a017);
  a024=cos(a024);
  a048=(a024*a026);
  a047=(a047+a048);
  a032=cos(a032);
  a048=(a032*a034);
  a047=(a047+a048);
  a040=cos(a040);
  a048=(a040*a042);
  a047=(a047+a048);
  a048=arg[5]? arg[5][42] : 0;
  a049=arg[3]? arg[3][22] : 0;
  a048=(a048*a049);
  a048=(a048/a045);
  a049=(a047*a048);
  a049=(a000*a049);
  a050=(a046+a049);
  a050=(a005-a050);
  a051=arg[3]? arg[3][4] : 0;
  a052=(a009*a051);
  a053=(a006*a052);
  a054=arg[0]? arg[0][11] : 0;
  a055=(a002*a051);
  a056=(a054*a055);
  a053=(a053-a056);
  a056=arg[3]? arg[3][1] : 0;
  a057=(a007*a056);
  a053=(a053+a057);
  a053=(a000*a053);
  a050=(a050-a053);
  if (res[0]!=0) res[0][0]=a050;
  a057=arg[5]? arg[5][41] : 0;
  a058=arg[3]? arg[3][21] : 0;
  a057=(a057*a058);
  a057=(a057/a045);
  a045=(a047*a057);
  a045=(a000*a045);
  a012=(a013/a012);
  a018=(a012*a018);
  a021=(a022/a021);
  a027=(a021*a027);
  a018=(a018+a027);
  a029=(a030/a029);
  a035=(a029*a035);
  a018=(a018+a035);
  a037=(a038/a037);
  a043=(a037*a043);
  a018=(a018+a043);
  a043=(a018*a044);
  a043=(a000*a043);
  a035=(a045-a043);
  a027=(a054*a008);
  a003=(a009*a003);
  a058=(a001*a003);
  a027=(a027-a058);
  a058=(a002*a010);
  a027=(a027+a058);
  a027=(a000*a027);
  a035=(a035-a027);
  a058=arg[3]? arg[3][3] : 0;
  a059=(a009*a058);
  a060=(a006*a059);
  a061=(a002*a058);
  a062=(a054*a061);
  a060=(a060-a062);
  a062=arg[3]? arg[3][0] : 0;
  a063=(a007*a062);
  a060=(a060+a063);
  a060=(a000*a060);
  a035=(a035+a060);
  if (res[0]!=0) res[0][1]=a035;
  a063=(a018*a048);
  a063=(a000*a063);
  a064=(a019*a057);
  a064=(a000*a064);
  a065=(a063+a064);
  a051=(a007*a051);
  a066=(a054*a051);
  a067=(a001*a052);
  a066=(a066-a067);
  a067=(a002*a056);
  a066=(a066+a067);
  a066=(a000*a066);
  a065=(a065+a066);
  a067=(a001*a061);
  a058=(a007*a058);
  a068=(a006*a058);
  a067=(a067-a068);
  a068=(a009*a062);
  a067=(a067+a068);
  a067=(a000*a067);
  a065=(a065-a067);
  if (res[0]!=0) res[0][2]=a065;
  a068=arg[0]? arg[0][9] : 0;
  a069=(a000*a068);
  a070=(a058*a069);
  a071=arg[0]? arg[0][7] : 0;
  a072=(a000*a071);
  a073=(a008*a072);
  a074=(a052*a072);
  a074=(a073+a074);
  a070=(a070-a074);
  a074=arg[0]? arg[0][8] : 0;
  a075=(a000*a074);
  a076=(a059*a075);
  a070=(a070+a076);
  if (res[0]!=0) res[0][3]=a070;
  a076=(a051*a069);
  a077=(a008*a075);
  a076=(a076-a077);
  a078=(a055*a072);
  a076=(a076+a078);
  a078=(a061*a075);
  a076=(a076-a078);
  if (res[0]!=0) res[0][4]=a076;
  a078=(a071*a004);
  a078=(a000*a078);
  a079=(a074*a003);
  a079=(a000*a079);
  a078=(a078+a079);
  a079=(a068*a052);
  a079=(a000*a079);
  a078=(a078-a079);
  a079=(a068*a061);
  a079=(a000*a079);
  a078=(a078-a079);
  if (res[0]!=0) res[0][5]=a078;
  a079=(a048*a069);
  a080=(a044*a075);
  a081=(a079-a080);
  a082=(a012*a081);
  a083=(a044*a072);
  a084=(a057*a069);
  a085=(a083-a084);
  a086=(a014*a085);
  a082=(a082-a086);
  a086=(a017*a082);
  a086=(a015*a086);
  a087=(a057*a075);
  a088=(a048*a072);
  a089=(a087-a088);
  a090=(a017*a089);
  a090=(a016*a090);
  a086=(a086-a090);
  if (res[0]!=0) res[0][6]=a086;
  a090=(a021*a081);
  a091=(a023*a085);
  a090=(a090-a091);
  a091=(a026*a090);
  a091=(a024*a091);
  a092=(a026*a089);
  a092=(a025*a092);
  a091=(a091-a092);
  if (res[0]!=0) res[0][7]=a091;
  a092=(a029*a081);
  a093=(a031*a085);
  a092=(a092-a093);
  a093=(a034*a092);
  a093=(a032*a093);
  a094=(a034*a089);
  a094=(a033*a094);
  a093=(a093-a094);
  if (res[0]!=0) res[0][8]=a093;
  a081=(a037*a081);
  a085=(a039*a085);
  a081=(a081-a085);
  a085=(a042*a081);
  a085=(a040*a085);
  a094=(a042*a089);
  a094=(a041*a094);
  a085=(a085-a094);
  if (res[0]!=0) res[0][9]=a085;
  a094=(a015*a089);
  a082=(a016*a082);
  a094=(a094+a082);
  if (res[0]!=0) res[0][10]=a094;
  a082=(a024*a089);
  a090=(a025*a090);
  a082=(a082+a090);
  if (res[0]!=0) res[0][11]=a082;
  a090=(a032*a089);
  a092=(a033*a092);
  a090=(a090+a092);
  if (res[0]!=0) res[0][12]=a090;
  a089=(a040*a089);
  a081=(a041*a081);
  a089=(a089+a081);
  if (res[0]!=0) res[0][13]=a089;
  if (res[0]!=0) res[0][14]=a050;
  a019=(a019*a048);
  a019=(a000*a019);
  a019=(a000*a019);
  a047=(a047*a044);
  a047=(a000*a047);
  a047=(a000*a047);
  a050=(a019-a047);
  a081=(a006*a003);
  a092=(a054*a004);
  a081=(a081-a092);
  a007=(a007*a010);
  a081=(a081+a007);
  a081=(a000*a081);
  a081=(a000*a081);
  a050=(a050-a081);
  a007=(a001*a055);
  a006=(a006*a051);
  a007=(a007-a006);
  a009=(a009*a056);
  a007=(a007+a009);
  a007=(a000*a007);
  a007=(a000*a007);
  a050=(a050-a007);
  if (res[0]!=0) res[0][15]=a050;
  a063=(a063-a064);
  a063=(a063+a066);
  a063=(a063+a067);
  if (res[0]!=0) res[0][16]=a063;
  a043=(a043+a045);
  a043=(a043+a027);
  a043=(a043+a060);
  if (res[0]!=0) res[0][17]=a043;
  a060=(a071+a071);
  a027=(a000*a060);
  a045=(a051*a027);
  a067=arg[0]? arg[0][6] : 0;
  a067=(a000*a067);
  a066=(a008*a067);
  a064=(a003*a027);
  a064=(a066+a064);
  a045=(a045-a064);
  a064=(a052*a067);
  a045=(a045-a064);
  a064=(a058*a075);
  a045=(a045-a064);
  a064=(a059*a069);
  a045=(a045+a064);
  if (res[0]!=0) res[0][18]=a045;
  a008=(a008*a069);
  a064=(a004*a027);
  a064=(a008+a064);
  a050=(a051*a075);
  a064=(a064+a050);
  a050=(a055*a067);
  a064=(a064+a050);
  a050=(a061*a069);
  a064=(a064-a050);
  if (res[0]!=0) res[0][19]=a064;
  a050=(a067*a004);
  a009=(a068*a003);
  a009=(a000*a009);
  a050=(a050-a009);
  a009=(a000*a055);
  a060=(a060*a009);
  a050=(a050-a060);
  a060=(a074*a052);
  a060=(a000*a060);
  a050=(a050-a060);
  a060=(a074*a061);
  a060=(a000*a060);
  a050=(a050+a060);
  if (res[0]!=0) res[0][20]=a050;
  a060=(a044*a069);
  a056=(a048*a075);
  a006=(a060+a056);
  a010=(a012*a006);
  a092=(a044*a067);
  a095=(a048*a027);
  a095=(a092-a095);
  a095=(a095+a087);
  a087=(a014*a095);
  a010=(a010-a087);
  a087=(a017*a010);
  a087=(a015*a087);
  a027=(a044*a027);
  a096=(a048*a067);
  a027=(a027+a096);
  a084=(a084-a027);
  a027=(a017*a084);
  a027=(a016*a027);
  a087=(a087-a027);
  if (res[0]!=0) res[0][21]=a087;
  a027=(a021*a006);
  a097=(a023*a095);
  a027=(a027-a097);
  a097=(a026*a027);
  a097=(a024*a097);
  a098=(a026*a084);
  a098=(a025*a098);
  a097=(a097-a098);
  if (res[0]!=0) res[0][22]=a097;
  a098=(a029*a006);
  a099=(a031*a095);
  a098=(a098-a099);
  a099=(a034*a098);
  a099=(a032*a099);
  a100=(a034*a084);
  a100=(a033*a100);
  a099=(a099-a100);
  if (res[0]!=0) res[0][23]=a099;
  a006=(a037*a006);
  a095=(a039*a095);
  a006=(a006-a095);
  a095=(a042*a006);
  a095=(a040*a095);
  a100=(a042*a084);
  a100=(a041*a100);
  a095=(a095-a100);
  if (res[0]!=0) res[0][24]=a095;
  a100=(a015*a084);
  a010=(a016*a010);
  a100=(a100+a010);
  if (res[0]!=0) res[0][25]=a100;
  a010=(a024*a084);
  a027=(a025*a027);
  a010=(a010+a027);
  if (res[0]!=0) res[0][26]=a010;
  a027=(a032*a084);
  a098=(a033*a098);
  a027=(a027+a098);
  if (res[0]!=0) res[0][27]=a027;
  a084=(a040*a084);
  a006=(a041*a006);
  a084=(a084+a006);
  if (res[0]!=0) res[0][28]=a084;
  if (res[0]!=0) res[0][29]=a035;
  if (res[0]!=0) res[0][30]=a063;
  a018=(a018*a057);
  a018=(a000*a018);
  a018=(a000*a018);
  a047=(a047+a018);
  a047=(a047+a081);
  a054=(a054*a058);
  a001=(a001*a059);
  a054=(a054-a001);
  a002=(a002*a062);
  a054=(a054+a002);
  a054=(a000*a054);
  a054=(a000*a054);
  a047=(a047+a054);
  a047=(-a047);
  if (res[0]!=0) res[0][31]=a047;
  a049=(a049-a046);
  a049=(a049+a005);
  a049=(a049+a053);
  if (res[0]!=0) res[0][32]=a049;
  a053=(a052*a069);
  a005=(a074+a074);
  a046=(a000*a005);
  a047=(a003*a046);
  a008=(a008+a047);
  a053=(a053-a008);
  a008=(a058*a072);
  a053=(a053-a008);
  a008=(a059*a067);
  a053=(a053+a008);
  if (res[0]!=0) res[0][33]=a053;
  a008=(a004*a046);
  a008=(a008-a066);
  a066=(a051*a072);
  a008=(a008+a066);
  a069=(a055*a069);
  a008=(a008-a069);
  a069=(a058*a046);
  a008=(a008-a069);
  a069=(a061*a067);
  a008=(a008-a069);
  if (res[0]!=0) res[0][34]=a008;
  a069=(a068*a004);
  a069=(a000*a069);
  a066=(a067*a003);
  a069=(a069+a066);
  a066=(a072*a052);
  a069=(a069-a066);
  a066=(a072*a061);
  a069=(a069+a066);
  a066=(a000*a059);
  a005=(a005*a066);
  a069=(a069+a005);
  if (res[0]!=0) res[0][35]=a069;
  a088=(a088-a092);
  a092=(a057*a046);
  a088=(a088-a092);
  a092=(a012*a088);
  a005=(a057*a072);
  a060=(a060+a005);
  a047=(a014*a060);
  a092=(a092-a047);
  a047=(a017*a092);
  a047=(a015*a047);
  a046=(a044*a046);
  a079=(a079-a046);
  a046=(a057*a067);
  a079=(a079+a046);
  a002=(a017*a079);
  a002=(a016*a002);
  a047=(a047-a002);
  if (res[0]!=0) res[0][36]=a047;
  a002=(a021*a088);
  a062=(a023*a060);
  a002=(a002-a062);
  a062=(a026*a002);
  a062=(a024*a062);
  a001=(a026*a079);
  a001=(a025*a001);
  a062=(a062-a001);
  if (res[0]!=0) res[0][37]=a062;
  a001=(a029*a088);
  a081=(a031*a060);
  a001=(a001-a081);
  a081=(a034*a001);
  a081=(a032*a081);
  a063=(a034*a079);
  a063=(a033*a063);
  a081=(a081-a063);
  if (res[0]!=0) res[0][38]=a081;
  a088=(a037*a088);
  a060=(a039*a060);
  a088=(a088-a060);
  a060=(a042*a088);
  a060=(a040*a060);
  a063=(a042*a079);
  a063=(a041*a063);
  a060=(a060-a063);
  if (res[0]!=0) res[0][39]=a060;
  a063=(a015*a079);
  a092=(a016*a092);
  a063=(a063+a092);
  if (res[0]!=0) res[0][40]=a063;
  a092=(a024*a079);
  a002=(a025*a002);
  a092=(a092+a002);
  if (res[0]!=0) res[0][41]=a092;
  a002=(a032*a079);
  a001=(a033*a001);
  a002=(a002+a001);
  if (res[0]!=0) res[0][42]=a002;
  a079=(a040*a079);
  a088=(a041*a088);
  a079=(a079+a088);
  if (res[0]!=0) res[0][43]=a079;
  if (res[0]!=0) res[0][44]=a065;
  if (res[0]!=0) res[0][45]=a043;
  if (res[0]!=0) res[0][46]=a049;
  a019=(a019-a018);
  a019=(a019-a007);
  a019=(a019-a054);
  if (res[0]!=0) res[0][47]=a019;
  a019=(a068+a068);
  a054=(a000*a019);
  a007=(a051*a054);
  a007=(a007-a077);
  a077=(a052*a075);
  a007=(a007+a077);
  a077=(a058*a067);
  a007=(a007+a077);
  a059=(a059*a072);
  a007=(a007+a059);
  if (res[0]!=0) res[0][48]=a007;
  a051=(a051*a067);
  a073=(a073+a051);
  a055=(a055*a075);
  a073=(a073-a055);
  a058=(a058*a054);
  a073=(a073-a058);
  a058=(a061*a072);
  a073=(a073-a058);
  if (res[0]!=0) res[0][49]=a073;
  a004=(a075*a004);
  a003=(a072*a003);
  a004=(a004-a003);
  a009=(a019*a009);
  a004=(a004-a009);
  a052=(a067*a052);
  a004=(a004-a052);
  a061=(a067*a061);
  a004=(a004-a061);
  a019=(a019*a066);
  a004=(a004+a019);
  if (res[0]!=0) res[0][50]=a004;
  a083=(a083+a096);
  a096=(a057*a054);
  a083=(a083-a096);
  a096=(a012*a083);
  a054=(a048*a054);
  a080=(a080-a054);
  a080=(a080-a046);
  a046=(a014*a080);
  a096=(a096-a046);
  a046=(a017*a096);
  a046=(a015*a046);
  a056=(a056+a005);
  a005=(a017*a056);
  a005=(a016*a005);
  a046=(a046-a005);
  if (res[0]!=0) res[0][51]=a046;
  a005=(a021*a083);
  a054=(a023*a080);
  a005=(a005-a054);
  a054=(a026*a005);
  a054=(a024*a054);
  a019=(a026*a056);
  a019=(a025*a019);
  a054=(a054-a019);
  if (res[0]!=0) res[0][52]=a054;
  a019=(a029*a083);
  a066=(a031*a080);
  a019=(a019-a066);
  a066=(a034*a019);
  a066=(a032*a066);
  a061=(a034*a056);
  a061=(a033*a061);
  a066=(a066-a061);
  if (res[0]!=0) res[0][53]=a066;
  a083=(a037*a083);
  a080=(a039*a080);
  a083=(a083-a080);
  a080=(a042*a083);
  a080=(a040*a080);
  a061=(a042*a056);
  a061=(a041*a061);
  a080=(a080-a061);
  if (res[0]!=0) res[0][54]=a080;
  a061=(a015*a056);
  a096=(a016*a096);
  a061=(a061+a096);
  if (res[0]!=0) res[0][55]=a061;
  a096=(a024*a056);
  a005=(a025*a005);
  a096=(a096+a005);
  if (res[0]!=0) res[0][56]=a096;
  a005=(a032*a056);
  a019=(a033*a019);
  a005=(a005+a019);
  if (res[0]!=0) res[0][57]=a005;
  a056=(a040*a056);
  a083=(a041*a083);
  a056=(a056+a083);
  if (res[0]!=0) res[0][58]=a056;
  if (res[0]!=0) res[0][59]=a070;
  if (res[0]!=0) res[0][60]=a045;
  if (res[0]!=0) res[0][61]=a053;
  if (res[0]!=0) res[0][62]=a007;
  a007=arg[5]? arg[5][6] : 0;
  a053=arg[5]? arg[5][46] : 0;
  a045=arg[3]? arg[3][26] : 0;
  a053=(a053*a045);
  a045=arg[5]? arg[5][8] : 0;
  a053=(a053/a045);
  a070=(a007*a053);
  a083=arg[5]? arg[5][7] : 0;
  a019=(a053*a083);
  a070=(a070-a019);
  if (res[0]!=0) res[0][63]=a070;
  a019=arg[5]? arg[5][45] : 0;
  a052=arg[3]? arg[3][25] : 0;
  a019=(a019*a052);
  a019=(a019/a083);
  a052=(a019*a045);
  a009=(a007*a019);
  a052=(a052-a009);
  if (res[0]!=0) res[0][64]=a052;
  if (res[0]!=0) res[0][65]=a076;
  if (res[0]!=0) res[0][66]=a064;
  if (res[0]!=0) res[0][67]=a008;
  if (res[0]!=0) res[0][68]=a073;
  if (res[0]!=0) res[0][69]=a070;
  a070=arg[5]? arg[5][44] : 0;
  a073=arg[3]? arg[3][24] : 0;
  a070=(a070*a073);
  a070=(a070/a007);
  a083=(a083*a070);
  a045=(a070*a045);
  a083=(a083-a045);
  if (res[0]!=0) res[0][70]=a083;
  if (res[0]!=0) res[0][71]=a078;
  if (res[0]!=0) res[0][72]=a050;
  if (res[0]!=0) res[0][73]=a069;
  if (res[0]!=0) res[0][74]=a004;
  if (res[0]!=0) res[0][75]=a052;
  if (res[0]!=0) res[0][76]=a083;
  if (res[0]!=0) res[0][77]=a086;
  if (res[0]!=0) res[0][78]=a087;
  if (res[0]!=0) res[0][79]=a047;
  if (res[0]!=0) res[0][80]=a046;
  a046=arg[5]? arg[5][10] : 0;
  a047=(a046*a017);
  a087=arg[5]? arg[5][9] : 0;
  a047=(a047*a087);
  a086=(a014*a019);
  a083=(a012*a070);
  a086=(a086-a083);
  a083=(a047*a086);
  a052=arg[5]? arg[5][13] : 0;
  a004=(a052*a019);
  a069=(a013*a053);
  a004=(a004-a069);
  a004=(a012*a004);
  a052=(a052*a070);
  a069=(a011*a053);
  a052=(a052-a069);
  a052=(a014*a052);
  a004=(a004+a052);
  a052=(a017*a004);
  a083=(a083+a052);
  a052=(a072*a068);
  a069=(a067*a074);
  a050=(a052-a069);
  a050=(a050*a044);
  a072=(a072*a074);
  a078=(a067*a068);
  a045=(a072+a078);
  a045=(a045*a048);
  a050=(a050+a045);
  a045=1.;
  a074=casadi_sq(a074);
  a074=(a000*a074);
  a007=(a045-a074);
  a073=casadi_sq(a068);
  a073=(a000*a073);
  a007=(a007-a073);
  a007=(a007*a057);
  a050=(a050+a007);
  a012=(a012*a050);
  a075=(a075*a068);
  a067=(a067*a071);
  a068=(a075+a067);
  a068=(a068*a044);
  a071=casadi_sq(a071);
  a000=(a000*a071);
  a045=(a045-a000);
  a073=(a045-a073);
  a073=(a073*a048);
  a068=(a068+a073);
  a072=(a072-a078);
  a072=(a072*a057);
  a068=(a068+a072);
  a014=(a014*a068);
  a012=(a012-a014);
  a014=(a017*a012);
  a083=(a083+a014);
  a083=(a083*a016);
  a013=(a013*a070);
  a011=(a011*a019);
  a013=(a013-a011);
  a011=(a017*a013);
  a047=(a047*a053);
  a011=(a011-a047);
  a045=(a045-a074);
  a045=(a045*a044);
  a075=(a075-a067);
  a075=(a075*a048);
  a045=(a045+a075);
  a052=(a052+a069);
  a052=(a052*a057);
  a045=(a045+a052);
  a017=(a017*a045);
  a011=(a011+a017);
  a011=(a011*a015);
  a083=(a083+a011);
  a083=(-a083);
  if (res[0]!=0) res[0][81]=a083;
  a046=(a087*a046);
  a086=(a086*a046);
  a086=(a086+a004);
  a086=(a086+a012);
  a015=(a015*a086);
  a046=(a053*a046);
  a013=(a013-a046);
  a013=(a013+a045);
  a016=(a016*a013);
  a015=(a015-a016);
  if (res[0]!=0) res[0][82]=a015;
  if (res[0]!=0) res[0][83]=a091;
  if (res[0]!=0) res[0][84]=a097;
  if (res[0]!=0) res[0][85]=a062;
  if (res[0]!=0) res[0][86]=a054;
  a054=arg[5]? arg[5][17] : 0;
  a062=(a054*a019);
  a097=(a022*a053);
  a062=(a062-a097);
  a062=(a021*a062);
  a054=(a054*a070);
  a097=(a020*a053);
  a054=(a054-a097);
  a054=(a023*a054);
  a062=(a062+a054);
  a054=(a026*a062);
  a097=arg[5]? arg[5][14] : 0;
  a091=(a097*a026);
  a091=(a091*a087);
  a016=(a023*a019);
  a013=(a021*a070);
  a016=(a016-a013);
  a013=(a091*a016);
  a054=(a054+a013);
  a021=(a021*a050);
  a023=(a023*a068);
  a021=(a021-a023);
  a023=(a026*a021);
  a054=(a054+a023);
  a054=(a054*a025);
  a022=(a022*a070);
  a020=(a020*a019);
  a022=(a022-a020);
  a020=(a026*a022);
  a091=(a091*a053);
  a020=(a020-a091);
  a026=(a026*a045);
  a020=(a020+a026);
  a020=(a020*a024);
  a054=(a054+a020);
  a054=(-a054);
  if (res[0]!=0) res[0][87]=a054;
  a097=(a087*a097);
  a016=(a016*a097);
  a062=(a062+a016);
  a062=(a062+a021);
  a024=(a024*a062);
  a097=(a053*a097);
  a022=(a022-a097);
  a022=(a022+a045);
  a025=(a025*a022);
  a024=(a024-a025);
  if (res[0]!=0) res[0][88]=a024;
  if (res[0]!=0) res[0][89]=a093;
  if (res[0]!=0) res[0][90]=a099;
  if (res[0]!=0) res[0][91]=a081;
  if (res[0]!=0) res[0][92]=a066;
  a066=arg[5]? arg[5][21] : 0;
  a081=(a066*a019);
  a099=(a030*a053);
  a081=(a081-a099);
  a081=(a029*a081);
  a066=(a066*a070);
  a099=(a028*a053);
  a066=(a066-a099);
  a066=(a031*a066);
  a081=(a081+a066);
  a066=(a034*a081);
  a099=arg[5]? arg[5][18] : 0;
  a093=(a099*a034);
  a093=(a093*a087);
  a025=(a031*a019);
  a022=(a029*a070);
  a025=(a025-a022);
  a022=(a093*a025);
  a066=(a066+a022);
  a029=(a029*a050);
  a031=(a031*a068);
  a029=(a029-a031);
  a031=(a034*a029);
  a066=(a066+a031);
  a066=(a066*a033);
  a030=(a030*a070);
  a028=(a028*a019);
  a030=(a030-a028);
  a028=(a034*a030);
  a093=(a093*a053);
  a028=(a028-a093);
  a034=(a034*a045);
  a028=(a028+a034);
  a028=(a028*a032);
  a066=(a066+a028);
  a066=(-a066);
  if (res[0]!=0) res[0][93]=a066;
  a099=(a087*a099);
  a025=(a025*a099);
  a081=(a081+a025);
  a081=(a081+a029);
  a032=(a032*a081);
  a099=(a053*a099);
  a030=(a030-a099);
  a030=(a030+a045);
  a033=(a033*a030);
  a032=(a032-a033);
  if (res[0]!=0) res[0][94]=a032;
  if (res[0]!=0) res[0][95]=a085;
  if (res[0]!=0) res[0][96]=a095;
  if (res[0]!=0) res[0][97]=a060;
  if (res[0]!=0) res[0][98]=a080;
  a080=arg[5]? arg[5][25] : 0;
  a060=(a080*a019);
  a095=(a038*a053);
  a060=(a060-a095);
  a060=(a037*a060);
  a080=(a080*a070);
  a095=(a036*a053);
  a080=(a080-a095);
  a080=(a039*a080);
  a060=(a060+a080);
  a080=(a042*a060);
  a095=arg[5]? arg[5][22] : 0;
  a085=(a095*a042);
  a085=(a085*a087);
  a033=(a039*a019);
  a030=(a037*a070);
  a033=(a033-a030);
  a030=(a085*a033);
  a080=(a080+a030);
  a037=(a037*a050);
  a039=(a039*a068);
  a037=(a037-a039);
  a039=(a042*a037);
  a080=(a080+a039);
  a080=(a080*a041);
  a038=(a038*a070);
  a036=(a036*a019);
  a038=(a038-a036);
  a036=(a042*a038);
  a085=(a085*a053);
  a036=(a036-a085);
  a042=(a042*a045);
  a036=(a036+a042);
  a036=(a036*a040);
  a080=(a080+a036);
  a080=(-a080);
  if (res[0]!=0) res[0][99]=a080;
  a087=(a087*a095);
  a033=(a033*a087);
  a060=(a060+a033);
  a060=(a060+a037);
  a040=(a040*a060);
  a053=(a053*a087);
  a038=(a038-a053);
  a038=(a038+a045);
  a041=(a041*a038);
  a040=(a040-a041);
  if (res[0]!=0) res[0][100]=a040;
  if (res[0]!=0) res[0][101]=a094;
  if (res[0]!=0) res[0][102]=a100;
  if (res[0]!=0) res[0][103]=a063;
  if (res[0]!=0) res[0][104]=a061;
  if (res[0]!=0) res[0][105]=a015;
  if (res[0]!=0) res[0][106]=a082;
  if (res[0]!=0) res[0][107]=a010;
  if (res[0]!=0) res[0][108]=a092;
  if (res[0]!=0) res[0][109]=a096;
  if (res[0]!=0) res[0][110]=a024;
  if (res[0]!=0) res[0][111]=a090;
  if (res[0]!=0) res[0][112]=a027;
  if (res[0]!=0) res[0][113]=a002;
  if (res[0]!=0) res[0][114]=a005;
  if (res[0]!=0) res[0][115]=a032;
  if (res[0]!=0) res[0][116]=a089;
  if (res[0]!=0) res[0][117]=a084;
  if (res[0]!=0) res[0][118]=a079;
  if (res[0]!=0) res[0][119]=a056;
  if (res[0]!=0) res[0][120]=a040;
  return 0;
}

CASADI_SYMBOL_EXPORT int tilt_qd_servo_thrust_dist_imp_mdl_cost_y_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int tilt_qd_servo_thrust_dist_imp_mdl_cost_y_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int tilt_qd_servo_thrust_dist_imp_mdl_cost_y_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tilt_qd_servo_thrust_dist_imp_mdl_cost_y_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int tilt_qd_servo_thrust_dist_imp_mdl_cost_y_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tilt_qd_servo_thrust_dist_imp_mdl_cost_y_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void tilt_qd_servo_thrust_dist_imp_mdl_cost_y_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void tilt_qd_servo_thrust_dist_imp_mdl_cost_y_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int tilt_qd_servo_thrust_dist_imp_mdl_cost_y_hess_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int tilt_qd_servo_thrust_dist_imp_mdl_cost_y_hess_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real tilt_qd_servo_thrust_dist_imp_mdl_cost_y_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tilt_qd_servo_thrust_dist_imp_mdl_cost_y_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tilt_qd_servo_thrust_dist_imp_mdl_cost_y_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tilt_qd_servo_thrust_dist_imp_mdl_cost_y_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    case 5: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tilt_qd_servo_thrust_dist_imp_mdl_cost_y_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int tilt_qd_servo_thrust_dist_imp_mdl_cost_y_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int tilt_qd_servo_thrust_dist_imp_mdl_cost_y_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
