/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) tilt_qd_servo_thrust_dist_imp_mdl_cost_y_0_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {27, 1, 1};
static const casadi_int casadi_s1[3] = {8, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {0, 0, 1};
static const casadi_int casadi_s4[3] = {47, 1, 1};
static const casadi_int casadi_s5[3] = {35, 1, 1};

/* tilt_qd_servo_thrust_dist_imp_mdl_cost_y_0_fun:(i0[27],i1[8],i2[0],i3[],i4[47])->(o0[35]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  casadi_real a48, a49, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59;
  a00=arg[0]? arg[0][0] : 0;
  a01=1.;
  a02=2.;
  a03=arg[0]? arg[0][8] : 0;
  a04=casadi_sq(a03);
  a04=(a02*a04);
  a05=(a01-a04);
  a06=arg[0]? arg[0][9] : 0;
  a07=casadi_sq(a06);
  a07=(a02*a07);
  a05=(a05-a07);
  a08=arg[4]? arg[4][28] : 0;
  a09=(a05*a08);
  a10=arg[0]? arg[0][7] : 0;
  a11=(a02*a10);
  a12=(a11*a03);
  a13=arg[0]? arg[0][6] : 0;
  a14=(a02*a13);
  a15=(a14*a06);
  a16=(a12-a15);
  a17=arg[4]? arg[4][29] : 0;
  a18=(a16*a17);
  a09=(a09+a18);
  a11=(a11*a06);
  a18=(a14*a03);
  a19=(a11+a18);
  a20=arg[4]? arg[4][30] : 0;
  a21=(a19*a20);
  a09=(a09+a21);
  a00=(a00+a09);
  if (res[0]!=0) res[0][0]=a00;
  a00=arg[0]? arg[0][1] : 0;
  a12=(a12+a15);
  a15=(a12*a08);
  a09=casadi_sq(a10);
  a09=(a02*a09);
  a09=(a01-a09);
  a07=(a09-a07);
  a21=(a07*a17);
  a15=(a15+a21);
  a21=(a02*a03);
  a21=(a21*a06);
  a14=(a14*a10);
  a22=(a21-a14);
  a23=(a22*a20);
  a15=(a15+a23);
  a00=(a00+a15);
  if (res[0]!=0) res[0][1]=a00;
  a00=arg[0]? arg[0][2] : 0;
  a11=(a11-a18);
  a18=(a11*a08);
  a21=(a21+a14);
  a14=(a21*a17);
  a18=(a18+a14);
  a09=(a09-a04);
  a04=(a09*a20);
  a18=(a18+a04);
  a00=(a00+a18);
  if (res[0]!=0) res[0][2]=a00;
  a00=arg[0]? arg[0][3] : 0;
  a18=arg[0]? arg[0][12] : 0;
  a04=(a16*a18);
  a14=arg[0]? arg[0][11] : 0;
  a15=(a19*a14);
  a04=(a04-a15);
  a04=(a04*a08);
  a15=arg[0]? arg[0][10] : 0;
  a23=(a19*a15);
  a24=(a05*a18);
  a23=(a23-a24);
  a23=(a23*a17);
  a04=(a04+a23);
  a23=(a05*a14);
  a24=(a16*a15);
  a23=(a23-a24);
  a23=(a23*a20);
  a04=(a04+a23);
  a00=(a00+a04);
  if (res[0]!=0) res[0][3]=a00;
  a00=arg[0]? arg[0][4] : 0;
  a04=(a07*a18);
  a23=(a22*a14);
  a04=(a04-a23);
  a04=(a04*a08);
  a23=(a22*a15);
  a24=(a12*a18);
  a23=(a23-a24);
  a23=(a23*a17);
  a04=(a04+a23);
  a23=(a12*a14);
  a24=(a07*a15);
  a23=(a23-a24);
  a23=(a23*a20);
  a04=(a04+a23);
  a00=(a00+a04);
  if (res[0]!=0) res[0][4]=a00;
  a00=arg[0]? arg[0][5] : 0;
  a04=(a21*a18);
  a23=(a09*a14);
  a04=(a04-a23);
  a04=(a04*a08);
  a08=(a09*a15);
  a23=(a11*a18);
  a08=(a08-a23);
  a08=(a08*a17);
  a04=(a04+a08);
  a08=(a11*a14);
  a17=(a21*a15);
  a08=(a08-a17);
  a08=(a08*a20);
  a04=(a04+a08);
  a00=(a00+a04);
  if (res[0]!=0) res[0][5]=a00;
  a00=arg[4]? arg[4][0] : 0;
  if (res[0]!=0) res[0][6]=a00;
  a04=arg[4]? arg[4][32] : 0;
  a08=(a13*a04);
  a20=arg[4]? arg[4][31] : 0;
  a17=(a10*a20);
  a08=(a08+a17);
  a17=arg[4]? arg[4][34] : 0;
  a23=(a03*a17);
  a08=(a08+a23);
  a23=arg[4]? arg[4][33] : 0;
  a24=(a06*a23);
  a08=(a08-a24);
  a24=(a00*a08);
  a25=arg[4]? arg[4][1] : 0;
  a26=(a13*a20);
  a27=(a10*a04);
  a26=(a26-a27);
  a27=(a03*a23);
  a26=(a26-a27);
  a27=(a06*a17);
  a26=(a26-a27);
  a27=(a25*a26);
  a24=(a24-a27);
  a27=arg[4]? arg[4][2] : 0;
  a28=(a13*a17);
  a29=(a10*a23);
  a28=(a28+a29);
  a29=(a03*a04);
  a28=(a28-a29);
  a29=(a06*a20);
  a28=(a28+a29);
  a29=(a27*a28);
  a24=(a24-a29);
  a29=arg[4]? arg[4][3] : 0;
  a13=(a13*a23);
  a10=(a10*a17);
  a13=(a13-a10);
  a03=(a03*a20);
  a13=(a13+a03);
  a06=(a06*a04);
  a13=(a13+a06);
  a06=(a29*a13);
  a24=(a24+a06);
  a24=(a24+a25);
  if (res[0]!=0) res[0][7]=a24;
  a24=(a00*a13);
  a06=(a25*a28);
  a24=(a24+a06);
  a06=(a27*a26);
  a24=(a24-a06);
  a06=(a29*a08);
  a24=(a24-a06);
  a24=(a24+a27);
  if (res[0]!=0) res[0][8]=a24;
  a00=(a00*a28);
  a25=(a25*a13);
  a00=(a00-a25);
  a27=(a27*a08);
  a00=(a00+a27);
  a26=(a29*a26);
  a00=(a00-a26);
  a00=(a00+a29);
  if (res[0]!=0) res[0][9]=a00;
  a00=casadi_sq(a23);
  a00=(a02*a00);
  a29=(a01-a00);
  a26=casadi_sq(a17);
  a26=(a02*a26);
  a29=(a29-a26);
  a29=(a29*a15);
  a27=(a02*a04);
  a08=(a27*a23);
  a20=(a02*a20);
  a25=(a20*a17);
  a13=(a08+a25);
  a13=(a13*a14);
  a29=(a29+a13);
  a27=(a27*a17);
  a13=(a20*a23);
  a28=(a27-a13);
  a28=(a28*a18);
  a29=(a29+a28);
  if (res[0]!=0) res[0][10]=a29;
  a08=(a08-a25);
  a08=(a08*a15);
  a25=casadi_sq(a04);
  a25=(a02*a25);
  a01=(a01-a25);
  a26=(a01-a26);
  a26=(a26*a14);
  a08=(a08+a26);
  a02=(a02*a23);
  a02=(a02*a17);
  a20=(a20*a04);
  a04=(a02+a20);
  a04=(a04*a18);
  a08=(a08+a04);
  if (res[0]!=0) res[0][11]=a08;
  a27=(a27+a13);
  a27=(a27*a15);
  a02=(a02-a20);
  a02=(a02*a14);
  a27=(a27+a02);
  a01=(a01-a00);
  a01=(a01*a18);
  a27=(a27+a01);
  if (res[0]!=0) res[0][12]=a27;
  a27=arg[0]? arg[0][13] : 0;
  if (res[0]!=0) res[0][13]=a27;
  a01=arg[0]? arg[0][14] : 0;
  if (res[0]!=0) res[0][14]=a01;
  a00=arg[0]? arg[0][15] : 0;
  if (res[0]!=0) res[0][15]=a00;
  a02=arg[0]? arg[0][16] : 0;
  if (res[0]!=0) res[0][16]=a02;
  a20=arg[0]? arg[0][17] : 0;
  if (res[0]!=0) res[0][17]=a20;
  a13=arg[0]? arg[0][18] : 0;
  if (res[0]!=0) res[0][18]=a13;
  a08=arg[0]? arg[0][19] : 0;
  if (res[0]!=0) res[0][19]=a08;
  a04=arg[0]? arg[0][20] : 0;
  if (res[0]!=0) res[0][20]=a04;
  a17=arg[4]? arg[4][12] : 0;
  a23=arg[4]? arg[4][11] : 0;
  a26=casadi_sq(a23);
  a25=casadi_sq(a17);
  a26=(a26+a25);
  a26=sqrt(a26);
  a25=(a17/a26);
  a29=sin(a27);
  a28=(a29*a20);
  a24=(a25*a28);
  a06=arg[4]? arg[4][16] : 0;
  a03=arg[4]? arg[4][15] : 0;
  a10=casadi_sq(a03);
  a30=casadi_sq(a06);
  a10=(a10+a30);
  a10=sqrt(a10);
  a30=(a06/a10);
  a31=sin(a01);
  a32=(a31*a13);
  a33=(a30*a32);
  a34=(a24+a33);
  a35=arg[4]? arg[4][20] : 0;
  a36=arg[4]? arg[4][19] : 0;
  a37=casadi_sq(a36);
  a38=casadi_sq(a35);
  a37=(a37+a38);
  a37=sqrt(a37);
  a38=(a35/a37);
  a39=sin(a00);
  a40=(a39*a08);
  a41=(a38*a40);
  a34=(a34+a41);
  a42=arg[4]? arg[4][24] : 0;
  a43=arg[4]? arg[4][23] : 0;
  a44=casadi_sq(a43);
  a45=casadi_sq(a42);
  a44=(a44+a45);
  a44=sqrt(a44);
  a45=(a42/a44);
  a46=sin(a02);
  a47=(a46*a04);
  a48=(a45*a47);
  a34=(a34+a48);
  a05=(a05*a34);
  a26=(a23/a26);
  a28=(a26*a28);
  a10=(a03/a10);
  a32=(a10*a32);
  a49=(a28+a32);
  a37=(a36/a37);
  a40=(a37*a40);
  a49=(a49+a40);
  a44=(a43/a44);
  a47=(a44*a47);
  a49=(a49+a47);
  a16=(a16*a49);
  a05=(a05-a16);
  a16=cos(a27);
  a50=(a16*a20);
  a51=cos(a01);
  a52=(a51*a13);
  a53=(a50+a52);
  a54=cos(a00);
  a55=(a54*a08);
  a53=(a53+a55);
  a56=cos(a02);
  a57=(a56*a04);
  a53=(a53+a57);
  a19=(a19*a53);
  a05=(a05+a19);
  a19=arg[0]? arg[0][21] : 0;
  a05=(a05+a19);
  a58=arg[4]? arg[4][35] : 0;
  a05=(a05+a58);
  a58=arg[4]? arg[4][4] : 0;
  a05=(a05/a58);
  a59=arg[4]? arg[4][41] : 0;
  a05=(a05*a59);
  a05=(a05-a19);
  if (res[0]!=0) res[0][21]=a05;
  a12=(a12*a34);
  a07=(a07*a49);
  a12=(a12-a07);
  a22=(a22*a53);
  a12=(a12+a22);
  a22=arg[0]? arg[0][22] : 0;
  a12=(a12+a22);
  a07=arg[4]? arg[4][36] : 0;
  a12=(a12+a07);
  a12=(a12/a58);
  a07=arg[4]? arg[4][42] : 0;
  a12=(a12*a07);
  a12=(a12-a22);
  if (res[0]!=0) res[0][22]=a12;
  a11=(a11*a34);
  a21=(a21*a49);
  a11=(a11-a21);
  a09=(a09*a53);
  a11=(a11+a09);
  a09=arg[0]? arg[0][23] : 0;
  a11=(a11+a09);
  a53=arg[4]? arg[4][37] : 0;
  a11=(a11+a53);
  a11=(a11/a58);
  a58=arg[4]? arg[4][5] : 0;
  a11=(a11-a58);
  a58=arg[4]? arg[4][43] : 0;
  a11=(a11*a58);
  a11=(a11-a09);
  if (res[0]!=0) res[0][23]=a11;
  a11=(a17*a50);
  a09=arg[4]? arg[4][13] : 0;
  a58=(a09*a28);
  a11=(a11+a58);
  a58=arg[4]? arg[4][10] : 0;
  a58=(a58*a20);
  a53=arg[4]? arg[4][9] : 0;
  a58=(a58*a53);
  a29=(a29*a58);
  a25=(a25*a29);
  a21=arg[4]? arg[4][14] : 0;
  a21=(a21*a13);
  a21=(a21*a53);
  a31=(a31*a21);
  a30=(a30*a31);
  a25=(a25+a30);
  a30=arg[4]? arg[4][18] : 0;
  a30=(a30*a08);
  a30=(a30*a53);
  a39=(a39*a30);
  a38=(a38*a39);
  a25=(a25+a38);
  a38=arg[4]? arg[4][22] : 0;
  a38=(a38*a04);
  a38=(a38*a53);
  a46=(a46*a38);
  a45=(a45*a46);
  a25=(a25+a45);
  a11=(a11-a25);
  a25=(a06*a52);
  a45=arg[4]? arg[4][17] : 0;
  a53=(a45*a32);
  a25=(a25+a53);
  a11=(a11+a25);
  a25=(a35*a55);
  a53=arg[4]? arg[4][21] : 0;
  a49=(a53*a40);
  a25=(a25+a49);
  a11=(a11+a25);
  a25=(a42*a57);
  a49=arg[4]? arg[4][25] : 0;
  a34=(a49*a47);
  a25=(a25+a34);
  a11=(a11+a25);
  a25=arg[4]? arg[4][8] : 0;
  a34=(a25*a18);
  a12=(a14*a34);
  a22=arg[4]? arg[4][7] : 0;
  a07=(a22*a14);
  a05=(a18*a07);
  a12=(a12-a05);
  a11=(a11-a12);
  a12=arg[0]? arg[0][24] : 0;
  a11=(a11+a12);
  a05=arg[4]? arg[4][38] : 0;
  a11=(a11+a05);
  a05=arg[4]? arg[4][6] : 0;
  a11=(a11/a05);
  a19=arg[4]? arg[4][44] : 0;
  a11=(a11*a19);
  a11=(a11-a12);
  if (res[0]!=0) res[0][24]=a11;
  a26=(a26*a29);
  a10=(a10*a31);
  a26=(a26+a10);
  a37=(a37*a39);
  a26=(a26+a37);
  a44=(a44*a46);
  a26=(a26+a44);
  a09=(a09*a24);
  a50=(a23*a50);
  a09=(a09-a50);
  a26=(a26+a09);
  a45=(a45*a33);
  a52=(a03*a52);
  a45=(a45-a52);
  a26=(a26+a45);
  a53=(a53*a41);
  a55=(a36*a55);
  a53=(a53-a55);
  a26=(a26+a53);
  a49=(a49*a48);
  a57=(a43*a57);
  a49=(a49-a57);
  a26=(a26+a49);
  a05=(a05*a15);
  a18=(a18*a05);
  a34=(a15*a34);
  a18=(a18-a34);
  a26=(a26-a18);
  a18=arg[0]? arg[0][25] : 0;
  a26=(a26+a18);
  a34=arg[4]? arg[4][39] : 0;
  a26=(a26+a34);
  a26=(a26/a22);
  a22=arg[4]? arg[4][45] : 0;
  a26=(a26*a22);
  a26=(a26-a18);
  if (res[0]!=0) res[0][25]=a26;
  a26=arg[0]? arg[0][26] : 0;
  a15=(a15*a07);
  a14=(a14*a05);
  a15=(a15-a14);
  a16=(a16*a58);
  a51=(a51*a21);
  a16=(a16+a51);
  a54=(a54*a30);
  a16=(a16+a54);
  a56=(a56*a38);
  a16=(a16+a56);
  a23=(a23*a28);
  a17=(a17*a24);
  a23=(a23+a17);
  a16=(a16+a23);
  a03=(a03*a32);
  a06=(a06*a33);
  a03=(a03+a06);
  a16=(a16+a03);
  a36=(a36*a40);
  a35=(a35*a41);
  a36=(a36+a35);
  a16=(a16+a36);
  a43=(a43*a47);
  a42=(a42*a48);
  a43=(a43+a42);
  a16=(a16+a43);
  a15=(a15+a16);
  a15=(a26-a15);
  a16=arg[4]? arg[4][40] : 0;
  a15=(a15+a16);
  a15=(a15/a25);
  a25=arg[4]? arg[4][46] : 0;
  a15=(a15*a25);
  a15=(a15-a26);
  if (res[0]!=0) res[0][26]=a15;
  a15=arg[1]? arg[1][0] : 0;
  a15=(a15-a20);
  if (res[0]!=0) res[0][27]=a15;
  a15=arg[1]? arg[1][1] : 0;
  a15=(a15-a13);
  if (res[0]!=0) res[0][28]=a15;
  a15=arg[1]? arg[1][2] : 0;
  a15=(a15-a08);
  if (res[0]!=0) res[0][29]=a15;
  a15=arg[1]? arg[1][3] : 0;
  a15=(a15-a04);
  if (res[0]!=0) res[0][30]=a15;
  a15=arg[1]? arg[1][4] : 0;
  a15=(a15-a27);
  if (res[0]!=0) res[0][31]=a15;
  a15=arg[1]? arg[1][5] : 0;
  a15=(a15-a01);
  if (res[0]!=0) res[0][32]=a15;
  a15=arg[1]? arg[1][6] : 0;
  a15=(a15-a00);
  if (res[0]!=0) res[0][33]=a15;
  a15=arg[1]? arg[1][7] : 0;
  a15=(a15-a02);
  if (res[0]!=0) res[0][34]=a15;
  return 0;
}

CASADI_SYMBOL_EXPORT int tilt_qd_servo_thrust_dist_imp_mdl_cost_y_0_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int tilt_qd_servo_thrust_dist_imp_mdl_cost_y_0_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int tilt_qd_servo_thrust_dist_imp_mdl_cost_y_0_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tilt_qd_servo_thrust_dist_imp_mdl_cost_y_0_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int tilt_qd_servo_thrust_dist_imp_mdl_cost_y_0_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tilt_qd_servo_thrust_dist_imp_mdl_cost_y_0_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void tilt_qd_servo_thrust_dist_imp_mdl_cost_y_0_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void tilt_qd_servo_thrust_dist_imp_mdl_cost_y_0_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int tilt_qd_servo_thrust_dist_imp_mdl_cost_y_0_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int tilt_qd_servo_thrust_dist_imp_mdl_cost_y_0_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real tilt_qd_servo_thrust_dist_imp_mdl_cost_y_0_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tilt_qd_servo_thrust_dist_imp_mdl_cost_y_0_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tilt_qd_servo_thrust_dist_imp_mdl_cost_y_0_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tilt_qd_servo_thrust_dist_imp_mdl_cost_y_0_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tilt_qd_servo_thrust_dist_imp_mdl_cost_y_0_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int tilt_qd_servo_thrust_dist_imp_mdl_cost_y_0_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int tilt_qd_servo_thrust_dist_imp_mdl_cost_y_0_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
