/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) fix_qd_thrust_out_mdl_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {35, 1, 1};
static const casadi_int casadi_s3[3] = {17, 1, 1};

/* fix_qd_thrust_out_mdl_expl_vde_adj:(i0[13],i1[13],i2[4],i3[35])->(o0[17]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27;
  a00=0.;
  if (res[0]!=0) res[0][0]=a00;
  if (res[0]!=0) res[0][1]=a00;
  if (res[0]!=0) res[0][2]=a00;
  a00=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][3]=a00;
  a00=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][4]=a00;
  a00=arg[1]? arg[1][2] : 0;
  if (res[0]!=0) res[0][5]=a00;
  a00=arg[0]? arg[0][12] : 0;
  a01=5.0000000000000000e-01;
  a02=arg[1]? arg[1][9] : 0;
  a02=(a01*a02);
  a03=(a00*a02);
  a04=arg[0]? arg[0][11] : 0;
  a05=arg[1]? arg[1][8] : 0;
  a05=(a01*a05);
  a06=(a04*a05);
  a03=(a03+a06);
  a06=arg[0]? arg[0][10] : 0;
  a07=arg[1]? arg[1][7] : 0;
  a07=(a01*a07);
  a08=(a06*a07);
  a03=(a03+a08);
  a08=2.;
  a09=arg[0]? arg[0][7] : 0;
  a10=arg[2]? arg[2][0] : 0;
  a11=arg[2]? arg[2][1] : 0;
  a10=(a10+a11);
  a11=arg[2]? arg[2][2] : 0;
  a10=(a10+a11);
  a11=arg[2]? arg[2][3] : 0;
  a10=(a10+a11);
  a11=arg[1]? arg[1][4] : 0;
  a12=arg[3]? arg[3][4] : 0;
  a11=(a11/a12);
  a13=(a10*a11);
  a14=(a09*a13);
  a14=(a08*a14);
  a03=(a03-a14);
  a14=arg[0]? arg[0][8] : 0;
  a15=arg[1]? arg[1][3] : 0;
  a15=(a15/a12);
  a16=(a10*a15);
  a17=(a14*a16);
  a17=(a08*a17);
  a03=(a03+a17);
  if (res[0]!=0) res[0][6]=a03;
  a03=(a04*a02);
  a17=(a00*a05);
  a03=(a03-a17);
  a17=arg[1]? arg[1][6] : 0;
  a01=(a01*a17);
  a17=(a06*a01);
  a03=(a03-a17);
  a17=(a09+a09);
  a18=arg[1]? arg[1][5] : 0;
  a18=(a18/a12);
  a10=(a10*a18);
  a10=(a08*a10);
  a17=(a17*a10);
  a03=(a03-a17);
  a17=arg[0]? arg[0][6] : 0;
  a12=(a08*a17);
  a19=(a12*a13);
  a03=(a03-a19);
  a19=arg[0]? arg[0][9] : 0;
  a20=(a19*a16);
  a20=(a08*a20);
  a03=(a03+a20);
  if (res[0]!=0) res[0][7]=a03;
  a03=(a00*a07);
  a20=(a06*a02);
  a03=(a03-a20);
  a20=(a04*a01);
  a03=(a03-a20);
  a20=(a14+a14);
  a20=(a20*a10);
  a03=(a03-a20);
  a20=(a19*a13);
  a20=(a08*a20);
  a03=(a03+a20);
  a20=(a12*a16);
  a03=(a03+a20);
  if (res[0]!=0) res[0][8]=a03;
  a03=(a06*a05);
  a20=(a04*a07);
  a03=(a03-a20);
  a20=(a00*a01);
  a03=(a03-a20);
  a20=(a08*a14);
  a13=(a20*a13);
  a03=(a03+a13);
  a13=(a08*a09);
  a16=(a13*a16);
  a03=(a03+a16);
  if (res[0]!=0) res[0][9]=a03;
  a03=arg[3]? arg[3][8] : 0;
  a16=(a03*a00);
  a10=arg[1]? arg[1][11] : 0;
  a21=arg[3]? arg[3][7] : 0;
  a10=(a10/a21);
  a22=(a16*a10);
  a23=(a21*a04);
  a24=arg[1]? arg[1][12] : 0;
  a24=(a24/a03);
  a25=(a23*a24);
  a22=(a22-a25);
  a25=arg[3]? arg[3][6] : 0;
  a26=(a04*a24);
  a27=(a00*a10);
  a26=(a26-a27);
  a26=(a25*a26);
  a22=(a22+a26);
  a26=(a14*a02);
  a22=(a22-a26);
  a26=(a19*a05);
  a22=(a22+a26);
  a26=(a17*a07);
  a22=(a22+a26);
  a26=(a09*a01);
  a22=(a22-a26);
  if (res[0]!=0) res[0][10]=a22;
  a22=(a25*a06);
  a26=(a22*a24);
  a27=arg[1]? arg[1][10] : 0;
  a27=(a27/a25);
  a00=(a00*a27);
  a25=(a06*a24);
  a00=(a00-a25);
  a21=(a21*a00);
  a26=(a26+a21);
  a16=(a16*a27);
  a26=(a26-a16);
  a16=(a09*a02);
  a26=(a26+a16);
  a16=(a17*a05);
  a26=(a26+a16);
  a16=(a19*a07);
  a26=(a26-a16);
  a16=(a14*a01);
  a26=(a26-a16);
  if (res[0]!=0) res[0][11]=a26;
  a23=(a23*a27);
  a22=(a22*a10);
  a23=(a23-a22);
  a06=(a06*a10);
  a04=(a04*a27);
  a06=(a06-a04);
  a03=(a03*a06);
  a23=(a23+a03);
  a17=(a17*a02);
  a23=(a23+a17);
  a05=(a09*a05);
  a23=(a23-a05);
  a07=(a14*a07);
  a23=(a23+a07);
  a01=(a19*a01);
  a23=(a23-a01);
  if (res[0]!=0) res[0][12]=a23;
  a23=arg[3]? arg[3][12] : 0;
  a23=(a23*a27);
  a01=arg[3]? arg[3][10] : 0;
  a07=arg[3]? arg[3][9] : 0;
  a07=(a07*a24);
  a01=(a01*a07);
  a24=arg[3]? arg[3][11] : 0;
  a24=(a24*a10);
  a01=(a01+a24);
  a23=(a23-a01);
  a01=1.;
  a24=casadi_sq(a09);
  a24=(a08*a24);
  a01=(a01-a24);
  a24=casadi_sq(a14);
  a08=(a08*a24);
  a01=(a01-a08);
  a01=(a01*a18);
  a20=(a20*a19);
  a09=(a12*a09);
  a20=(a20-a09);
  a20=(a20*a11);
  a01=(a01+a20);
  a13=(a13*a19);
  a12=(a12*a14);
  a13=(a13+a12);
  a13=(a13*a15);
  a01=(a01+a13);
  a23=(a23+a01);
  if (res[0]!=0) res[0][13]=a23;
  a23=arg[3]? arg[3][16] : 0;
  a23=(a23*a27);
  a13=arg[3]? arg[3][14] : 0;
  a13=(a13*a07);
  a15=arg[3]? arg[3][15] : 0;
  a15=(a15*a10);
  a13=(a13+a15);
  a23=(a23-a13);
  a23=(a23+a01);
  if (res[0]!=0) res[0][14]=a23;
  a23=arg[3]? arg[3][20] : 0;
  a23=(a23*a27);
  a13=arg[3]? arg[3][18] : 0;
  a13=(a13*a07);
  a15=arg[3]? arg[3][19] : 0;
  a15=(a15*a10);
  a13=(a13+a15);
  a23=(a23-a13);
  a23=(a23+a01);
  if (res[0]!=0) res[0][15]=a23;
  a23=arg[3]? arg[3][24] : 0;
  a23=(a23*a27);
  a27=arg[3]? arg[3][22] : 0;
  a27=(a27*a07);
  a07=arg[3]? arg[3][23] : 0;
  a07=(a07*a10);
  a27=(a27+a07);
  a23=(a23-a27);
  a23=(a23+a01);
  if (res[0]!=0) res[0][16]=a23;
  return 0;
}

CASADI_SYMBOL_EXPORT int fix_qd_thrust_out_mdl_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int fix_qd_thrust_out_mdl_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int fix_qd_thrust_out_mdl_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void fix_qd_thrust_out_mdl_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int fix_qd_thrust_out_mdl_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void fix_qd_thrust_out_mdl_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void fix_qd_thrust_out_mdl_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void fix_qd_thrust_out_mdl_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int fix_qd_thrust_out_mdl_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int fix_qd_thrust_out_mdl_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real fix_qd_thrust_out_mdl_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* fix_qd_thrust_out_mdl_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* fix_qd_thrust_out_mdl_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* fix_qd_thrust_out_mdl_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* fix_qd_thrust_out_mdl_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int fix_qd_thrust_out_mdl_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int fix_qd_thrust_out_mdl_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
