/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) tilt_bi_servo_mdl_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {15, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};

/* tilt_bi_servo_mdl_expl_ode_fun:(i0[15],i1[4],i2[4])->(o0[15]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26;
  a00=arg[0]? arg[0][3] : 0;
  if (res[0]!=0) res[0][0]=a00;
  a00=arg[0]? arg[0][4] : 0;
  if (res[0]!=0) res[0][1]=a00;
  a00=arg[0]? arg[0][5] : 0;
  if (res[0]!=0) res[0][2]=a00;
  a00=1.;
  a01=2.;
  a02=arg[0]? arg[0][8] : 0;
  a03=casadi_sq(a02);
  a03=(a01*a03);
  a04=(a00-a03);
  a05=arg[0]? arg[0][9] : 0;
  a06=casadi_sq(a05);
  a06=(a01*a06);
  a04=(a04-a06);
  a06=arg[0]? arg[0][13] : 0;
  a07=sin(a06);
  a08=arg[1]? arg[1][0] : 0;
  a09=(a07*a08);
  a10=arg[0]? arg[0][14] : 0;
  a11=sin(a10);
  a12=arg[1]? arg[1][1] : 0;
  a13=(a11*a12);
  a14=(a09-a13);
  a04=(a04*a14);
  a15=arg[0]? arg[0][7] : 0;
  a16=(a01*a15);
  a17=(a16*a05);
  a18=arg[0]? arg[0][6] : 0;
  a19=(a01*a18);
  a20=(a19*a02);
  a21=(a17+a20);
  a22=cos(a06);
  a23=(a22*a08);
  a24=cos(a10);
  a25=(a24*a12);
  a26=(a23+a25);
  a21=(a21*a26);
  a04=(a04+a21);
  a21=1.4444100000000000e+00;
  a04=(a04/a21);
  if (res[0]!=0) res[0][3]=a04;
  a16=(a16*a02);
  a04=(a19*a05);
  a16=(a16+a04);
  a16=(a16*a14);
  a04=(a01*a02);
  a04=(a04*a05);
  a19=(a19*a15);
  a04=(a04-a19);
  a04=(a04*a26);
  a16=(a16+a04);
  a16=(a16/a21);
  if (res[0]!=0) res[0][4]=a16;
  a17=(a17-a20);
  a17=(a17*a14);
  a14=casadi_sq(a15);
  a14=(a01*a14);
  a00=(a00-a14);
  a00=(a00-a03);
  a00=(a00*a26);
  a17=(a17+a00);
  a17=(a17/a21);
  a21=-9.7980000000000000e+00;
  a17=(a17+a21);
  if (res[0]!=0) res[0][5]=a17;
  a17=arg[0]? arg[0][10] : 0;
  a21=(a17*a15);
  a00=arg[0]? arg[0][11] : 0;
  a26=(a00*a02);
  a21=(a21+a26);
  a26=arg[0]? arg[0][12] : 0;
  a03=(a26*a05);
  a21=(a21+a03);
  a21=(a21/a01);
  a21=(-a21);
  if (res[0]!=0) res[0][6]=a21;
  a21=(a17*a18);
  a03=(a26*a02);
  a21=(a21+a03);
  a03=(a00*a05);
  a21=(a21-a03);
  a21=(a21/a01);
  if (res[0]!=0) res[0][7]=a21;
  a21=(a00*a18);
  a03=(a26*a15);
  a21=(a21-a03);
  a05=(a17*a05);
  a21=(a21+a05);
  a21=(a21/a01);
  if (res[0]!=0) res[0][8]=a21;
  a18=(a26*a18);
  a15=(a00*a15);
  a18=(a18+a15);
  a02=(a17*a02);
  a18=(a18-a02);
  a18=(a18/a01);
  if (res[0]!=0) res[0][9]=a18;
  a18=1.8041097620379226e+01;
  a01=2.3749999999999999e-01;
  a23=(a01*a23);
  a02=1.7200000000000000e-02;
  a08=(a02*a08);
  a07=(a07*a08);
  a02=(a02*a12);
  a11=(a11*a02);
  a07=(a07+a11);
  a23=(a23-a07);
  a07=-2.3749999999999999e-01;
  a25=(a07*a25);
  a23=(a23+a25);
  a25=6.7850999999999995e-02;
  a25=(a25*a26);
  a11=(a00*a25);
  a12=1.7873000000000000e-02;
  a12=(a12*a00);
  a15=(a26*a12);
  a11=(a11-a15);
  a23=(a23-a11);
  a18=(a18*a23);
  if (res[0]!=0) res[0][10]=a18;
  a18=5.5950316119286072e+01;
  a23=1.2098000000000000e-01;
  a11=(a23*a09);
  a23=(a23*a13);
  a11=(a11-a23);
  a23=5.5428999999999999e-02;
  a23=(a23*a17);
  a26=(a26*a23);
  a25=(a17*a25);
  a26=(a26-a25);
  a11=(a11-a26);
  a18=(a18*a11);
  if (res[0]!=0) res[0][11]=a18;
  a18=1.4738176298064879e+01;
  a24=(a24*a02);
  a22=(a22*a08);
  a24=(a24-a22);
  a01=(a01*a09);
  a24=(a24-a01);
  a07=(a07*a13);
  a24=(a24+a07);
  a17=(a17*a12);
  a00=(a00*a23);
  a17=(a17-a00);
  a24=(a24-a17);
  a18=(a18*a24);
  if (res[0]!=0) res[0][12]=a18;
  a18=arg[1]? arg[1][2] : 0;
  a18=(a18-a06);
  a06=1.5858000000000000e-01;
  a18=(a18/a06);
  if (res[0]!=0) res[0][13]=a18;
  a18=arg[1]? arg[1][3] : 0;
  a18=(a18-a10);
  a18=(a18/a06);
  if (res[0]!=0) res[0][14]=a18;
  return 0;
}

CASADI_SYMBOL_EXPORT int tilt_bi_servo_mdl_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int tilt_bi_servo_mdl_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int tilt_bi_servo_mdl_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tilt_bi_servo_mdl_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int tilt_bi_servo_mdl_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tilt_bi_servo_mdl_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void tilt_bi_servo_mdl_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void tilt_bi_servo_mdl_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int tilt_bi_servo_mdl_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int tilt_bi_servo_mdl_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real tilt_bi_servo_mdl_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tilt_bi_servo_mdl_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tilt_bi_servo_mdl_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tilt_bi_servo_mdl_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tilt_bi_servo_mdl_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int tilt_bi_servo_mdl_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int tilt_bi_servo_mdl_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
