sensor_plugin:
        gicp:
                sensor_frame: lidar_imu
                time_sync: false
                registration:
                        init:
                                map_voxel_size: 0.1
                                scan_voxel_size: 0.1
                                max_corres_dist: 0.1
                                localization_thresh: 0.85
                                map_range: 15.0
                                scan_range: 15.0
                        float:
                                map_voxel_size: 0.3
                                scan_voxel_size: 0.1
                                max_corres_dist: 0.6
                                localization_thresh: 0.75
                                map_range: 12.0
                                scan_range: 6.0
                        fix:
                                map_voxel_size: 0.2
                                scan_voxel_size: 0.1
                                max_corres_dist: 0.3
                                localization_thresh: 0.85
                                map_range: 10.0
                                scan_range: 5.0
