/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) tilt_tri_servo_mdl_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {16, 1, 1};
static const casadi_int casadi_s1[3] = {6, 1, 1};
static const casadi_int casadi_s2[3] = {4, 1, 1};

/* tilt_tri_servo_mdl_expl_ode_fun:(i0[16],i1[6],i2[4])->(o0[16]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45;
  a00=arg[0]? arg[0][3] : 0;
  if (res[0]!=0) res[0][0]=a00;
  a00=arg[0]? arg[0][4] : 0;
  if (res[0]!=0) res[0][1]=a00;
  a00=arg[0]? arg[0][5] : 0;
  if (res[0]!=0) res[0][2]=a00;
  a00=2.;
  a01=arg[0]? arg[0][7] : 0;
  a02=(a00*a01);
  a03=arg[0]? arg[0][9] : 0;
  a04=(a02*a03);
  a05=arg[0]? arg[0][6] : 0;
  a06=(a00*a05);
  a07=arg[0]? arg[0][8] : 0;
  a08=(a06*a07);
  a09=(a04+a08);
  a10=arg[0]? arg[0][13] : 0;
  a11=cos(a10);
  a12=arg[1]? arg[1][0] : 0;
  a13=(a11*a12);
  a14=arg[0]? arg[0][14] : 0;
  a15=cos(a14);
  a16=arg[1]? arg[1][1] : 0;
  a17=(a15*a16);
  a18=(a13+a17);
  a19=arg[0]? arg[0][15] : 0;
  a20=cos(a19);
  a21=arg[1]? arg[1][2] : 0;
  a22=(a20*a21);
  a18=(a18+a22);
  a09=(a09*a18);
  a23=1.;
  a24=casadi_sq(a07);
  a24=(a00*a24);
  a25=(a23-a24);
  a26=casadi_sq(a03);
  a26=(a00*a26);
  a25=(a25-a26);
  a27=9.3971157813970552e-01;
  a28=sin(a10);
  a29=(a28*a12);
  a30=(a27*a29);
  a31=-9.3969306746094605e-01;
  a32=sin(a14);
  a33=(a32*a16);
  a34=(a31*a33);
  a35=(a30+a34);
  a36=9.4757538721294815e-05;
  a37=sin(a19);
  a38=(a37*a21);
  a39=(a36*a38);
  a35=(a35+a39);
  a25=(a25*a35);
  a02=(a02*a07);
  a40=(a06*a03);
  a41=(a02-a40);
  a42=3.4196805393221158e-01;
  a29=(a42*a29);
  a43=3.4201891609359575e-01;
  a33=(a43*a33);
  a44=(a29+a33);
  a45=-9.9999999551050445e-01;
  a38=(a45*a38);
  a44=(a44+a38);
  a41=(a41*a44);
  a25=(a25+a41);
  a09=(a09-a25);
  a25=1.5212699999999999e+00;
  a09=(a09/a25);
  if (res[0]!=0) res[0][3]=a09;
  a09=(a00*a07);
  a09=(a09*a03);
  a06=(a06*a01);
  a41=(a09-a06);
  a41=(a41*a18);
  a02=(a02+a40);
  a02=(a02*a35);
  a40=casadi_sq(a01);
  a40=(a00*a40);
  a23=(a23-a40);
  a26=(a23-a26);
  a26=(a26*a44);
  a02=(a02+a26);
  a41=(a41-a02);
  a41=(a41/a25);
  if (res[0]!=0) res[0][4]=a41;
  a23=(a23-a24);
  a23=(a23*a18);
  a04=(a04-a08);
  a04=(a04*a35);
  a09=(a09+a06);
  a09=(a09*a44);
  a04=(a04+a09);
  a23=(a23-a04);
  a23=(a23/a25);
  a25=-9.7980000000000000e+00;
  a23=(a23+a25);
  if (res[0]!=0) res[0][5]=a23;
  a23=arg[0]? arg[0][10] : 0;
  a25=(a23*a01);
  a04=arg[0]? arg[0][11] : 0;
  a09=(a04*a07);
  a25=(a25+a09);
  a09=arg[0]? arg[0][12] : 0;
  a44=(a09*a03);
  a25=(a25+a44);
  a25=(a25/a00);
  a25=(-a25);
  if (res[0]!=0) res[0][6]=a25;
  a25=(a23*a05);
  a44=(a09*a07);
  a25=(a25+a44);
  a44=(a04*a03);
  a25=(a25-a44);
  a25=(a25/a00);
  if (res[0]!=0) res[0][7]=a25;
  a25=(a04*a05);
  a44=(a09*a01);
  a25=(a25-a44);
  a03=(a23*a03);
  a25=(a25+a03);
  a25=(a25/a00);
  if (res[0]!=0) res[0][8]=a25;
  a05=(a09*a05);
  a01=(a04*a01);
  a05=(a05+a01);
  a07=(a23*a07);
  a05=(a05-a07);
  a05=(a05/a00);
  if (res[0]!=0) res[0][9]=a05;
  a05=3.9837463150346586e+01;
  a00=1.7200000000000000e-02;
  a12=(a00*a12);
  a28=(a28*a12);
  a27=(a27*a28);
  a16=(a00*a16);
  a32=(a32*a16);
  a31=(a31*a32);
  a27=(a27-a31);
  a00=(a00*a21);
  a37=(a37*a00);
  a36=(a36*a37);
  a27=(a27+a36);
  a36=-2.3752000000000001e-01;
  a21=(a36*a13);
  a31=2.5907500000000000e-02;
  a07=(a31*a29);
  a21=(a21+a07);
  a27=(a27+a21);
  a21=2.3748000000000000e-01;
  a07=(a21*a17);
  a01=(a31*a33);
  a07=(a07+a01);
  a27=(a27+a07);
  a07=-2.0000000000000002e-05;
  a01=(a07*a22);
  a25=(a31*a38);
  a01=(a01+a25);
  a27=(a27+a01);
  a01=3.8796100000000000e-02;
  a01=(a01*a09);
  a25=(a04*a01);
  a03=1.9084199999999999e-02;
  a03=(a03*a04);
  a44=(a09*a03);
  a25=(a25-a44);
  a27=(a27-a25);
  a05=(a05*a27);
  if (res[0]!=0) res[0][10]=a05;
  a05=5.2399367015646455e+01;
  a42=(a42*a28);
  a43=(a43*a32);
  a42=(a42-a43);
  a45=(a45*a37);
  a42=(a42+a45);
  a45=(a31*a30);
  a37=8.6435300000000007e-02;
  a13=(a37*a13);
  a45=(a45+a13);
  a42=(a42-a45);
  a45=(a31*a34);
  a17=(a37*a17);
  a45=(a45+a17);
  a42=(a42-a45);
  a31=(a31*a39);
  a45=-2.1106500000000000e-01;
  a22=(a45*a22);
  a31=(a31+a22);
  a42=(a42-a31);
  a31=2.5101999999999999e-02;
  a31=(a31*a23);
  a09=(a09*a31);
  a01=(a23*a01);
  a09=(a09-a01);
  a42=(a42-a09);
  a05=(a05*a42);
  if (res[0]!=0) res[0][11]=a05;
  a05=2.5775786741450815e+01;
  a15=(a15*a16);
  a11=(a11*a12);
  a15=(a15-a11);
  a20=(a20*a00);
  a15=(a15-a20);
  a36=(a36*a30);
  a29=(a37*a29);
  a36=(a36-a29);
  a15=(a15+a36);
  a21=(a21*a34);
  a37=(a37*a33);
  a21=(a21-a37);
  a15=(a15+a21);
  a07=(a07*a39);
  a45=(a45*a38);
  a07=(a07-a45);
  a15=(a15+a07);
  a23=(a23*a03);
  a04=(a04*a31);
  a23=(a23-a04);
  a15=(a15-a23);
  a05=(a05*a15);
  if (res[0]!=0) res[0][12]=a05;
  a05=arg[1]? arg[1][3] : 0;
  a05=(a05-a10);
  a10=8.5883000000000001e-02;
  a05=(a05/a10);
  if (res[0]!=0) res[0][13]=a05;
  a05=arg[1]? arg[1][4] : 0;
  a05=(a05-a14);
  a05=(a05/a10);
  if (res[0]!=0) res[0][14]=a05;
  a05=arg[1]? arg[1][5] : 0;
  a05=(a05-a19);
  a05=(a05/a10);
  if (res[0]!=0) res[0][15]=a05;
  return 0;
}

CASADI_SYMBOL_EXPORT int tilt_tri_servo_mdl_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int tilt_tri_servo_mdl_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int tilt_tri_servo_mdl_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tilt_tri_servo_mdl_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int tilt_tri_servo_mdl_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tilt_tri_servo_mdl_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void tilt_tri_servo_mdl_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void tilt_tri_servo_mdl_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int tilt_tri_servo_mdl_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int tilt_tri_servo_mdl_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real tilt_tri_servo_mdl_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tilt_tri_servo_mdl_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tilt_tri_servo_mdl_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tilt_tri_servo_mdl_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tilt_tri_servo_mdl_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int tilt_tri_servo_mdl_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int tilt_tri_servo_mdl_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
