/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) tilt_tri_servo_mdl_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {16, 1, 1};
static const casadi_int casadi_s1[3] = {6, 1, 1};
static const casadi_int casadi_s2[3] = {4, 1, 1};
static const casadi_int casadi_s3[3] = {22, 1, 1};

/* tilt_tri_servo_mdl_expl_vde_adj:(i0[16],i1[16],i2[6],i3[4])->(o0[22]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44;
  a00=0.;
  if (res[0]!=0) res[0][0]=a00;
  if (res[0]!=0) res[0][1]=a00;
  if (res[0]!=0) res[0][2]=a00;
  a00=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][3]=a00;
  a00=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][4]=a00;
  a00=arg[1]? arg[1][2] : 0;
  if (res[0]!=0) res[0][5]=a00;
  a00=arg[0]? arg[0][12] : 0;
  a01=5.0000000000000000e-01;
  a02=arg[1]? arg[1][9] : 0;
  a02=(a01*a02);
  a03=(a00*a02);
  a04=arg[0]? arg[0][11] : 0;
  a05=arg[1]? arg[1][8] : 0;
  a05=(a01*a05);
  a06=(a04*a05);
  a03=(a03+a06);
  a06=arg[0]? arg[0][10] : 0;
  a07=arg[1]? arg[1][7] : 0;
  a07=(a01*a07);
  a08=(a06*a07);
  a03=(a03+a08);
  a08=2.;
  a09=arg[0]? arg[0][7] : 0;
  a10=3.4196805393221158e-01;
  a11=arg[0]? arg[0][13] : 0;
  a12=sin(a11);
  a13=arg[2]? arg[2][0] : 0;
  a14=(a12*a13);
  a15=(a10*a14);
  a16=3.4201891609359575e-01;
  a17=arg[0]? arg[0][14] : 0;
  a18=sin(a17);
  a19=arg[2]? arg[2][1] : 0;
  a20=(a18*a19);
  a21=(a16*a20);
  a15=(a15+a21);
  a21=-9.9999999551050445e-01;
  a22=arg[0]? arg[0][15] : 0;
  a23=sin(a22);
  a24=arg[2]? arg[2][2] : 0;
  a25=(a23*a24);
  a26=(a21*a25);
  a15=(a15+a26);
  a26=6.5734550737212993e-01;
  a27=arg[1]? arg[1][5] : 0;
  a27=(a26*a27);
  a28=(a15*a27);
  a29=(a09*a28);
  a29=(a08*a29);
  a03=(a03-a29);
  a29=arg[0]? arg[0][8] : 0;
  a30=9.3971157813970552e-01;
  a14=(a30*a14);
  a31=-9.3969306746094605e-01;
  a20=(a31*a20);
  a14=(a14+a20);
  a20=9.4757538721294815e-05;
  a25=(a20*a25);
  a14=(a14+a25);
  a25=(a14*a27);
  a32=(a29*a25);
  a32=(a08*a32);
  a03=(a03+a32);
  a32=arg[0]? arg[0][9] : 0;
  a33=arg[1]? arg[1][4] : 0;
  a33=(a26*a33);
  a34=(a14*a33);
  a35=(a32*a34);
  a35=(a08*a35);
  a03=(a03-a35);
  a11=cos(a11);
  a35=(a11*a13);
  a17=cos(a17);
  a36=(a17*a19);
  a35=(a35+a36);
  a22=cos(a22);
  a36=(a22*a24);
  a35=(a35+a36);
  a36=(a35*a33);
  a37=(a09*a36);
  a37=(a08*a37);
  a03=(a03-a37);
  a37=arg[1]? arg[1][3] : 0;
  a26=(a26*a37);
  a37=(a15*a26);
  a38=(a32*a37);
  a38=(a08*a38);
  a03=(a03+a38);
  a38=(a35*a26);
  a39=(a29*a38);
  a39=(a08*a39);
  a03=(a03+a39);
  if (res[0]!=0) res[0][6]=a03;
  a03=(a04*a02);
  a39=(a00*a05);
  a03=(a03-a39);
  a39=arg[1]? arg[1][6] : 0;
  a01=(a01*a39);
  a39=(a06*a01);
  a03=(a03-a39);
  a39=arg[0]? arg[0][6] : 0;
  a40=(a08*a39);
  a41=(a40*a28);
  a03=(a03-a41);
  a41=(a32*a25);
  a41=(a08*a41);
  a03=(a03-a41);
  a41=(a09+a09);
  a35=(a35*a27);
  a35=(a08*a35);
  a42=(a41*a35);
  a03=(a03-a42);
  a15=(a15*a33);
  a15=(a08*a15);
  a41=(a41*a15);
  a03=(a03+a41);
  a41=(a29*a34);
  a41=(a08*a41);
  a03=(a03-a41);
  a41=(a40*a36);
  a03=(a03-a41);
  a41=(a29*a37);
  a41=(a08*a41);
  a03=(a03-a41);
  a41=(a32*a38);
  a41=(a08*a41);
  a03=(a03+a41);
  if (res[0]!=0) res[0][7]=a03;
  a03=(a00*a07);
  a41=(a06*a02);
  a03=(a03-a41);
  a41=(a04*a01);
  a03=(a03-a41);
  a41=(a32*a28);
  a41=(a08*a41);
  a03=(a03-a41);
  a41=(a40*a25);
  a03=(a03+a41);
  a41=(a29+a29);
  a35=(a41*a35);
  a03=(a03-a35);
  a35=(a08*a09);
  a42=(a35*a34);
  a03=(a03-a42);
  a42=(a32*a36);
  a42=(a08*a42);
  a03=(a03+a42);
  a42=(a35*a37);
  a03=(a03-a42);
  a14=(a14*a26);
  a14=(a08*a14);
  a41=(a41*a14);
  a03=(a03+a41);
  a41=(a40*a38);
  a03=(a03+a41);
  if (res[0]!=0) res[0][8]=a03;
  a03=(a06*a05);
  a41=(a04*a07);
  a03=(a03-a41);
  a41=(a00*a01);
  a03=(a03-a41);
  a41=(a08*a29);
  a28=(a41*a28);
  a03=(a03-a28);
  a25=(a35*a25);
  a03=(a03-a25);
  a25=(a32+a32);
  a15=(a25*a15);
  a03=(a03+a15);
  a34=(a40*a34);
  a03=(a03-a34);
  a36=(a41*a36);
  a03=(a03+a36);
  a37=(a40*a37);
  a03=(a03+a37);
  a25=(a25*a14);
  a03=(a03+a25);
  a38=(a35*a38);
  a03=(a03+a38);
  if (res[0]!=0) res[0][9]=a03;
  a03=3.8796100000000000e-02;
  a38=(a03*a00);
  a25=5.2399367015646455e+01;
  a14=arg[1]? arg[1][11] : 0;
  a25=(a25*a14);
  a14=(a38*a25);
  a37=1.9084199999999999e-02;
  a36=(a37*a04);
  a34=2.5775786741450815e+01;
  a15=arg[1]? arg[1][12] : 0;
  a34=(a34*a15);
  a15=(a36*a34);
  a14=(a14-a15);
  a15=2.5101999999999999e-02;
  a28=(a04*a34);
  a42=(a00*a25);
  a28=(a28-a42);
  a28=(a15*a28);
  a14=(a14+a28);
  a28=(a29*a02);
  a14=(a14-a28);
  a28=(a32*a05);
  a14=(a14+a28);
  a28=(a39*a07);
  a14=(a14+a28);
  a28=(a09*a01);
  a14=(a14-a28);
  if (res[0]!=0) res[0][10]=a14;
  a15=(a15*a06);
  a14=(a15*a34);
  a28=3.9837463150346586e+01;
  a42=arg[1]? arg[1][10] : 0;
  a28=(a28*a42);
  a00=(a00*a28);
  a42=(a06*a34);
  a00=(a00-a42);
  a37=(a37*a00);
  a14=(a14+a37);
  a38=(a38*a28);
  a14=(a14-a38);
  a38=(a09*a02);
  a14=(a14+a38);
  a38=(a39*a05);
  a14=(a14+a38);
  a38=(a32*a07);
  a14=(a14-a38);
  a38=(a29*a01);
  a14=(a14-a38);
  if (res[0]!=0) res[0][11]=a14;
  a36=(a36*a28);
  a15=(a15*a25);
  a36=(a36-a15);
  a06=(a06*a25);
  a04=(a04*a28);
  a06=(a06-a04);
  a03=(a03*a06);
  a36=(a36+a03);
  a39=(a39*a02);
  a36=(a36+a39);
  a05=(a09*a05);
  a36=(a36-a05);
  a07=(a29*a07);
  a36=(a36+a07);
  a01=(a32*a01);
  a36=(a36-a01);
  if (res[0]!=0) res[0][12]=a36;
  a36=-2.3752000000000001e-01;
  a01=(a36*a34);
  a07=2.5907500000000000e-02;
  a05=(a07*a25);
  a01=(a01-a05);
  a01=(a30*a01);
  a07=(a07*a28);
  a39=8.6435300000000007e-02;
  a02=(a39*a34);
  a02=(a07-a02);
  a03=(a10*a02);
  a01=(a01+a03);
  a03=(a13*a01);
  a06=1.7200000000000000e-02;
  a04=(a06*a13);
  a15=(a10*a25);
  a14=(a30*a28);
  a15=(a15+a14);
  a14=(a04*a15);
  a03=(a03+a14);
  a41=(a41*a32);
  a14=(a40*a09);
  a38=(a41+a14);
  a38=(a38*a27);
  a37=1.;
  a09=casadi_sq(a09);
  a09=(a08*a09);
  a09=(a37-a09);
  a00=casadi_sq(a32);
  a00=(a08*a00);
  a42=(a09-a00);
  a42=(a42*a33);
  a38=(a38+a42);
  a42=(a35*a29);
  a43=(a40*a32);
  a44=(a42-a43);
  a44=(a44*a26);
  a38=(a38+a44);
  a10=(a10*a38);
  a35=(a35*a32);
  a40=(a40*a29);
  a32=(a35-a40);
  a32=(a32*a27);
  a42=(a42+a43);
  a42=(a42*a33);
  a32=(a32+a42);
  a29=casadi_sq(a29);
  a08=(a08*a29);
  a37=(a37-a08);
  a37=(a37-a00);
  a37=(a37*a26);
  a32=(a32+a37);
  a30=(a30*a32);
  a10=(a10+a30);
  a30=(a13*a10);
  a03=(a03-a30);
  a03=(a11*a03);
  a30=1.1643747889570696e+01;
  a37=arg[1]? arg[1][13] : 0;
  a37=(a30*a37);
  a03=(a03-a37);
  a36=(a36*a28);
  a39=(a39*a25);
  a36=(a36-a39);
  a00=(a13*a36);
  a04=(a04*a34);
  a00=(a00-a04);
  a09=(a09-a08);
  a09=(a09*a27);
  a41=(a41-a14);
  a41=(a41*a33);
  a09=(a09+a41);
  a35=(a35+a40);
  a35=(a35*a26);
  a09=(a09+a35);
  a13=(a13*a09);
  a00=(a00+a13);
  a00=(a12*a00);
  a03=(a03-a00);
  if (res[0]!=0) res[0][13]=a03;
  a03=2.3748000000000000e-01;
  a00=(a03*a34);
  a00=(a00-a05);
  a00=(a31*a00);
  a02=(a16*a02);
  a00=(a00+a02);
  a02=(a19*a00);
  a13=(a06*a19);
  a35=(a16*a25);
  a26=(a31*a28);
  a35=(a35+a26);
  a26=(a13*a35);
  a02=(a02-a26);
  a16=(a16*a38);
  a31=(a31*a32);
  a16=(a16+a31);
  a31=(a19*a16);
  a02=(a02-a31);
  a02=(a17*a02);
  a31=arg[1]? arg[1][14] : 0;
  a31=(a30*a31);
  a02=(a02-a31);
  a13=(a13*a34);
  a03=(a03*a28);
  a03=(a03-a39);
  a39=(a19*a03);
  a13=(a13+a39);
  a19=(a19*a09);
  a13=(a13+a19);
  a13=(a18*a13);
  a02=(a02-a13);
  if (res[0]!=0) res[0][14]=a02;
  a02=-2.0000000000000002e-05;
  a13=(a02*a34);
  a13=(a13-a05);
  a13=(a20*a13);
  a05=-2.1106500000000000e-01;
  a19=(a05*a34);
  a07=(a07-a19);
  a07=(a21*a07);
  a13=(a13+a07);
  a07=(a24*a13);
  a19=(a06*a24);
  a39=(a21*a25);
  a26=(a20*a28);
  a39=(a39+a26);
  a26=(a19*a39);
  a07=(a07+a26);
  a21=(a21*a38);
  a20=(a20*a32);
  a21=(a21+a20);
  a20=(a24*a21);
  a07=(a07-a20);
  a07=(a22*a07);
  a20=arg[1]? arg[1][15] : 0;
  a30=(a30*a20);
  a07=(a07-a30);
  a02=(a02*a28);
  a05=(a05*a25);
  a02=(a02-a05);
  a05=(a24*a02);
  a19=(a19*a34);
  a05=(a05-a19);
  a24=(a24*a09);
  a05=(a05+a24);
  a05=(a23*a05);
  a07=(a07-a05);
  if (res[0]!=0) res[0][15]=a07;
  a01=(a12*a01);
  a36=(a11*a36);
  a01=(a01+a36);
  a15=(a12*a15);
  a36=(a11*a34);
  a15=(a15-a36);
  a15=(a06*a15);
  a01=(a01+a15);
  a12=(a12*a10);
  a01=(a01-a12);
  a11=(a11*a09);
  a01=(a01+a11);
  if (res[0]!=0) res[0][16]=a01;
  a00=(a18*a00);
  a03=(a17*a03);
  a00=(a00+a03);
  a03=(a17*a34);
  a35=(a18*a35);
  a03=(a03-a35);
  a03=(a06*a03);
  a00=(a00+a03);
  a18=(a18*a16);
  a00=(a00-a18);
  a17=(a17*a09);
  a00=(a00+a17);
  if (res[0]!=0) res[0][17]=a00;
  a13=(a23*a13);
  a02=(a22*a02);
  a13=(a13+a02);
  a39=(a23*a39);
  a34=(a22*a34);
  a39=(a39-a34);
  a06=(a06*a39);
  a13=(a13+a06);
  a23=(a23*a21);
  a13=(a13-a23);
  a22=(a22*a09);
  a13=(a13+a22);
  if (res[0]!=0) res[0][18]=a13;
  if (res[0]!=0) res[0][19]=a37;
  if (res[0]!=0) res[0][20]=a31;
  if (res[0]!=0) res[0][21]=a30;
  return 0;
}

CASADI_SYMBOL_EXPORT int tilt_tri_servo_mdl_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int tilt_tri_servo_mdl_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int tilt_tri_servo_mdl_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tilt_tri_servo_mdl_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int tilt_tri_servo_mdl_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tilt_tri_servo_mdl_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void tilt_tri_servo_mdl_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void tilt_tri_servo_mdl_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int tilt_tri_servo_mdl_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int tilt_tri_servo_mdl_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real tilt_tri_servo_mdl_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tilt_tri_servo_mdl_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tilt_tri_servo_mdl_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tilt_tri_servo_mdl_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tilt_tri_servo_mdl_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int tilt_tri_servo_mdl_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int tilt_tri_servo_mdl_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
